export const PHASE_10B_ASSET_INTELLIGENCE_CORE_GATES = [
  ["A", "Repository identity"],
  ["B", "PI v1 tag integrity"],
  ["C", "II v1 tag integrity"],
  ["D", "Phase 10A baseline intact"],
  ["E", "Shared-domain ownership"],
  ["F", "Duplicate asset ownership"],
  ["G", "Core version and flags"],
  ["H", "Asset Snapshot model"],
  ["I", "Health Index abstraction"],
  ["J", "Intelligence Source Registry"],
  ["K", "Historical Intelligence Timeline"],
  ["L", "Asset Intelligence Engine"],
  ["M", "Hosted persistence"],
  ["N", "II public contract consumption"],
  ["O", "Condition vertical slice"],
  ["P", "Events governance"],
  ["Q", "Capabilities and services"],
  ["R", "Architecture docs"],
  ["S", "Core manifest"],
  ["T", "No full module GA claim"],
  ["U", "RUL and accuracy uncertified"],
  ["V", "Unit and architecture tests"],
  ["W", "Secret exposure"],
  ["X", "Artifact identity"],
  ["Y", "Phase 10C readiness"],
] as const;

export type Phase10bGateId = (typeof PHASE_10B_ASSET_INTELLIGENCE_CORE_GATES)[number][0];
