import {
  AU_CONCRETE_IMPLEMENTATION_MATURITY,
  AU_CONCRETE_PACK_CERTIFIED,
  AU_CONCRETE_PRODUCT_CLAIM_LEVEL,
  AU_CONCRETE_STANDARD_CONFORMANCE_STATE,
  AU_CONCRETE_STANDARD_EDITION,
  AU_CONCRETE_STANDARD_FAMILY_BOUND,
  AU_D1E_RECONCILIATION,
  AU_IMPLEMENTED_CODE_METHOD_COUNT,
  AU_NUMERICAL_CONCRETE_CODE_METHOD_COUNT,
  AU_PARAMETER_LEAKAGE_INTO_COMMON_RC_KERNEL,
  COMPLETE_CONCRETE_DESIGN_PRODUCT,
  CONCRETE_DESIGN_IMPLIES_GEOTECHNICAL_VALIDATION,
  CONCRETE_OPTIMIZATION_ACCEPTS_UNDETERMINED,
  D1E_ARCHITECTURE_PHASE_COMPLETE,
  D1E_ENGINEERING_AUTHORITY_LAYERS_SEPARATE,
  D1E_GLOBAL_CONCRETE_ARCHITECTURE_VALIDATED,
  D1E_GLOBAL_FAIL_CLOSED_AUDIT,
  D1E_GLOBAL_RELEASE_CLASSIFICATION,
  D1E_INVERSE_DESIGN_ARCHITECTURE_READY,
  D1E_MISLEADING_CONCRETE_PRODUCT_CLAIMS,
  D1E_OPTIMIZATION_ACCEPTS_UNDETERMINED,
  D1E_PARETO_ACCEPTS_UNDETERMINED_AS_FEASIBLE,
  EU_CONCRETE_IMPLEMENTATION_MATURITY,
  EU_CONCRETE_MULTI_COUNTRY_SUPPORT,
  EU_CONCRETE_NATIONAL_ANNEX_MODEL,
  EU_CONCRETE_NDP_MODEL,
  EU_CONCRETE_PACK_CERTIFIED,
  EU_CONCRETE_PRODUCT_CLAIM_LEVEL,
  EU_CONCRETE_STANDARD_CONFORMANCE_STATE,
  EU_CONCRETE_STANDARD_EDITION,
  EU_CONCRETE_STANDARD_GENERATION_MODEL,
  EU_CONCRETE_STANDARD_PART_MODEL,
  EU_D1E_RECONCILIATION,
  EU_IMPLEMENTED_CODE_METHOD_COUNT,
  EU_NUMERICAL_CONCRETE_CODE_METHOD_COUNT,
  GENERATIVE_MODEL_CAN_APPROVE_DESIGN,
  GENERATIVE_MODEL_CAN_BYPASS_CODE_ADAPTER,
  GENERATIVE_MODEL_CAN_BYPASS_RC_KERNEL,
  GENERATIVE_MODEL_EQUALS_ENGINEERING_AUTHORITY,
  GENERAL_CONCRETE_CONNECTION_DESIGN_VALIDATED,
  GENERAL_CONCRETE_FEA_CLAIMED,
  GENERAL_CONCRETE_FIRE_DESIGN_VALIDATED,
  GENERAL_CONCRETE_SEISMIC_DESIGN_VALIDATED,
  GENERAL_PRESTRESSED_CONCRETE_DESIGN_VALIDATED,
  IMPLEMENTED_EU_CONCRETE_CODE_FLEXURE_METHODS,
  IMPLEMENTED_US_CONCRETE_CODE_FLEXURE_METHODS,
  INTERNATIONAL_EUROCODE_CONCRETE_PROFILE_SUPPORTED,
  PARALLEL_AU_RC_CORE,
  PARALLEL_AU_RC_SECTION_SOLVER_CREATED,
  PARALLEL_EU_CONCRETE_STANDARD_FRAMEWORK_CREATED,
  PARALLEL_EU_RC_CORE,
  PARALLEL_EU_RC_SECTION_KERNEL_CREATED,
  PARALLEL_US_CONCRETE_STANDARD_FRAMEWORK_CREATED,
  PARALLEL_US_RC_CORE,
  PARALLEL_US_RC_SECTION_KERNEL_CREATED,
  SILENT_CONCRETE_STANDARD_EDITION_INFERENCE,
  STANDARD_UPDATE_OVERWRITES_HISTORICAL_CONCRETE_RULE,
  STANDARD_UPDATE_OVERWRITES_HISTORICAL_US_CONCRETE_RULE,
  THREE_JURISDICTION_CONCRETE_ARCHITECTURE_AUDIT,
  THREE_JURISDICTION_RC_KERNEL_REUSE_AUDIT,
  US_BUILDING_CODE_AND_ACI_CONCRETE_STANDARD_SEPARATE,
  US_CONCRETE_BUILDING_CODE_ADOPTION_CONTEXT,
  US_CONCRETE_DIRECT_CONTRACT_PROFILE_SUPPORTED,
  US_CONCRETE_IMPLEMENTATION_MATURITY,
  US_CONCRETE_LOCAL_AMENDMENT_MODEL,
  US_CONCRETE_PACK_CERTIFIED,
  US_CONCRETE_PRODUCT_CLAIM_LEVEL,
  US_CONCRETE_STANDARD_CONFORMANCE_STATE,
  US_CONCRETE_STANDARD_EDITION,
  US_CONCRETE_STANDARD_FAMILY_BOUND,
  US_D1E_RECONCILIATION,
  US_IMPLEMENTED_CODE_METHOD_COUNT,
  US_NUMERICAL_CONCRETE_CODE_METHOD_COUNT,
  ACI_CONCRETE_NOT_HARDCODED_TO_US_GEOGRAPHY,
  INTERNATIONAL_ACI_CONCRETE_PROFILE_SUPPORTED,
} from "@rtb/types";
import { IMPLEMENTED_AU_CONCRETE_CODE_FLEXURE_METHODS } from "../au-flexure";
import { assertCandidateFullConcreteRecheck } from "../orchestration";
import { assertAiCannotOverrideSectionKernel } from "../section-mechanics";

export const D1E_GLOBAL_ARCHITECTURE_STACK = [
  "COMMON STRUCTURAL DOMAIN",
  "COMMON CONCRETE OBJECT MODEL",
  "COMMON RC SECTION KERNEL",
  "JURISDICTION-SPECIFIC STANDARD ADAPTERS",
  "CODE-PROFILE DESIGN METHODS",
  "MEMBER / ELEMENT ORCHESTRATION",
  "VALIDATION / CONFORMANCE",
  "HUMAN ENGINEERING APPROVAL",
] as const;

export const D1E_ENGINEERING_AUTHORITY_LAYERS = [
  "MECHANICS_REFERENCE",
  "CODE PROFILE",
  "CODE DESIGN RESULT",
  "STANDARD CONFORMANCE",
  "BUILDING-CODE / CONTRACT COMPLIANCE",
  "ENGINEERING APPROVAL",
] as const;

export const D1E_GLOBAL_FAIL_CLOSED_CASES = [
  "invalid geometry",
  "missing material",
  "missing reinforcement",
  "unknown standard edition",
  "missing required standard context",
  "missing code method",
  "missing material rule",
  "missing stress-block rule",
  "missing strain limit",
  "missing design factor",
  "solver non-convergence",
  "unsupported action combination",
  "stale result",
  "unvalidated method requested as validated",
] as const;

export const D1E_INVERSE_DESIGN_PIPELINE = [
  "candidate generation",
  "D1E-1 deterministic geometry validation",
  "common mechanics",
  "jurisdiction adapter",
  "validated code checks",
  "MTO / cost / carbon",
  "Pareto optimizer",
  "engineer decision",
] as const;

export function assertD1eCloseoutAudits(): void {
  if (!D1E_GLOBAL_CONCRETE_ARCHITECTURE_VALIDATED) throw new Error("global concrete architecture must be validated");
  if (PARALLEL_AU_RC_CORE || PARALLEL_EU_RC_CORE || PARALLEL_US_RC_CORE) {
    throw new Error("parallel jurisdiction RC cores are forbidden");
  }
  if (PARALLEL_AU_RC_SECTION_SOLVER_CREATED || PARALLEL_EU_RC_SECTION_KERNEL_CREATED || PARALLEL_US_RC_SECTION_KERNEL_CREATED) {
    throw new Error("parallel RC kernels are forbidden");
  }
  if (PARALLEL_EU_CONCRETE_STANDARD_FRAMEWORK_CREATED || PARALLEL_US_CONCRETE_STANDARD_FRAMEWORK_CREATED) {
    throw new Error("parallel standard frameworks are forbidden");
  }
  if (THREE_JURISDICTION_CONCRETE_ARCHITECTURE_AUDIT !== "PASS") throw new Error("three-jurisdiction architecture audit must pass");
  if (THREE_JURISDICTION_RC_KERNEL_REUSE_AUDIT !== "PASS") throw new Error("three-jurisdiction kernel reuse must pass");
  if (!D1E_ENGINEERING_AUTHORITY_LAYERS_SEPARATE) throw new Error("engineering authority layers must remain separate");
  if (AU_D1E_RECONCILIATION !== "PASS" || EU_D1E_RECONCILIATION !== "PASS" || US_D1E_RECONCILIATION !== "PASS") {
    throw new Error("jurisdiction D1E reconciliation must pass");
  }
  if (AU_CONCRETE_IMPLEMENTATION_MATURITY !== "FRAMEWORK_PLUS_COMMON_MECHANICS") throw new Error("AU maturity drifted");
  if (EU_CONCRETE_IMPLEMENTATION_MATURITY !== "FRAMEWORK_PLUS_COMMON_MECHANICS") throw new Error("EU maturity drifted");
  if (US_CONCRETE_IMPLEMENTATION_MATURITY !== "FRAMEWORK_PLUS_COMMON_MECHANICS") throw new Error("US maturity drifted");
  if (AU_CONCRETE_STANDARD_CONFORMANCE_STATE !== "INTENDED_PROFILE") throw new Error("AU conformance drifted");
  if (EU_CONCRETE_STANDARD_CONFORMANCE_STATE !== "INTENDED_PROFILE") throw new Error("EU conformance drifted");
  if (US_CONCRETE_STANDARD_CONFORMANCE_STATE !== "INTENDED_PROFILE") throw new Error("US conformance drifted");
  if (AU_CONCRETE_PRODUCT_CLAIM_LEVEL !== "AU_CONCRETE_MECHANICS_REFERENCE_CAPABILITY") throw new Error("AU claim drifted");
  if (EU_CONCRETE_PRODUCT_CLAIM_LEVEL !== "EU_CONCRETE_MECHANICS_REFERENCE_CAPABILITY") throw new Error("EU claim drifted");
  if (US_CONCRETE_PRODUCT_CLAIM_LEVEL !== "US_CONCRETE_MECHANICS_REFERENCE_CAPABILITY") throw new Error("US claim drifted");
  if (AU_CONCRETE_PACK_CERTIFIED || EU_CONCRETE_PACK_CERTIFIED || US_CONCRETE_PACK_CERTIFIED) {
    throw new Error("no concrete pack is certified");
  }
  if (
    AU_IMPLEMENTED_CODE_METHOD_COUNT !== 0 ||
    EU_IMPLEMENTED_CODE_METHOD_COUNT !== 0 ||
    US_IMPLEMENTED_CODE_METHOD_COUNT !== 0 ||
    AU_NUMERICAL_CONCRETE_CODE_METHOD_COUNT !== 0 ||
    EU_NUMERICAL_CONCRETE_CODE_METHOD_COUNT !== 0 ||
    US_NUMERICAL_CONCRETE_CODE_METHOD_COUNT !== 0
  ) {
    throw new Error("numerical concrete code method counts must remain zero");
  }
  if (
    IMPLEMENTED_AU_CONCRETE_CODE_FLEXURE_METHODS !== "NONE" ||
    IMPLEMENTED_EU_CONCRETE_CODE_FLEXURE_METHODS !== "NONE" ||
    IMPLEMENTED_US_CONCRETE_CODE_FLEXURE_METHODS !== "NONE"
  ) {
    throw new Error("implemented code flexure methods must remain NONE");
  }
  if (AU_CONCRETE_STANDARD_EDITION !== "UNKNOWN_PENDING_CONFIRMATION") throw new Error("AU edition must remain unconfirmed");
  if (EU_CONCRETE_STANDARD_EDITION !== "UNKNOWN_PENDING_CONFIRMATION") throw new Error("EU edition must remain unconfirmed");
  if (US_CONCRETE_STANDARD_EDITION !== "UNKNOWN_PENDING_CONFIRMATION") throw new Error("US edition must remain unconfirmed");
  if (SILENT_CONCRETE_STANDARD_EDITION_INFERENCE) throw new Error("silent standard-edition inference is forbidden");
  if (!AU_CONCRETE_STANDARD_FAMILY_BOUND || AU_PARAMETER_LEAKAGE_INTO_COMMON_RC_KERNEL) {
    throw new Error("AU governance isolation failed");
  }
  if (
    !EU_CONCRETE_STANDARD_GENERATION_MODEL ||
    !EU_CONCRETE_STANDARD_PART_MODEL ||
    !EU_CONCRETE_NATIONAL_ANNEX_MODEL ||
    !EU_CONCRETE_NDP_MODEL ||
    !EU_CONCRETE_MULTI_COUNTRY_SUPPORT ||
    !INTERNATIONAL_EUROCODE_CONCRETE_PROFILE_SUPPORTED ||
    STANDARD_UPDATE_OVERWRITES_HISTORICAL_CONCRETE_RULE
  ) {
    throw new Error("EU concrete governance reconciliation failed");
  }
  if (
    !US_CONCRETE_STANDARD_FAMILY_BOUND ||
    !US_BUILDING_CODE_AND_ACI_CONCRETE_STANDARD_SEPARATE ||
    !US_CONCRETE_BUILDING_CODE_ADOPTION_CONTEXT ||
    !US_CONCRETE_LOCAL_AMENDMENT_MODEL ||
    !US_CONCRETE_DIRECT_CONTRACT_PROFILE_SUPPORTED ||
    !ACI_CONCRETE_NOT_HARDCODED_TO_US_GEOGRAPHY ||
    !INTERNATIONAL_ACI_CONCRETE_PROFILE_SUPPORTED ||
    STANDARD_UPDATE_OVERWRITES_HISTORICAL_US_CONCRETE_RULE
  ) {
    throw new Error("US concrete governance reconciliation failed");
  }
  if (D1E_GLOBAL_FAIL_CLOSED_AUDIT !== "PASS") throw new Error("global fail-closed audit must pass");
  if (!D1E_INVERSE_DESIGN_ARCHITECTURE_READY) throw new Error("inverse-design architecture must remain ready");
  if (
    GENERATIVE_MODEL_EQUALS_ENGINEERING_AUTHORITY ||
    GENERATIVE_MODEL_CAN_BYPASS_RC_KERNEL ||
    GENERATIVE_MODEL_CAN_BYPASS_CODE_ADAPTER ||
    GENERATIVE_MODEL_CAN_APPROVE_DESIGN
  ) {
    throw new Error("generative model must not hold engineering authority");
  }
  if (
    D1E_OPTIMIZATION_ACCEPTS_UNDETERMINED ||
    D1E_PARETO_ACCEPTS_UNDETERMINED_AS_FEASIBLE ||
    CONCRETE_OPTIMIZATION_ACCEPTS_UNDETERMINED
  ) {
    throw new Error("optimization must not accept undetermined as feasible");
  }
  if (
    GENERAL_CONCRETE_FEA_CLAIMED ||
    GENERAL_PRESTRESSED_CONCRETE_DESIGN_VALIDATED ||
    GENERAL_CONCRETE_CONNECTION_DESIGN_VALIDATED ||
    GENERAL_CONCRETE_SEISMIC_DESIGN_VALIDATED ||
    GENERAL_CONCRETE_FIRE_DESIGN_VALIDATED ||
    CONCRETE_DESIGN_IMPLIES_GEOTECHNICAL_VALIDATION
  ) {
    throw new Error("unsupported concrete capabilities must remain unvalidated");
  }
  if (D1E_ARCHITECTURE_PHASE_COMPLETE && COMPLETE_CONCRETE_DESIGN_PRODUCT) {
    throw new Error("architecture complete must not imply a complete concrete design product");
  }
  if (D1E_GLOBAL_RELEASE_CLASSIFICATION !== "INTERNAL_ENGINEERING_REFERENCE") {
    throw new Error("D1E release classification must remain INTERNAL_ENGINEERING_REFERENCE");
  }
  if (D1E_MISLEADING_CONCRETE_PRODUCT_CLAIMS !== "NONE") throw new Error("misleading concrete product claims detected");
  assertAiCannotOverrideSectionKernel();
  assertCandidateFullConcreteRecheck({
    candidateSectionRef: "sec-closeout",
    proposedBy: "AI",
    deterministicRecheckRequired: true,
    rechecked: true,
    memberCheckState: "CHECK_SATISFIED",
  });
}
