import type { D1dCommonMechanicsRecord } from "@rtb/types";

const AU_EU_US = ["AU", "EU", "US"] as const;
const NOT_CODE = "not AS 3600, EN 1992, National Annex/NDP, or ACI 318 capacity";

export const COMMON_RC_KERNEL_INVENTORY: readonly D1dCommonMechanicsRecord[] = [
  {
    commonMethodId: "COMMON_RC_SECTION_GEOMETRY",
    supportedInputs: ["shape", "dimensions", "origin"],
    supportedOutputs: "section outlines",
    units: "mm",
    assumptions: "explicit geometry; no code shape classification",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not a national section catalog; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_POLYGON_GEOMETRY",
    supportedInputs: ["outer polygon vertices"],
    supportedOutputs: "polygonal outline",
    units: "mm",
    assumptions: "simple polygons; winding explicit",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not a code-approved section family; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_VOIDS",
    supportedInputs: ["inner polygons / voids"],
    supportedOutputs: "void outlines subtracted from gross area",
    units: "mm",
    assumptions: "voids contained in outer polygon",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not hollow-section code design; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_GROSS_SECTION_PROPERTIES",
    supportedInputs: ["outlines including voids"],
    supportedOutputs: "Ag, Ix, Iy, Ixy, centroid",
    units: "mm / mm2 / mm4",
    assumptions: "gross concrete geometry only",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not cracked transformed section or code Ieff; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_PRINCIPAL_PROPERTIES",
    supportedInputs: ["gross second moments"],
    supportedOutputs: "principal Ix/Iy and orientation",
    units: "mm4 / rad",
    assumptions: "elastic geometric principal axes",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code axis classification; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_REINFORCEMENT_GEOMETRY",
    supportedInputs: ["bar coordinates", "explicit bar area"],
    supportedOutputs: "bar points and areas",
    units: "mm / mm2",
    assumptions: "area not inferred from designation",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code bar-area tables; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_BAR_CONTAINMENT",
    supportedInputs: ["bar coordinates", "section outlines"],
    supportedOutputs: "containment validity",
    units: "dimensionless",
    assumptions: "bars must lie in concrete, not in voids",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code cover compliance; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_GEOMETRIC_CLEARANCES",
    supportedInputs: ["bar coordinates", "surface polygons"],
    supportedOutputs: "geometric clearance to surface",
    units: "mm",
    assumptions: "geometry only; no exposure class",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `geometric clearance ≠ AS 3600 / EN 1992 / ACI cover; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_PLANE_SECTION_KINEMATICS",
    supportedInputs: ["ε0", "φx", "φy", "origin"],
    supportedOutputs: "plane-section strain field",
    units: "strain / 1/mm",
    assumptions: "Navier plane sections remain plane",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code ultimate strain profile; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_BAR_STRAIN",
    supportedInputs: ["strain field", "bar coordinates"],
    supportedOutputs: "εs at each bar",
    units: "strain",
    assumptions: "perfect bond; strain compatibility",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code yield/strain-limit check; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_MATERIAL_RESPONSE_CONTRACT",
    supportedInputs: ["explicit governed E", "tension treatment"],
    supportedOutputs: "σ(ε) contract; linear-elastic reference models",
    units: "MPa",
    assumptions: "no guessed constitutive parameters",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not AS 3600 / EN 1992 / ACI stress-strain laws; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_SECTION_DISCRETIZATION",
    supportedInputs: ["geometry", "fiber count"],
    supportedOutputs: "fiber areas and centroids",
    units: "mm2 / mm",
    assumptions: "area conservation checked",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not structural FEA mesh; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_SECTION_INTEGRATION",
    supportedInputs: ["fibers", "bars", "material response", "strain field"],
    supportedOutputs: "N, Mx, My",
    units: "N / Nmm",
    assumptions: "fiber + bar summation",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `section integration ≠ general structural FEA; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_EQUILIBRIUM_RESIDUAL",
    supportedInputs: ["integrated resultants", "target actions"],
    supportedOutputs: "residual vector",
    units: "N / Nmm",
    assumptions: "first-order section equilibrium",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code utilization; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_EQUILIBRIUM_SOLVER",
    supportedInputs: ["target N/M", "elastic models"],
    supportedOutputs: "converged strain state or fail-closed",
    units: "strain / 1/mm",
    assumptions: "Newton-type elastic solver; nonconvergence fails closed",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code capacity solver; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_NEUTRAL_AXIS_GEOMETRY",
    supportedInputs: ["converged strain state"],
    supportedOutputs: "neutral-axis location",
    units: "mm",
    assumptions: "derived from plane-section kinematics",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `neutral axis ≠ code flexural capacity state; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_ELASTIC_REFERENCE_MECHANICS",
    supportedInputs: ["gross properties", "governed E", "Es"],
    supportedOutputs: "uncracked elastic reference resultants",
    units: "N / Nmm",
    assumptions: "uncracked transformed-style elastic reference",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `elastic reference ≠ AS 3600 / EN 1992 / ACI flexural resistance; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_CONFIGURATION_FINGERPRINTS",
    supportedInputs: ["geometry", "layout", "material refs", "units"],
    supportedOutputs: "sha256 configuration fingerprint",
    units: "hex digest",
    assumptions: "stable JSON canonicalization",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `fingerprint is not a conformance certificate; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_RC_INVALIDATION",
    supportedInputs: ["previous fingerprint", "current fingerprint"],
    supportedOutputs: "jurisdiction-neutral invalidation tags",
    units: "tag list",
    assumptions: "geometry/reinforcement change invalidates results",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `invalidation is not a code check; ${NOT_CODE}`,
  },
];
