import type { D1dCanonicalCapabilityRow, D1dCapabilityCell } from "@rtb/types";
import { D1E_GLOBAL_RELEASE_CLASSIFICATION } from "@rtb/types";

const RELEASE = D1E_GLOBAL_RELEASE_CLASSIFICATION;

function cell(patch: Partial<D1dCapabilityCell> & Pick<D1dCapabilityCell, "limitation">): D1dCapabilityCell {
  return {
    implemented: false,
    frameworkOnly: false,
    numericallyValidated: false,
    engineerValidated: false,
    codeProfileImplemented: false,
    conformanceValidated: false,
    certified: false,
    releaseState: RELEASE,
    ...patch,
  };
}

const kernel = (limitation: string) =>
  cell({ implemented: true, numericallyValidated: true, limitation });
const framework = (limitation: string) => cell({ frameworkOnly: true, limitation });
const none = (limitation: string) => cell({ limitation });
const domain = (limitation: string) => cell({ implemented: true, limitation });

export const D1E_CANONICAL_CAPABILITY_MATRIX: readonly D1dCanonicalCapabilityRow[] = [
  {
    capability: "concrete domain model",
    GLOBAL: domain("D1E-0 objects; not a design engine"),
    AU: domain("reuses global concrete domain"),
    EU: domain("reuses global concrete domain"),
    US: domain("reuses global concrete domain"),
  },
  {
    capability: "material model",
    GLOBAL: domain("governed-property contract; no default constitutive law"),
    AU: framework("AU constitutive law unpopulated"),
    EU: framework("EN 1992 constitutive law unpopulated"),
    US: framework("ACI constitutive law unpopulated"),
  },
  {
    capability: "reinforcement model",
    GLOBAL: domain("explicit area/Es contract; no inferred bar tables"),
    AU: framework("AU bar constitutive law unpopulated"),
    EU: framework("EN 1992 reinforcement law unpopulated"),
    US: framework("ACI reinforcement law unpopulated"),
  },
  {
    capability: "section geometry",
    GLOBAL: kernel("D1E-1 outlines including voids"),
    AU: kernel("reuses D1E-1"),
    EU: kernel("reuses D1E-1"),
    US: kernel("reuses D1E-1"),
  },
  {
    capability: "section properties",
    GLOBAL: kernel("gross/principal geometric properties"),
    AU: kernel("reuses D1E-1"),
    EU: kernel("reuses D1E-1"),
    US: kernel("reuses D1E-1"),
  },
  {
    capability: "reinforcement geometry",
    GLOBAL: kernel("bar coordinates, containment, geometric clearances"),
    AU: kernel("reuses D1E-1; clearance ≠ AS 3600 cover"),
    EU: kernel("reuses D1E-1; clearance ≠ EN 1992 cover"),
    US: kernel("reuses D1E-1; clearance ≠ ACI cover"),
  },
  {
    capability: "strain kinematics",
    GLOBAL: kernel("plane-sections kinematics and bar strain"),
    AU: kernel("reuses D1E-1"),
    EU: kernel("reuses D1E-1"),
    US: kernel("reuses D1E-1"),
  },
  {
    capability: "section integration",
    GLOBAL: kernel("fiber + bar integration; not structural FEA"),
    AU: kernel("reuses D1E-1"),
    EU: kernel("reuses D1E-1"),
    US: kernel("reuses D1E-1"),
  },
  {
    capability: "equilibrium solver",
    GLOBAL: kernel("elastic equilibrium; nonconvergence fails closed"),
    AU: kernel("reuses D1E-1; no parallel AU solver"),
    EU: kernel("reuses D1E-1; no parallel EU solver"),
    US: kernel("reuses D1E-1; no parallel US solver"),
  },
  {
    capability: "elastic reference mechanics",
    GLOBAL: kernel("uncracked elastic reference ≠ code capacity"),
    AU: kernel("elastic reference ≠ AS 3600 flexure"),
    EU: kernel("elastic reference ≠ EN 1992 flexure"),
    US: kernel("elastic reference ≠ ACI flexure"),
  },
  {
    capability: "AU standard profile",
    GLOBAL: none("AU profile is adapter-owned"),
    AU: framework("AS 3600 family bound; edition UNKNOWN_PENDING_CONFIRMATION"),
    EU: none("EU must not consume AU profile"),
    US: none("US must not consume AU profile"),
  },
  {
    capability: "EU standard profile",
    GLOBAL: none("EU profile is adapter-owned"),
    AU: none("AU must not consume EN 1992 semantics"),
    EU: framework("EN 1992 family/generation/part/annex/NDP bound; datasets unpopulated"),
    US: none("US must not consume EN 1992 semantics"),
  },
  {
    capability: "US standard profile",
    GLOBAL: none("US profile is adapter-owned"),
    AU: none("AU must not consume ACI semantics"),
    EU: none("EU must not consume ACI semantics"),
    US: framework("ACI family + building-code adoption + amendments + direct contract"),
  },
  {
    capability: "AU flexure",
    GLOBAL: none("no global code flexure"),
    AU: framework("pipeline + D1E-1 elastic reference; AS 3600 equations absent"),
    EU: none("EU flexure is separate"),
    US: none("US flexure is separate"),
  },
  {
    capability: "EU flexure",
    GLOBAL: none("no global code flexure"),
    AU: none("AU flexure is separate"),
    EU: framework("pipeline + D1E-1 elastic reference; EN 1992 equations absent"),
    US: none("US flexure is separate"),
  },
  {
    capability: "US flexure",
    GLOBAL: none("no global code flexure"),
    AU: none("AU flexure is separate"),
    EU: none("EU flexure is separate"),
    US: framework("pipeline + D1E-1 elastic reference; ACI equations absent"),
  },
  {
    capability: "axial-flexure",
    GLOBAL: none("N-M not implemented"),
    AU: framework("profile ready; no numerical AS 3600 N-M"),
    EU: framework("C3 bounded uniaxial N-M numerical reference; not column design; not CONFORMANCE_VALIDATED"),
    US: framework("profile ready; no numerical ACI N-M"),
  },
  {
    capability: "biaxial interaction",
    GLOBAL: none("P-M-M not implemented globally"),
    AU: none("no AU biaxial code method"),
    EU: framework("C4 bounded rectangular N-Mx-My numerical reference; not column design; not CONFORMANCE_VALIDATED"),
    US: none("no US biaxial code method"),
  },
  {
    capability: "shear",
    GLOBAL: none("code shear absent"),
    AU: none("no AS 3600 shear"),
    EU: framework("C5 evidence audit; profile ready; no numerical EN 1992 shear"),
    US: framework("profile ready; no numerical ACI shear"),
  },
  {
    capability: "punching",
    GLOBAL: none("punching absent"),
    AU: none("no AU punching"),
    EU: framework("C5 evidence audit; profile ready; no numerical punching"),
    US: framework("profile ready; no numerical punching"),
  },
  {
    capability: "torsion",
    GLOBAL: none("torsion absent"),
    AU: none("no AU torsion"),
    EU: none("C5 evidence audit; no EU torsion numerical method; D1C torsion demand unavailable"),
    US: none("no US torsion"),
  },
  {
    capability: "second-order effects",
    GLOBAL: none("RC second-order absent; steel stability not reused"),
    AU: none("no AU RC slenderness method"),
    EU: framework("profile ready; no numerical second-order"),
    US: framework("profile ready; no numerical second-order"),
  },
  {
    capability: "crack control",
    GLOBAL: none("code crack-width absent"),
    AU: none("no AS 3600 crack control"),
    EU: framework("profile ready; no numerical crack control"),
    US: framework("profile ready; no numerical crack control"),
  },
  {
    capability: "deflection",
    GLOBAL: none("cracked/long-term RC deflection absent"),
    AU: none("no AU RC deflection method"),
    EU: framework("profile ready; no numerical RC deflection"),
    US: framework("profile ready; no numerical RC deflection"),
  },
  {
    capability: "creep/shrinkage",
    GLOBAL: none("no default time-dependent model"),
    AU: none("no AU creep/shrinkage method"),
    EU: framework("interface ready; no default EU creep/shrinkage"),
    US: none("no ACI time-dependent method"),
  },
  {
    capability: "cover",
    GLOBAL: none("no default minimum cover"),
    AU: none("geometric clearance ≠ AS 3600 cover"),
    EU: framework("profile ready; no numerical cover check"),
    US: framework("profile ready; no numerical cover check"),
  },
  {
    capability: "durability",
    GLOBAL: none("exposure classes not in common kernel"),
    AU: none("no AU durability check"),
    EU: framework("profile ready; no numerical durability"),
    US: framework("profile ready; no numerical durability"),
  },
  {
    capability: "minimum reinforcement",
    GLOBAL: none("no global min-reo"),
    AU: none("no AS 3600 min reinforcement"),
    EU: none("no EN 1992 min reinforcement"),
    US: none("no ACI min reinforcement"),
  },
  {
    capability: "maximum reinforcement",
    GLOBAL: none("no global max-reo"),
    AU: none("no AS 3600 max reinforcement"),
    EU: none("no EN 1992 max reinforcement"),
    US: none("no ACI max reinforcement"),
  },
  {
    capability: "development",
    GLOBAL: none("development length absent"),
    AU: none("no AU development"),
    EU: none("no EU development"),
    US: none("no US development"),
  },
  {
    capability: "anchorage",
    GLOBAL: none("anchorage absent"),
    AU: none("no AU anchorage"),
    EU: none("no EU anchorage"),
    US: none("no US anchorage"),
  },
  {
    capability: "laps",
    GLOBAL: none("no default lap length"),
    AU: none("no AU lap splice"),
    EU: none("no EU lap splice"),
    US: none("no US lap splice"),
  },
  {
    capability: "detailing",
    GLOBAL: none("no global numeric detailing limits"),
    AU: none("no AU detailing"),
    EU: framework("profile ready; no numerical detailing"),
    US: framework("profile ready; no numerical detailing"),
  },
  {
    capability: "prestress",
    GLOBAL: none("prestressed design not validated"),
    AU: none("no AU prestress"),
    EU: none("extensible later; not implemented"),
    US: none("no US prestress"),
  },
  {
    capability: "connections",
    GLOBAL: none("concrete connections not validated"),
    AU: none("D1F later"),
    EU: none("D1F later"),
    US: none("D1F later"),
  },
  {
    capability: "seismic",
    GLOBAL: none("seismic concrete design not validated"),
    AU: none("dependency architecture only"),
    EU: none("not v1 ductile detailing"),
    US: none("dependency architecture only"),
  },
  {
    capability: "fire",
    GLOBAL: none("fire design not validated"),
    AU: none("no AU fire"),
    EU: none("EN 1992-1-2 part modelled; not implemented"),
    US: none("no ACI fire"),
  },
  {
    capability: "general FEA",
    GLOBAL: none("section integration is not structural FEA"),
    AU: none("not claimed"),
    EU: none("not claimed"),
    US: none("not claimed"),
  },
];
