import type { UsBendingMethodRecord } from "@rtb/types";
import { AISC_UNKNOWN_EDITION_TOKEN } from "@rtb/types";

export const US_BENDING_IMPLEMENTATION_VERSION = "us-bending-1.0.0" as const;
export const US_BENDING_TOOL_REF = "EOS_US_STEEL_BENDING" as const;

const MECHANICS_YIELD = "established-mechanics-first-yield-moment-equals-fy-times-elastic-section-modulus";
const MECHANICS_LTB = "established-mechanics-uniform-moment-elastic-critical-ltb-sqrt-pi2-EIy-L2-times-GJ-plus-pi2-EIw-L2";
const EDITIONS = [AISC_UNKNOWN_EDITION_TOKEN] as const;

export const US_BENDING_ELASTIC_MAJOR_MECHANICS_RULE: UsBendingMethodRecord = {
  ruleId: "US-BENDING-ELASTIC-MAJOR-MECHANICS-V1",
  methodId: "US_BENDING_ELASTIC_MAJOR_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_YIELD,
  calculationPurpose: "elastic first-yield moment about the major axis as a mechanics reference, not AISC Mn",
  applicability: "steel members with explicit Fy and major-axis elastic section modulus",
  requiredInputs: ["material.yieldStrength", "section.sectionModulusYy"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_BENDING",
  units: "N.m",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-BENDING-BM-ELASTIC-MAJOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-bending-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ELASTIC_BENDING_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "MAJOR_AXIS",
  factorDependencies: [],
  localAmendmentDependencies: [],
  classificationDependency: false,
  unbracedLengthDependency: false,
  restraintDependency: false,
  momentGradientDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_BENDING_ELASTIC_MINOR_MECHANICS_RULE: UsBendingMethodRecord = {
  ruleId: "US-BENDING-ELASTIC-MINOR-MECHANICS-V1",
  methodId: "US_BENDING_ELASTIC_MINOR_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_YIELD,
  calculationPurpose: "elastic first-yield moment about the minor axis as a mechanics reference, not AISC Mn",
  applicability: "steel members with explicit Fy and minor-axis elastic section modulus",
  requiredInputs: ["material.yieldStrength", "section.sectionModulusZz"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_BENDING",
  units: "N.m",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-BENDING-BM-ELASTIC-MINOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-bending-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ELASTIC_BENDING_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "MINOR_AXIS",
  factorDependencies: [],
  localAmendmentDependencies: [],
  classificationDependency: false,
  unbracedLengthDependency: false,
  restraintDependency: false,
  momentGradientDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_BENDING_ELASTIC_LTB_MECHANICS_RULE: UsBendingMethodRecord = {
  ruleId: "US-BENDING-ELASTIC-LTB-MECHANICS-V1",
  methodId: "US_BENDING_ELASTIC_LTB_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_LTB,
  calculationPurpose: "uniform-moment elastic critical LTB moment as a mechanics reference; no Cb or AISC reduction",
  applicability: "doubly-symmetric prismatic members with explicit E, G, Iminor, J, Iw, unbraced length, and LTB restraint",
  requiredInputs: ["material.elasticModulus", "material.shearModulus", "section.Izz", "section.torsionConstant", "section.warpingConstant", "stability.unbracedLengthM"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_LTB",
  units: "N.m",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-BENDING-BM-ELASTIC-LTB-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-bending-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ELASTIC_LTB_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "LTB",
  factorDependencies: [],
  localAmendmentDependencies: [],
  classificationDependency: false,
  unbracedLengthDependency: true,
  restraintDependency: true,
  momentGradientDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_SECTION_FLEXURAL_STRENGTH_CODE_PROFILE_RULE: UsBendingMethodRecord = {
  ruleId: "US-SECTION-FLEXURAL-STRENGTH-CODE-PROFILE-V1",
  methodId: "US_SECTION_FLEXURAL_STRENGTH_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-section-flexural-strength-validation-required",
  calculationPurpose: "AISC-profile section flexural strength",
  applicability: "not implemented; requires governed classification, edition, and factors",
  requiredInputs: ["material.yieldStrength", "section modulus", "classification", "edition"],
  outputType: "AISC_NOMINAL_FLEXURAL_STRENGTH",
  units: "N.m",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_FLEXURAL_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "SECTION",
  factorDependencies: [],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  classificationDependency: true,
  unbracedLengthDependency: false,
  restraintDependency: false,
  momentGradientDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_BENDING_MAJOR_LRFD_RULE: UsBendingMethodRecord = {
  ruleId: "US-BENDING-MAJOR-LRFD-V1",
  methodId: "US_BENDING_MAJOR_LRFD",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-lrfd-flexural-design-strength-validation-required",
  calculationPurpose: "AISC-profile LRFD major-axis flexural design strength φbMn",
  applicability: "not implemented; φb unpopulated; edition unknown",
  requiredInputs: ["Mn", "phi_b", "designMethod=LRFD"],
  outputType: "AISC_LRFD_DESIGN_STRENGTH",
  units: "N.m",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_LRFD_DESIGN_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "LRFD",
  axis: "MAJOR_AXIS",
  factorDependencies: ["phi_b"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  classificationDependency: true,
  unbracedLengthDependency: true,
  restraintDependency: true,
  momentGradientDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_BENDING_MAJOR_ASD_RULE: UsBendingMethodRecord = {
  ruleId: "US-BENDING-MAJOR-ASD-V1",
  methodId: "US_BENDING_MAJOR_ASD",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-asd-flexural-allowable-strength-validation-required",
  calculationPurpose: "AISC-profile ASD major-axis allowable flexural strength Mn/Ωb",
  applicability: "not implemented; Ωb unpopulated; edition unknown",
  requiredInputs: ["Mn", "Omega_b", "designMethod=ASD"],
  outputType: "AISC_ASD_ALLOWABLE_STRENGTH",
  units: "N.m",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_ASD_ALLOWABLE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "ASD",
  axis: "MAJOR_AXIS",
  factorDependencies: ["Omega_b"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  classificationDependency: true,
  unbracedLengthDependency: true,
  restraintDependency: true,
  momentGradientDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_BENDING_MINOR_LRFD_RULE: UsBendingMethodRecord = {
  ruleId: "US-BENDING-MINOR-LRFD-V1",
  methodId: "US_BENDING_MINOR_LRFD",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-lrfd-minor-flexural-design-strength-validation-required",
  calculationPurpose: "AISC-profile LRFD minor-axis flexural design strength",
  applicability: "not implemented; φb unpopulated; edition unknown",
  requiredInputs: ["Mn", "phi_b", "designMethod=LRFD"],
  outputType: "AISC_LRFD_DESIGN_STRENGTH",
  units: "N.m",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_LRFD_DESIGN_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "LRFD",
  axis: "MINOR_AXIS",
  factorDependencies: ["phi_b"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  classificationDependency: true,
  unbracedLengthDependency: false,
  restraintDependency: false,
  momentGradientDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_BENDING_MINOR_ASD_RULE: UsBendingMethodRecord = {
  ruleId: "US-BENDING-MINOR-ASD-V1",
  methodId: "US_BENDING_MINOR_ASD",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-asd-minor-flexural-allowable-strength-validation-required",
  calculationPurpose: "AISC-profile ASD minor-axis allowable flexural strength",
  applicability: "not implemented; Ωb unpopulated; edition unknown",
  requiredInputs: ["Mn", "Omega_b", "designMethod=ASD"],
  outputType: "AISC_ASD_ALLOWABLE_STRENGTH",
  units: "N.m",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_ASD_ALLOWABLE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "ASD",
  axis: "MINOR_AXIS",
  factorDependencies: ["Omega_b"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  classificationDependency: true,
  unbracedLengthDependency: false,
  restraintDependency: false,
  momentGradientDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_LTB_STRENGTH_CODE_PROFILE_RULE: UsBendingMethodRecord = {
  ruleId: "US-LTB-STRENGTH-CODE-PROFILE-V1",
  methodId: "US_LTB_STRENGTH_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-ltb-flexural-strength-validation-required",
  calculationPurpose: "AISC-profile LTB flexural strength",
  applicability: "not implemented; requires Lp/Lr, Cb, classification, edition, and factors",
  requiredInputs: ["unbracedLength", "Cb", "Lp", "Lr", "classification", "edition"],
  outputType: "AISC_NOMINAL_FLEXURAL_STRENGTH",
  units: "N.m",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_FLEXURAL_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "LTB",
  factorDependencies: ["Cb"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  classificationDependency: true,
  unbracedLengthDependency: true,
  restraintDependency: true,
  momentGradientDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "VALIDATION_REQUIRED",
};

export const US_BENDING_LOCAL_BUCKLING_CODE_PROFILE_RULE: UsBendingMethodRecord = {
  ruleId: "US-BENDING-LOCAL-BUCKLING-CODE-PROFILE-V1",
  methodId: "US_BENDING_LOCAL_BUCKLING_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-flexural-local-buckling-validation-required",
  calculationPurpose: "AISC-profile flange/web local buckling for bending",
  applicability: "not implemented; width-thickness limits unvalidated",
  requiredInputs: ["section geometry", "material.yieldStrength", "edition"],
  outputType: "AISC_LOCAL_BUCKLING",
  units: "1",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_FLEXURAL_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "LOCAL_BUCKLING",
  factorDependencies: [],
  localAmendmentDependencies: [],
  classificationDependency: true,
  unbracedLengthDependency: false,
  restraintDependency: false,
  momentGradientDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "VALIDATION_REQUIRED",
};

export const US_BENDING_ELEMENT_CLASSIFICATION_CODE_PROFILE_RULE: UsBendingMethodRecord = {
  ruleId: "US-BENDING-ELEMENT-CLASSIFICATION-CODE-PROFILE-V1",
  methodId: "US_BENDING_ELEMENT_CLASSIFICATION_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-bending-element-classification-validation-required",
  calculationPurpose: "AISC-profile compact/noncompact/slender classification for bending",
  applicability: "not implemented; compactness limits unvalidated",
  requiredInputs: ["section geometry", "material.yieldStrength", "axis", "limitState", "edition"],
  outputType: "AISC_ELEMENT_CLASSIFICATION",
  units: "1",
  implementationVersion: US_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_FLEXURAL_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "CLASSIFICATION",
  factorDependencies: [],
  localAmendmentDependencies: [],
  classificationDependency: true,
  unbracedLengthDependency: false,
  restraintDependency: false,
  momentGradientDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "VALIDATION_REQUIRED",
};

export const US_BENDING_METHOD_REGISTRY: readonly UsBendingMethodRecord[] = [
  US_BENDING_ELASTIC_MAJOR_MECHANICS_RULE,
  US_BENDING_ELASTIC_MINOR_MECHANICS_RULE,
  US_BENDING_ELASTIC_LTB_MECHANICS_RULE,
  US_SECTION_FLEXURAL_STRENGTH_CODE_PROFILE_RULE,
  US_BENDING_MAJOR_LRFD_RULE,
  US_BENDING_MAJOR_ASD_RULE,
  US_BENDING_MINOR_LRFD_RULE,
  US_BENDING_MINOR_ASD_RULE,
  US_LTB_STRENGTH_CODE_PROFILE_RULE,
  US_BENDING_LOCAL_BUCKLING_CODE_PROFILE_RULE,
  US_BENDING_ELEMENT_CLASSIFICATION_CODE_PROFILE_RULE,
];

export const IMPLEMENTED_US_BENDING_METHODS = [
  US_BENDING_ELASTIC_MAJOR_MECHANICS_RULE.methodId,
  US_BENDING_ELASTIC_MINOR_MECHANICS_RULE.methodId,
  US_BENDING_ELASTIC_LTB_MECHANICS_RULE.methodId,
] as const;

export const FRAMEWORK_ONLY_US_BENDING_METHODS = [
  US_SECTION_FLEXURAL_STRENGTH_CODE_PROFILE_RULE.methodId,
  US_BENDING_MAJOR_LRFD_RULE.methodId,
  US_BENDING_MAJOR_ASD_RULE.methodId,
  US_BENDING_MINOR_LRFD_RULE.methodId,
  US_BENDING_MINOR_ASD_RULE.methodId,
  US_LTB_STRENGTH_CODE_PROFILE_RULE.methodId,
  US_BENDING_LOCAL_BUCKLING_CODE_PROFILE_RULE.methodId,
  US_BENDING_ELEMENT_CLASSIFICATION_CODE_PROFILE_RULE.methodId,
] as const;
