/**
 * Phase 10D certification gates A–AO.
 */
export const PHASE_10D_ASSET_INTELLIGENCE_RELIABILITY_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 10A regression"],
  ["C", "Phase 10B regression"],
  ["D", "Phase 10B.1 hosted persistence regression"],
  ["E", "Phase 10C regression"],
  ["F", "PI v1 integrity"],
  ["G", "II v1 integrity"],
  ["H", "Ownership lock"],
  ["I", "Health semantic separation"],
  ["J", "Composition versioning"],
  ["K", "Asset Health Profile"],
  ["L", "Reliability model"],
  ["M", "Reliability Engine"],
  ["N", "Reliability metric governance"],
  ["O", "Evidence Confidence Engine"],
  ["P", "Evidence sufficiency"],
  ["Q", "Source Registry"],
  ["R", "Hosted migration"],
  ["S", "Hosted reliability persistence"],
  ["T", "Governed review"],
  ["U", "Health Composer integration"],
  ["V", "Criticality contextual separation"],
  ["W", "Snapshot integration"],
  ["X", "Timeline"],
  ["Y", "Event/outbox integrity"],
  ["Z", "II public-contract boundary"],
  ["AA", "HTTP contracts"],
  ["AB", "Hosted RLS"],
  ["AC", "Role matrix"],
  ["AD", "Tenant isolation"],
  ["AE", "Workspace isolation"],
  ["AF", "IDOR"],
  ["AG", "Idempotency"],
  ["AH", "Concurrency"],
  ["AI", "Health/observability"],
  ["AJ", "Performance"],
  ["AK", "No production memory adapter"],
  ["AL", "No predictive/RUL claims"],
  ["AM", "Secret exposure"],
  ["AN", "Artifact identity"],
  ["AO", "Phase 10E readiness"],
] as const;

export type Phase10dGateId = (typeof PHASE_10D_ASSET_INTELLIGENCE_RELIABILITY_GATES)[number][0];
