import type { UsCompressionMethodRecord } from "@rtb/types";
import { AISC_UNKNOWN_EDITION_TOKEN } from "@rtb/types";

export const US_COMPRESSION_IMPLEMENTATION_VERSION = "us-compression-1.0.0" as const;
export const US_COMPRESSION_TOOL_REF = "EOS_US_STEEL_COMPRESSION" as const;

const MECHANICS_SQUASH = "established-mechanics-nominal-squash-load-equals-yield-stress-times-gross-area";
const MECHANICS_EULER = "established-mechanics-euler-elastic-buckling-pcr-pi2-ei-over-le2";
const EDITIONS = [AISC_UNKNOWN_EDITION_TOKEN] as const;

export const US_COMPRESSION_SQUASH_YIELD_MECHANICS_RULE: UsCompressionMethodRecord = {
  ruleId: "US-COMPRESSION-SQUASH-YIELD-MECHANICS-V1",
  methodId: "US_COMPRESSION_SQUASH_YIELD_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_SQUASH,
  calculationPurpose: "nominal squash load as a mechanics reference, not AISC member compressive strength",
  applicability: "steel compression members with explicit governed Fy and gross area",
  requiredInputs: ["material.yieldStrength", "section.area"],
  outputType: "MECHANICS_REFERENCE_SQUASH",
  units: "N",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-COMPRESSION-BM-SQUASH-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-compression-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  stabilityAnalysisMethodDependency: "NONE",
  axis: "SQUASH",
  factorDependencies: [],
  localAmendmentDependencies: [],
  elementClassificationDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_COMPRESSION_EULER_MAJOR_MECHANICS_RULE: UsCompressionMethodRecord = {
  ruleId: "US-COMPRESSION-EULER-MAJOR-MECHANICS-V1",
  methodId: "US_COMPRESSION_EULER_MAJOR_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_EULER,
  calculationPurpose: "Euler elastic buckling load about the major axis as a mechanics reference, not AISC Pn",
  applicability: "prismatic members with explicit E, Iyy, and governed major-axis effective length",
  requiredInputs: ["material.elasticModulus", "section.Iyy", "stability.effectiveLengthMajorM"],
  outputType: "ELASTIC_BUCKLING_REFERENCE_EULER",
  units: "N",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-COMPRESSION-BM-EULER-MAJOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-compression-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ELASTIC_BUCKLING_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  stabilityAnalysisMethodDependency: "EFFECTIVE_LENGTH_BASED",
  axis: "MAJOR_AXIS",
  factorDependencies: [],
  localAmendmentDependencies: [],
  elementClassificationDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_COMPRESSION_EULER_MINOR_MECHANICS_RULE: UsCompressionMethodRecord = {
  ruleId: "US-COMPRESSION-EULER-MINOR-MECHANICS-V1",
  methodId: "US_COMPRESSION_EULER_MINOR_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_EULER,
  calculationPurpose: "Euler elastic buckling load about the minor axis as a mechanics reference, not AISC Pn",
  applicability: "prismatic members with explicit E, Izz, and governed minor-axis effective length",
  requiredInputs: ["material.elasticModulus", "section.Izz", "stability.effectiveLengthMinorM"],
  outputType: "ELASTIC_BUCKLING_REFERENCE_EULER",
  units: "N",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-COMPRESSION-BM-EULER-MINOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-compression-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ELASTIC_BUCKLING_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  stabilityAnalysisMethodDependency: "EFFECTIVE_LENGTH_BASED",
  axis: "MINOR_AXIS",
  factorDependencies: [],
  localAmendmentDependencies: [],
  elementClassificationDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_COMPRESSION_NOMINAL_STRENGTH_CODE_PROFILE_RULE: UsCompressionMethodRecord = {
  ruleId: "US-COMPRESSION-NOMINAL-STRENGTH-CODE-PROFILE-V1",
  methodId: "US_COMPRESSION_NOMINAL_STRENGTH_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-nominal-compressive-strength-validation-required",
  calculationPurpose: "AISC-profile nominal compressive strength Pn",
  applicability: "not implemented; requires governed strength curve, slenderness, local-element treatment, edition, and stability method",
  requiredInputs: ["material.yieldStrength", "section.area", "classification", "strength-curve", "stabilityAnalysisMethod"],
  outputType: "AISC_NOMINAL_COMPRESSIVE_STRENGTH",
  units: "N",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_COMPRESSIVE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  stabilityAnalysisMethodDependency: "UNKNOWN",
  axis: "STRENGTH_CURVE",
  factorDependencies: [],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  elementClassificationDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_COMPRESSION_LRFD_DESIGN_STRENGTH_RULE: UsCompressionMethodRecord = {
  ruleId: "US-COMPRESSION-LRFD-DESIGN-STRENGTH-V1",
  methodId: "US_COMPRESSION_LRFD_DESIGN_STRENGTH",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-lrfd-compressive-design-strength-validation-required",
  calculationPurpose: "AISC-profile LRFD compressive design strength φcPn",
  applicability: "not implemented; φc unpopulated; edition unknown",
  requiredInputs: ["Pn", "phi_c", "designMethod=LRFD"],
  outputType: "AISC_LRFD_DESIGN_STRENGTH",
  units: "N",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_LRFD_DESIGN_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "LRFD",
  stabilityAnalysisMethodDependency: "UNKNOWN",
  axis: "STRENGTH_CURVE",
  factorDependencies: ["phi_c"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  elementClassificationDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_COMPRESSION_ASD_ALLOWABLE_STRENGTH_RULE: UsCompressionMethodRecord = {
  ruleId: "US-COMPRESSION-ASD-ALLOWABLE-STRENGTH-V1",
  methodId: "US_COMPRESSION_ASD_ALLOWABLE_STRENGTH",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-asd-compressive-allowable-strength-validation-required",
  calculationPurpose: "AISC-profile ASD allowable compressive strength Pn/Ωc",
  applicability: "not implemented; Ωc unpopulated; edition unknown",
  requiredInputs: ["Pn", "Omega_c", "designMethod=ASD"],
  outputType: "AISC_ASD_ALLOWABLE_STRENGTH",
  units: "N",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_ASD_ALLOWABLE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "ASD",
  stabilityAnalysisMethodDependency: "UNKNOWN",
  axis: "STRENGTH_CURVE",
  factorDependencies: ["Omega_c"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  elementClassificationDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_COMPRESSION_STRENGTH_CURVE_RULE: UsCompressionMethodRecord = {
  ruleId: "US-COMPRESSION-STRENGTH-CURVE-V1",
  methodId: "US_COMPRESSION_STRENGTH_CURVE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-compressive-strength-curve-validation-required",
  calculationPurpose: "AISC-profile compressive-strength curve / inelastic buckling reduction",
  applicability: "not implemented; curve parameters unvalidated",
  requiredInputs: ["Fy", "E", "slenderness", "edition"],
  outputType: "AISC_COMPRESSION_STRENGTH_CURVE",
  units: "1",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_COMPRESSIVE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  stabilityAnalysisMethodDependency: "UNKNOWN",
  axis: "STRENGTH_CURVE",
  factorDependencies: [],
  localAmendmentDependencies: [],
  elementClassificationDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "VALIDATION_REQUIRED",
};

export const US_ELEMENT_CLASSIFICATION_CODE_PROFILE_RULE: UsCompressionMethodRecord = {
  ruleId: "US-ELEMENT-CLASSIFICATION-CODE-PROFILE-V1",
  methodId: "US_ELEMENT_CLASSIFICATION_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-element-classification-validation-required",
  calculationPurpose: "AISC-profile local/slender-element classification for compression",
  applicability: "not implemented; width-thickness limits unvalidated",
  requiredInputs: ["section geometry", "material.yieldStrength", "edition"],
  outputType: "AISC_ELEMENT_CLASSIFICATION",
  units: "1",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_COMPRESSIVE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  stabilityAnalysisMethodDependency: "NONE",
  axis: "CLASSIFICATION",
  factorDependencies: [],
  localAmendmentDependencies: [],
  elementClassificationDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "VALIDATION_REQUIRED",
};

export const US_CODE_SLENDERNESS_CODE_PROFILE_RULE: UsCompressionMethodRecord = {
  ruleId: "US-CODE-SLENDERNESS-CODE-PROFILE-V1",
  methodId: "US_CODE_SLENDERNESS_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-code-slenderness-limit-validation-required",
  calculationPurpose: "AISC-profile member slenderness limit context",
  applicability: "not implemented; code limits unvalidated",
  requiredInputs: ["KL/r", "edition"],
  outputType: "AISC_CODE_SLENDERNESS",
  units: "1",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_COMPRESSIVE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  stabilityAnalysisMethodDependency: "EFFECTIVE_LENGTH_BASED",
  axis: "SLENDERNESS",
  factorDependencies: [],
  localAmendmentDependencies: [],
  elementClassificationDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "VALIDATION_REQUIRED",
};

export const US_TORSIONAL_BUCKLING_CODE_PROFILE_RULE: UsCompressionMethodRecord = {
  ruleId: "US-TORSIONAL-BUCKLING-CODE-PROFILE-V1",
  methodId: "US_TORSIONAL_BUCKLING_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-torsional-buckling-not-implemented",
  calculationPurpose: "represent torsional buckling as an extensible mode without a numerical check",
  applicability: "architecture only; numerical code method not implemented",
  requiredInputs: ["section.torsionConstant", "section.warpingConstant", "stability"],
  outputType: "AISC_TORSIONAL_BUCKLING",
  units: "N",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_COMPRESSIVE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  stabilityAnalysisMethodDependency: "UNKNOWN",
  axis: "TORSIONAL",
  factorDependencies: [],
  localAmendmentDependencies: [],
  elementClassificationDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "NOT_IMPLEMENTED",
};

export const US_FLEXURAL_TORSIONAL_BUCKLING_CODE_PROFILE_RULE: UsCompressionMethodRecord = {
  ruleId: "US-FLEXURAL-TORSIONAL-BUCKLING-CODE-PROFILE-V1",
  methodId: "US_FLEXURAL_TORSIONAL_BUCKLING_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-flexural-torsional-buckling-not-implemented",
  calculationPurpose: "represent flexural-torsional buckling as an extensible mode without a numerical check",
  applicability: "architecture only; numerical code method not implemented",
  requiredInputs: ["section.Iyy", "section.Izz", "section.torsionConstant", "section.warpingConstant"],
  outputType: "AISC_FLEXURAL_TORSIONAL_BUCKLING",
  units: "N",
  implementationVersion: US_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_COMPRESSIVE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  stabilityAnalysisMethodDependency: "UNKNOWN",
  axis: "FLEXURAL_TORSIONAL",
  factorDependencies: [],
  localAmendmentDependencies: [],
  elementClassificationDependency: false,
  compatibleEditions: EDITIONS,
  scopeState: "NOT_IMPLEMENTED",
};

export const US_COMPRESSION_METHOD_REGISTRY: readonly UsCompressionMethodRecord[] = [
  US_COMPRESSION_SQUASH_YIELD_MECHANICS_RULE,
  US_COMPRESSION_EULER_MAJOR_MECHANICS_RULE,
  US_COMPRESSION_EULER_MINOR_MECHANICS_RULE,
  US_COMPRESSION_NOMINAL_STRENGTH_CODE_PROFILE_RULE,
  US_COMPRESSION_LRFD_DESIGN_STRENGTH_RULE,
  US_COMPRESSION_ASD_ALLOWABLE_STRENGTH_RULE,
  US_COMPRESSION_STRENGTH_CURVE_RULE,
  US_ELEMENT_CLASSIFICATION_CODE_PROFILE_RULE,
  US_CODE_SLENDERNESS_CODE_PROFILE_RULE,
  US_TORSIONAL_BUCKLING_CODE_PROFILE_RULE,
  US_FLEXURAL_TORSIONAL_BUCKLING_CODE_PROFILE_RULE,
];

export const IMPLEMENTED_US_COMPRESSION_METHODS = [
  US_COMPRESSION_SQUASH_YIELD_MECHANICS_RULE.methodId,
  US_COMPRESSION_EULER_MAJOR_MECHANICS_RULE.methodId,
  US_COMPRESSION_EULER_MINOR_MECHANICS_RULE.methodId,
] as const;

export const FRAMEWORK_ONLY_US_COMPRESSION_METHODS = [
  US_COMPRESSION_NOMINAL_STRENGTH_CODE_PROFILE_RULE.methodId,
  US_COMPRESSION_LRFD_DESIGN_STRENGTH_RULE.methodId,
  US_COMPRESSION_ASD_ALLOWABLE_STRENGTH_RULE.methodId,
  US_COMPRESSION_STRENGTH_CURVE_RULE.methodId,
  US_ELEMENT_CLASSIFICATION_CODE_PROFILE_RULE.methodId,
  US_CODE_SLENDERNESS_CODE_PROFILE_RULE.methodId,
  US_TORSIONAL_BUCKLING_CODE_PROFILE_RULE.methodId,
  US_FLEXURAL_TORSIONAL_BUCKLING_CODE_PROFILE_RULE.methodId,
] as const;
