/**
 * Phase 10G certification gates A–BC (Asset Lifecycle Intelligence).
 */
export const PHASE_10G_ASSET_INTELLIGENCE_LIFECYCLE_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 10A regression"],
  ["C", "Phase 10B regression"],
  ["D", "Phase 10B.1 persistence regression"],
  ["E", "Phase 10C regression"],
  ["F", "Phase 10D regression"],
  ["G", "Phase 10E regression"],
  ["H", "Authoritative Phase 10F recertification identity"],
  ["I", "PI v1 integrity"],
  ["J", "II v1 integrity"],
  ["K", "Ownership lock"],
  ["L", "Lifecycle terminology"],
  ["M", "Canonical lifecycle ownership"],
  ["N", "Lifecycle Intelligence state"],
  ["O", "LifecycleContextEngine"],
  ["P", "Cross-slice policy"],
  ["Q", "Published-slice restriction"],
  ["R", "Evidence Confidence"],
  ["S", "Trend Confidence"],
  ["T", "Transition candidate governance"],
  ["U", "Age/service-life governance"],
  ["V", "Lifecycle/Condition boundary"],
  ["W", "Lifecycle/Failure boundary"],
  ["X", "Lifecycle/Degradation boundary"],
  ["Y", "Maintenance boundary"],
  ["Z", "Digital Twin boundary"],
  ["AA", "Lifecycle taxonomy"],
  ["AB", "Governed review"],
  ["AC", "Hosted migration"],
  ["AD", "Migration lineage 55/55b/56"],
  ["AE", "Hosted lifecycle persistence"],
  ["AF", "Snapshot"],
  ["AG", "Timeline"],
  ["AH", "Event/outbox integrity"],
  ["AI", "Health composition boundary"],
  ["AJ", "Lifecycle not health factor"],
  ["AK", "Priority Engine reservation"],
  ["AL", "Fusion reservation"],
  ["AM", "II contract boundary"],
  ["AN", "PI boundary"],
  ["AO", "HTTP contracts"],
  ["AP", "Real JWT role matrix"],
  ["AQ", "Tenant isolation"],
  ["AR", "Workspace isolation"],
  ["AS", "IDOR"],
  ["AT", "Idempotency"],
  ["AU", "Concurrency"],
  ["AV", "AI governance"],
  ["AW", "Health/observability"],
  ["AX", "Performance"],
  ["AY", "No memory production"],
  ["AZ", "No predictive/PoF/RUL claims"],
  ["BA", "Secret exposure"],
  ["BB", "Artifact identity"],
  ["BC", "Phase 10H readiness"],
] as const;

export type Phase10gGateId = (typeof PHASE_10G_ASSET_INTELLIGENCE_LIFECYCLE_GATES)[number][0];
