export const PHASE_8D_MEETING_INTELLIGENCE_GATES = [
  ["A", "Repository and build identity"],
  ["B", "Phase 7B, 8A, 8B and 8C regression"],
  ["C", "Hosted schema and migration identity"],
  ["D", "Real-JWT RLS"],
  ["E", "Feature registration"],
  ["F", "Shared Engineering Services consumption"],
  ["G", "Provider-neutral ingestion"],
  ["H", "Manual provider"],
  ["I", "Uploaded-source provider paths where implemented"],
  ["J", "Meeting lifecycle"],
  ["K", "Consent and privacy"],
  ["L", "Realtime transcript ordering and revisions"],
  ["M", "Reconnect and replay"],
  ["N", "Durable enqueue and outbox"],
  ["O", "Multi-worker processing and recovery"],
  ["P", "Document Intelligence grounding"],
  ["Q", "Minutes generation and versioning"],
  ["R", "Proposal extraction"],
  ["S", "Human review"],
  ["T", "Engineering Core conversion"],
  ["U", "Findings Intelligence handoff"],
  ["V", "Entitlement and workspace isolation"],
  ["W", "HTTP and webhook contracts"],
  ["X", "Browser E2E"],
  ["Y", "Accessibility"],
  ["Z", "Responsive layouts"],
  ["AA", "Performance baseline"],
  ["AB", "Secret exposure"],
  ["AC", "Artifact identity and release eligibility"],
] as const;

export type Phase8dGateId = (typeof PHASE_8D_MEETING_INTELLIGENCE_GATES)[number][0];
