import type { OperatingSystemManifest } from "@rtb/types";
import { BUSINESS_CAPABILITY_DEFINITIONS } from "./capabilities";
import { BUSINESS_OS_VERSION, BUSINESS_OS_ID } from "./version";

const OS_ID = BUSINESS_OS_ID;

export function buildBusinessOsManifest(): OperatingSystemManifest {
  return {
    id: OS_ID,
    name: "Business Operating System",
    description:
      "AI-assisted business operations — Business OS Core v1.0 GA. Xero, Microsoft 365, and HubSpot remain Preview.",
    version: BUSINESS_OS_VERSION,
    author: "RTB",
    certificationOnly: false,
    catalogStatus: "available",
    permissions: [
      { resource: "business", action: "read" },
      { resource: "business", action: "execute" },
      { resource: "business", action: "admin" },
    ],
    modules: [],
    applications: [],
    routes: [
      { path: "/business", title: "Owner Command Centre", component: "OwnerCommandCentre" },
      { path: "/business/finance", title: "Financial Intelligence", component: "FinancialIntelligence" },
      { path: "/business/growth", title: "Growth Intelligence", component: "GrowthIntelligence" },
      { path: "/business/revenue", title: "Revenue Execution", component: "RevenueExecution" },
      { path: "/business/customers", title: "Customer Intelligence", component: "CustomerIntelligence" },
      { path: "/business/profit", title: "Profit Intelligence", component: "ProfitIntelligence" },
      { path: "/business/operations", title: "Work & Operations", component: "WorkOperations" },
      { path: "/business/decisions", title: "Decision Intelligence", component: "DecisionIntelligence" },
      { path: "/business/risk", title: "Business Risk", component: "BusinessRisk" },
      { path: "/business/context", title: "Business Context", component: "BusinessContext" },
      { path: "/business/ai-workforce", title: "AI Workforce", component: "AiWorkforce" },
      { path: "/business/integrations", title: "Integrations", component: "BusinessIntegrations" },
      { path: "/business/settings", title: "Business OS Settings", component: "BusinessOsSettings" },
    ],
    navigation: [
      {
        id: "bos-home",
        label: "Owner Command",
        path: "/business",
        icon: "Briefcase",
        group: "business",
        order: 1,
      },
      {
        id: "bos-finance",
        label: "Finance",
        path: "/business/finance",
        icon: "LineChart",
        group: "business",
        order: 2,
      },
      {
        id: "bos-growth",
        label: "Growth",
        path: "/business/growth",
        icon: "Network",
        group: "business",
        order: 3,
      },
      {
        id: "bos-revenue",
        label: "Revenue",
        path: "/business/revenue",
        icon: "DollarSign",
        group: "business",
        order: 4,
      },
      {
        id: "bos-customers",
        label: "Customers",
        path: "/business/customers",
        icon: "Users",
        group: "business",
        order: 5,
      },
      {
        id: "bos-profit",
        label: "Profit",
        path: "/business/profit",
        icon: "PieChart",
        group: "business",
        order: 6,
      },
      {
        id: "bos-operations",
        label: "Operations",
        path: "/business/operations",
        icon: "Wrench",
        group: "business",
        order: 7,
      },
      {
        id: "bos-decisions",
        label: "Decisions",
        path: "/business/decisions",
        icon: "Gavel",
        group: "business",
        order: 8,
      },
      {
        id: "bos-risk",
        label: "Risk",
        path: "/business/risk",
        icon: "ShieldAlert",
        group: "business",
        order: 9,
      },
      {
        id: "bos-context",
        label: "Business Context",
        path: "/business/context",
        icon: "GitBranch",
        group: "business",
        order: 10,
      },
      {
        id: "bos-ai-workforce",
        label: "AI Workforce",
        path: "/business/ai-workforce",
        icon: "Bot",
        group: "business",
        order: 11,
      },
      {
        id: "bos-integrations",
        label: "Integrations",
        path: "/business/integrations",
        icon: "Plug",
        group: "business",
        order: 12,
      },
      {
        id: "bos-settings",
        label: "Settings",
        path: "/business/settings",
        icon: "Settings",
        group: "business_admin",
        order: 90,
      },
    ],
    capabilities: BUSINESS_CAPABILITY_DEFINITIONS.map((c) => ({
      id: c.id,
      description: c.description,
    })),
    events: [
      { type: "business_os.foundation.status.requested", description: "Foundation status read" },
      { type: "business_os.foundation.access.denied", description: "Foundation access denied" },
      { type: "business_os.foundation.access.granted", description: "Foundation access granted" },
      { type: "business_os.kpi.updated", description: "KPI measurement or configuration updated" },
      { type: "business_os.signal.created", description: "Business signal created" },
      { type: "business_os.signal.resolved", description: "Business signal resolved" },
      { type: "business_os.recommendation.created", description: "Advisory recommendation created" },
      { type: "business_os.decision.created", description: "Owner decision recorded" },
      { type: "business_os.decision.updated", description: "Owner decision updated" },
      { type: "business_os.action.created", description: "Internal action recorded" },
      { type: "business_os.action.completed", description: "Internal action completed" },
      { type: "business_os.decision.evidence_updated", description: "Decision evidence bundle updated" },
      { type: "business_os.decision.option_created", description: "Decision option created" },
      { type: "business_os.decision.brief_prepared", description: "Decision brief prepared" },
      { type: "business_os.decision.selected", description: "Decision option selected (human still required to approve)" },
      { type: "business_os.decision.outcome_recorded", description: "Decision outcome recorded" },
      { type: "business_os.decision.outcome_reviewed", description: "Decision outcome reviewed" },
      { type: "business_os.decision.lesson_recorded", description: "Decision lesson recorded" },
      { type: "business_os.finance.snapshot_ingested", description: "Finance snapshot ingested" },
      { type: "business_os.finance.metrics_updated", description: "Finance metrics published to Owner Command" },
      { type: "business_os.finance.signal_detected", description: "Finance rule produced a signal" },
      { type: "business_os.growth.lead_created", description: "Growth lead ingested" },
      { type: "business_os.growth.lead_qualified", description: "Growth lead qualified" },
      { type: "business_os.growth.lead_converted", description: "Growth lead converted" },
      { type: "business_os.growth.opportunity_created", description: "Growth opportunity ingested" },
      { type: "business_os.growth.opportunity_updated", description: "Growth opportunity updated" },
      { type: "business_os.growth.opportunity_won", description: "Growth opportunity marked won" },
      { type: "business_os.growth.opportunity_lost", description: "Growth opportunity marked lost" },
      { type: "business_os.growth.metrics_updated", description: "Growth metrics published to Owner Command" },
      { type: "business_os.growth.signal_detected", description: "Growth rule produced a signal" },
      { type: "business_os.revenue.engagement_created", description: "Engagement plan created" },
      { type: "business_os.revenue.proposal_created", description: "Proposal draft created" },
      { type: "business_os.revenue.proposal_updated", description: "Proposal updated" },
      { type: "business_os.revenue.proposal_ready", description: "Proposal marked internally ready" },
      { type: "business_os.revenue.pricing_evaluated", description: "Pricing scenario evaluated" },
      { type: "business_os.revenue.pricing_exception", description: "Pricing guardrail exception detected" },
      { type: "business_os.revenue.bid_decision_requested", description: "Bid/no-bid human decision requested" },
      { type: "business_os.revenue.bid_decision_completed", description: "Bid/no-bid human decision recorded" },
      { type: "business_os.revenue.draft_prepared", description: "Internal communication draft prepared" },
      { type: "business_os.customer.created", description: "Customer created" },
      { type: "business_os.customer.updated", description: "Customer updated" },
      { type: "business_os.customer.converted", description: "Lead or opportunity linked to a customer" },
      { type: "business_os.customer.health_updated", description: "Customer health recomputed" },
      { type: "business_os.customer.risk_detected", description: "Customer risk indicator detected" },
      { type: "business_os.customer.financial_fact_ingested", description: "Customer financial fact ingested" },
      { type: "business_os.customer.signal_detected", description: "Customer rule produced a signal" },
      { type: "business_os.profit.fact_ingested", description: "Profit fact ingested" },
      { type: "business_os.profit.metrics_updated", description: "Profit metrics published to Owner Command" },
      { type: "business_os.profit.leakage_detected", description: "Profit leakage rule produced a signal" },
      { type: "business_os.profit.classification_updated", description: "Profit classification or settings updated" },
      { type: "business_os.operations.work_created", description: "Work item created" },
      { type: "business_os.operations.work_updated", description: "Work item updated" },
      { type: "business_os.operations.work_completed", description: "Work item completed" },
      { type: "business_os.operations.milestone_updated", description: "Milestone updated" },
      { type: "business_os.operations.cost_fact_ingested", description: "Operational cost fact ingested" },
      { type: "business_os.operations.capacity_updated", description: "Capacity fact updated" },
      { type: "business_os.operations.risk_detected", description: "Operational risk indicator detected" },
      { type: "business_os.operations.metrics_updated", description: "Operations metrics published to Owner Command" },
      { type: "business_os.risk.created", description: "Business risk created" },
      { type: "business_os.risk.assessed", description: "Business risk assessed" },
      { type: "business_os.risk.residual_updated", description: "Residual risk updated from evidenced controls" },
      { type: "business_os.risk.control_updated", description: "Risk control updated" },
      { type: "business_os.risk.treatment_updated", description: "Risk treatment updated" },
      { type: "business_os.risk.outside_tolerance", description: "Residual risk is outside configured tolerance" },
      { type: "business_os.risk.obligation_overdue", description: "Risk obligation is overdue" },
      { type: "business_os.risk.review_due", description: "Risk review is due or overdue" },
      { type: "business_os.context.node_projected", description: "Business context node projected into Kernel graph" },
      { type: "business_os.context.relationship_projected", description: "Business context relationship projected into Kernel graph" },
      { type: "business_os.context.projection_failed", description: "Business context projection failed" },
      { type: "business_os.context.rebuild_completed", description: "Business context projection rebuild completed" },
      { type: "business_os.context.unresolved_reference_detected", description: "Unresolved context graph reference detected" },
      { type: "business_os.ai_workforce.agent_installed", description: "Governed workforce agent installed" },
      { type: "business_os.ai_workforce.agent_enabled", description: "Governed workforce agent enabled" },
      { type: "business_os.ai_workforce.agent_suspended", description: "Governed workforce agent suspended" },
      { type: "business_os.ai_workforce.agent_revoked", description: "Governed workforce agent revoked" },
      { type: "business_os.ai_workforce.task_requested", description: "Workforce task requested" },
      { type: "business_os.ai_workforce.run_started", description: "Workforce run started" },
      { type: "business_os.ai_workforce.approval_requested", description: "Workforce execution approval requested" },
      { type: "business_os.ai_workforce.execution_started", description: "Workforce execution started after approval/policy" },
      { type: "business_os.ai_workforce.run_completed", description: "Workforce run completed" },
      { type: "business_os.ai_workforce.run_failed", description: "Workforce run failed" },
      { type: "business_os.ai_workforce.run_blocked", description: "Workforce run blocked" },
      { type: "business_os.ai_workforce.handoff_requested", description: "Bounded agent-to-agent handoff requested" },
      { type: "business_os.connectors.configured", description: "Optional connector configured (secret reference only)" },
      { type: "business_os.connectors.revoked", description: "Optional connector revoked and secret reference cleared" },
      { type: "business_os.connectors.sync_started", description: "Connector sync started" },
      { type: "business_os.connectors.sync_completed", description: "Connector sync completed or partial" },
      { type: "business_os.connectors.sync_failed", description: "Connector sync failed" },
      { type: "business_os.connectors.import_committed", description: "CSV/Excel import committed to staging" },
      { type: "business_os.connectors.mapping_updated", description: "Connector mapping version updated" },
    ],
    knowledge: [
      {
        namespace: "business",
        description: "Business OS projects canonical records into the Platform Kernel Knowledge Graph",
      },
    ],
    agents: [
      {
        id: "business-development-agent",
        name: "AI Business Development Agent",
        description:
          "Supervised A0–A2 preparation of research, engagement, drafts, and proposal intelligence. No external send.",
      },
    ],
  };
}

export const BUSINESS_OS_RUNTIME_MANIFEST = buildBusinessOsManifest();

/** Plugin-shaped manifest for existing plugin-sdk consumers. */
export const BUSINESS_OS_MANIFEST = {
  id: "business-os",
  name: BUSINESS_OS_RUNTIME_MANIFEST.name,
  version: BUSINESS_OS_RUNTIME_MANIFEST.version,
  description: BUSINESS_OS_RUNTIME_MANIFEST.description,
  author: BUSINESS_OS_RUNTIME_MANIFEST.author,
  operating_system: OS_ID,
  entry_point: "@rtb/business-os",
  permissions: BUSINESS_OS_RUNTIME_MANIFEST.permissions ?? [],
  routes: (BUSINESS_OS_RUNTIME_MANIFEST.routes ?? []).map((r) => ({
    path: r.path,
    component: r.component ?? "Unknown",
    title: r.title,
  })),
  navigation: (BUSINESS_OS_RUNTIME_MANIFEST.navigation ?? []).map((n) => ({
    id: n.id,
    label: n.label,
    icon: n.icon ?? "Circle",
    path: n.path,
    group: n.group ?? "business",
    order: n.order ?? 99,
  })),
};
