/**
 * Phase 11N certification gates A–BM (Project Controls V1.0 GA closure).
 * 65 gates: A–Z (26) + AA–AZ (26) + BA–BM (13).
 */
export const PHASE_11N_PROJECT_CONTROLS_GA_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 11A regression"],
  ["C", "Phase 11B regression"],
  ["D", "Phase 11C regression"],
  ["E", "Phase 11D regression"],
  ["F", "Phase 11E regression"],
  ["G", "Phase 11F regression"],
  ["H", "Phase 11G regression"],
  ["I", "Phase 11H regression"],
  ["J", "Phase 11I regression"],
  ["K", "Phase 11J regression"],
  ["L", "Phase 11K regression"],
  ["M", "Phase 11L regression"],
  ["N", "Phase 11M regression"],
  ["O", "PI v1 integrity"],
  ["P", "II v1 integrity"],
  ["Q", "AI v1 integrity"],
  ["R", "Shared Project Domain"],
  ["S", "Ownership locks"],
  ["T", "V1.0.0 version freeze"],
  ["U", "GA status declaration"],
  ["V", "Package version alignment"],
  ["W", "Single authoritative version source"],
  ["X", "Module manifest generator"],
  ["Y", "Module manifest snapshot"],
  ["Z", "Capability registry freeze"],
  ["AA", "Service registry freeze"],
  ["AB", "Event contract freeze"],
  ["AC", "Unavailable capability matrix"],
  ["AD", "Module registry drift"],
  ["AE", "Capability matrix document"],
  ["AF", "Public contracts document"],
  ["AG", "Commercial packaging document"],
  ["AH", "Operations runbook"],
  ["AI", "Incident response runbook"],
  ["AJ", "Recovery runbook"],
  ["AK", "Rollback runbook"],
  ["AL", "Performance baseline document"],
  ["AM", "Unavailable capabilities document"],
  ["AN", "Limitations document"],
  ["AO", "CPM unavailable"],
  ["AP", "Earned value unavailable"],
  ["AQ", "Financial posting unavailable"],
  ["AR", "Schedule execution unavailable"],
  ["AS", "Resource leveling unavailable"],
  ["AT", "Autonomous decision forbidden"],
  ["AU", "Migration lineage 61–73"],
  ["AV", "No batch_74 migration"],
  ["AW", "Hosted persistence"],
  ["AX", "Tenant isolation / RLS"],
  ["AY", "Real JWT matrix"],
  ["AZ", "Workspace isolation / IDOR"],
  ["BA", "HTTP contracts"],
  ["BB", "Health/observability"],
  ["BC", "No production memory repository"],
  ["BD", "Idempotency"],
  ["BE", "Concurrency"],
  ["BF", "Engineering OS module page"],
  ["BG", "GA readiness marker"],
  ["BH", "Unavailable labels in UI"],
  ["BI", "Browser E2E"],
  ["BJ", "Upgrade certification"],
  ["BK", "Backup/restore certification"],
  ["BL", "Unit and architecture tests"],
  ["BM", "Release tag integrity"],
] as const;

export type Phase11nGateId = (typeof PHASE_11N_PROJECT_CONTROLS_GA_GATES)[number][0];

export const PHASE_11N_RELEASE_TAG = "project-controls-v1.0.0" as const;
export const PHASE_11N_GATE_COUNT = PHASE_11N_PROJECT_CONTROLS_GA_GATES.length;
