import type {
  BusinessGrowthLeadIngestInput,
  BusinessGrowthMarketIngestInput,
  BusinessGrowthOpportunityIngestInput,
  BusinessGrowthTargetProfile,
} from "@rtb/types";

export const GROWTH_DEMO_PROFILE: BusinessGrowthTargetProfile = {
  industries: ["civil", "infrastructure", "inspection"],
  geographies: ["AU", "NZ"],
  companySizeBands: ["sme", "mid"],
  services: ["engineering", "inspection"],
  targetMarkets: ["public_infrastructure"],
};

export const GROWTH_DEMO_REVENUE_TARGET_MINOR = "200000000";

export const GROWTH_DEMO_LEADS: BusinessGrowthLeadIngestInput[] = [
  {
    organisationName: "Northbound Civils",
    website: "https://northbound.example",
    domain: "northbound.example",
    industry: "civil",
    geography: "AU",
    companySizeBand: "mid",
    services: "engineering",
    targetMarket: "public_infrastructure",
    evidenceOfNeed: true,
    relationshipKind: "known",
    sourceType: "public_directory",
    sourceRef: "bos-3-demo-lead-northbound",
    sourceTimestamp: "2026-07-01T09:00:00.000Z",
    qualificationStatus: "qualified",
    owner: "Owner",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false, personalContactPresent: false },
    enrichment: {
      industry: {
        value: "civil",
        source: "demo",
        timestamp: "2026-07-01T09:00:00.000Z",
        confidence: "high",
      },
      geography: {
        value: "AU",
        source: "demo",
        timestamp: "2026-07-01T09:00:00.000Z",
        confidence: "high",
      },
      website: {
        value: "https://northbound.example",
        source: "demo",
        timestamp: "2026-07-01T09:00:00.000Z",
        confidence: "medium",
      },
    },
  },
  {
    organisationName: "Harbour Inspection Co",
    website: "https://harbour.example",
    domain: "harbour.example",
    industry: "inspection",
    geography: "AU",
    companySizeBand: "sme",
    services: "inspection",
    targetMarket: "public_infrastructure",
    contactName: "Alex Rivera",
    contactRole: "Operations manager",
    businessEmail: "ops@harbour.example",
    evidenceOfNeed: true,
    relationshipKind: "referral",
    sourceType: "referral",
    sourceRef: "bos-3-demo-lead-harbour",
    sourceTimestamp: "2026-07-10T09:00:00.000Z",
    qualificationStatus: "researching",
    owner: "Owner",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false, personalContactPresent: true },
  },
  {
    organisationName: "Directory listing 441",
    sourceType: "public_directory",
    sourceRef: "bos-3-demo-lead-incomplete",
    sourceTimestamp: "2026-07-12T09:00:00.000Z",
    qualificationStatus: "unqualified",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false, personalContactPresent: false },
  },
];

export const GROWTH_DEMO_OPPORTUNITIES: BusinessGrowthOpportunityIngestInput[] = [
  {
    name: "Northbound bridge inspection",
    description: "Condition survey of two river crossings.",
    stage: "qualified",
    estimatedValueMinor: "80000000",
    currency: "AUD",
    scale: 2,
    probabilityBps: "4000",
    expectedCloseDate: "2026-09-30",
    expectedMarginBps: "2200",
    sourceType: "demo",
    sourceRef: "bos-3-demo-opp-northbound",
    owner: "Owner",
    nextAction: "Internal capability review",
    strategicFit: "high",
    relationshipStrength: "medium",
    deliveryCapability: "high",
    commercialRisk: "low",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false },
  },
  {
    name: "Harbour condition survey",
    description: "Wharf inspection package.",
    stage: "discovery",
    estimatedValueMinor: "25000000",
    currency: "AUD",
    scale: 2,
    expectedCloseDate: "2026-10-31",
    sourceType: "demo",
    sourceRef: "bos-3-demo-opp-harbour",
    owner: "Owner",
    nextAction: "Request public tender documents",
    strategicFit: "medium",
    relationshipStrength: "high",
    deliveryCapability: "medium",
    commercialRisk: "medium",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false, probability: "not_supplied" },
  },
  {
    name: "Zero-value workshop",
    stage: "identified",
    estimatedValueMinor: "0",
    currency: "AUD",
    scale: 2,
    sourceType: "demo",
    sourceRef: "bos-3-demo-opp-zero",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false },
  },
  {
    name: "Lost coastal tender",
    stage: "lost",
    estimatedValueMinor: "12000000",
    currency: "AUD",
    scale: 2,
    probabilityBps: "2000",
    sourceType: "demo",
    sourceRef: "bos-3-demo-opp-lost",
    strategicFit: "low",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false },
  },
  {
    name: "Won pavement patch",
    stage: "won",
    estimatedValueMinor: "4500000",
    currency: "AUD",
    scale: 2,
    probabilityBps: "10000",
    expectedCloseDate: "2026-06-15",
    sourceType: "demo",
    sourceRef: "bos-3-demo-opp-won",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false },
  },
  {
    name: "Metro interchange package",
    description: "Large public infrastructure package.",
    stage: "proposal_ready",
    estimatedValueMinor: "150000000",
    currency: "AUD",
    scale: 2,
    probabilityBps: "3500",
    expectedCloseDate: "2026-11-30",
    expectedMarginBps: "1800",
    sourceType: "demo",
    sourceRef: "bos-3-demo-opp-metro",
    strategicFit: "high",
    relationshipStrength: "medium",
    deliveryCapability: "medium",
    commercialRisk: "medium",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false, nextAction: "missing" },
  },
];

export const GROWTH_DEMO_MARKET: BusinessGrowthMarketIngestInput[] = [
  {
    segmentName: "Public infrastructure — Australia",
    industry: "infrastructure",
    geography: "AU",
    targetCustomerProfile: "State road and rail agencies",
    attractiveness: "high",
    status: "active",
    sourceType: "demo",
    sourceRef: "bos-3-demo-market-au-infra",
    sourceTimestamp: "2026-07-01T09:00:00.000Z",
    evidence: [
      {
        sourceType: "demo",
        sourceRef: "bos-3-demo-market-au-infra",
        title: "Target segment",
        excerpt: "Public infrastructure agencies in AU.",
      },
    ],
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false },
  },
  {
    segmentName: "Industrial inspection — New Zealand",
    industry: "inspection",
    geography: "NZ",
    targetCustomerProfile: "Mid-size industrial operators",
    attractiveness: "medium",
    status: "watch",
    sourceType: "demo",
    sourceRef: "bos-3-demo-market-nz-inspect",
    sourceTimestamp: "2026-07-01T09:00:00.000Z",
    isDemo: true,
    provenance: { fixture: "bos-3-growth-intelligence", live: false },
  },
];
