export const PHASE_10B1_ASSET_INTELLIGENCE_HOSTED_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 10A regression"],
  ["C", "Phase 10B architecture regression"],
  ["D", "PI v1 integrity"],
  ["E", "II v1 integrity"],
  ["F", "Repository abstraction"],
  ["G", "Production PostgreSQL adapter"],
  ["H", "Hosted migration identity"],
  ["I", "Hosted schema"],
  ["J", "RLS"],
  ["K", "Tenant isolation"],
  ["L", "Workspace isolation"],
  ["M", "IDOR"],
  ["N", "Condition persistence"],
  ["O", "Snapshot persistence"],
  ["P", "Source provenance"],
  ["Q", "Timeline persistence"],
  ["R", "II public-contract consumption"],
  ["S", "Transactional condition flow"],
  ["T", "Idempotency"],
  ["U", "Concurrency"],
  ["V", "Restart durability"],
  ["W", "Multi-context persistence"],
  ["X", "Event/outbox integrity"],
  ["Y", "HTTP contracts"],
  ["Z", "Health"],
  ["AA", "Observability"],
  ["AB", "Production memory-adapter prohibition"],
  ["AC", "Secret exposure"],
  ["AD", "Artifact identity"],
  ["AE", "Phase 10C readiness"],
] as const;

export type Phase10b1GateId = (typeof PHASE_10B1_ASSET_INTELLIGENCE_HOSTED_GATES)[number][0];
