export const AU_BOUNDED_SINGLE_ACTION_VALIDATION_STATE = "NUMERICALLY_VALIDATED" as const;
export const AU_BOUNDED_SINGLE_ACTION_SUPPORTED_SCOPE =
  "single-action mechanics-reference tension (gross yield, net fracture), compression squash and Euler, elastic bending and elastic LTB, and shear yield/elastic buckling; not code member design and not combined actions" as const;

export const AU_TENSION_VALIDATION_STATE = "NUMERICALLY_VALIDATED;ENGINEERING_VALIDATION_REQUIRED;INTENDED_PROFILE" as const;
export const AU_COMPRESSION_VALIDATION_STATE = "NUMERICALLY_VALIDATED;ENGINEERING_VALIDATION_REQUIRED;INTENDED_PROFILE;EULER_NOT_CODE_CAPACITY" as const;
export const AU_BENDING_VALIDATION_STATE = "NUMERICALLY_VALIDATED;ENGINEERING_VALIDATION_REQUIRED;INTENDED_PROFILE;ELASTIC_LTB_NOT_CODE_CAPACITY" as const;
export const AU_SHEAR_VALIDATION_STATE = "NUMERICALLY_VALIDATED;ENGINEERING_VALIDATION_REQUIRED;INTENDED_PROFILE" as const;
