import type { OwnerCommandRepository } from "../owner-command/repository";
import type { OwnerCommandScope } from "../owner-command/service";
import type { DecisionActionRepository } from "./repository";
import { asJson, minorCol } from "./repository";

const NOW = "2026-08-19T09:00:00.000Z";

function isoDate(offsetDays: number): string {
  const d = new Date("2026-08-19T00:00:00.000Z");
  d.setUTCDate(d.getUTCDate() + offsetDays);
  return d.toISOString().slice(0, 10);
}

export async function seedDecisionActionDemo(
  decisions: DecisionActionRepository,
  owner: OwnerCommandRepository,
  scope: OwnerCommandScope,
): Promise<{ created: boolean; isDemo: true }> {
  const createdBy = scope.userId;
  const existing = await owner.listDecisions(scope);
  if (existing.some((row) => row.isDemo && row.statement.includes("Hold non-essential spend"))) {
    const already = await decisions.getContextBySourceRef(scope, "demo", "bos-8-demo-cash-context");
    if (already) return { created: false, isDemo: true };
  }

  let cash = existing.find((row) => row.isDemo && row.statement.includes("Hold non-essential spend"));
  if (!cash) {
    cash = await owner.insertDecision(scope, {
      recommendationId: null,
      statement: "Hold non-essential spend until cash runway is reviewed.",
      context: "Demo decision linked to cash runway recommendation. Pending owner confirmation.",
      ownerId: scope.userId,
      status: "pending",
      decision: null,
      rationale: null,
      decidedAt: null,
      reviewAt: isoDate(-1),
      isDemo: true,
      createdBy,
    });
  }

  const signals = await owner.listSignals(scope);
  const cashSignal = signals.find((s) => s.title.toLowerCase().includes("cash")) ?? null;
  const recs = await owner.listRecommendations(scope);
  const cashRec = recs.find((r) => r.title.toLowerCase().includes("cash") || r.title.toLowerCase().includes("spend")) ?? null;

  const cashContext = await decisions.insertContext({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: cash.id,
    question: "Should we hold non-essential spend given cash runway?",
    problem_statement: "Cash runway is below the target band. Owner must decide whether to pause discretionary spend.",
    originating_signal_id: cashSignal?.id ?? null,
    originating_recommendation_id: cashRec?.id ?? cash.recommendationId ?? null,
    domain: "finance",
    owner_label: "Owner",
    stakeholders: asJson(["Finance lead", "Operations lead"]),
    urgency: "critical",
    due_at: isoDate(-2) + "T00:00:00.000Z",
    evidence_completeness_bps: 8000,
    assumptions: asJson(["Runway figure is from the latest demo cash KPI"]),
    constraints: asJson(["No autonomous spend freeze", "Human approval required"]),
    source_type: "demo",
    source_ref: "bos-8-demo-cash-context",
    provenance: asJson({ fixture: "bos-8-decision-action", live: false, capturedAt: NOW }),
    is_demo: true,
    created_by: createdBy,
  });

  await decisions.insertEvidence({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: cash.id,
    option_id: null,
    source_type: "kpi",
    source_domain: "finance",
    source_id: "cash_runway_months",
    source_ref: "bos-1-demo:cash_runway_months",
    summary: "Cash runway 4.2 months at link time",
    value_state: "known",
    value_text: "4.2 months",
    value_minor: null,
    currency: null,
    scale: null,
    unit: "months",
    observed_at: NOW,
    freshness: "point_in_time",
    confidence: "high",
    evidence_quality: "high",
    snapshot: asJson({ key: "cash_runway_months", value: 4.2, capturedAt: NOW }),
    generated_by: "deterministic_rule",
    provenance: asJson({ domain: "finance", live: false, pointInTime: true }),
    is_demo: true,
    created_by: createdBy,
  });

  const hold = await decisions.insertOption({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: cash.id,
    title: "Hold discretionary spend",
    description: "Pause non-essential software and hiring until runway is reviewed.",
    status: "preferred",
    assumptions: asJson(["Discretionary spend is identifiable"]),
    constraints: asJson(["Payroll and contracted delivery continue"]),
    expected_benefits: "Preserve cash",
    expected_costs: "Delayed capability investment",
    expected_risks: "Delivery slowdown if over-applied",
    reversibility: "reversible",
    generated_by: "user",
    ai_generated: false,
    source_type: "demo",
    source_ref: "bos-8-demo-option-hold",
    provenance: asJson({ fixture: "bos-8-decision-action" }),
    is_demo: true,
    created_by: createdBy,
  });

  const continueSpend = await decisions.insertOption({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: cash.id,
    title: "Continue current spend",
    description: "Keep current discretionary commitments.",
    status: "candidate",
    assumptions: asJson(["Receivables collect on the demo schedule"]),
    constraints: asJson([]),
    expected_benefits: "No disruption",
    expected_costs: "Cash continues to decline",
    expected_risks: "Runway compression",
    reversibility: "partially_reversible",
    generated_by: "user",
    ai_generated: false,
    source_type: "demo",
    source_ref: "bos-8-demo-option-continue",
    provenance: asJson({ fixture: "bos-8-decision-action" }),
    is_demo: true,
    created_by: createdBy,
  });

  await decisions.insertOption({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: cash.id,
    title: "Immediate vendor termination (AI proposal)",
    description: "AI-generated proposal to terminate vendors immediately. Labelled as AI-generated and rejected.",
    status: "rejected",
    assumptions: asJson(["AI draft only"]),
    constraints: asJson(["No autonomous termination"]),
    expected_benefits: "Faster cash preservation (unsupported)",
    expected_costs: "Contractual risk",
    expected_risks: "Irreversible external action — forbidden",
    reversibility: "irreversible",
    generated_by: "platform_ai_director",
    ai_generated: true,
    source_type: "demo",
    source_ref: "bos-8-demo-option-ai-rejected",
    provenance: asJson({ fixture: "bos-8-decision-action", aiGenerated: true, rejected: true }),
    is_demo: true,
    created_by: createdBy,
  });

  await decisions.insertImpact({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    option_id: hold.id,
    dimension: "financial",
    quantification: "quantitative",
    value_minor: minorCol(2500000),
    currency: "AUD",
    scale: 2,
    unit: "AUD",
    period: "2026-Q3",
    qualitative_label: null,
    qualitative_only: false,
    source_domain: "finance",
    source_ref: "bos-2-demo:cash",
    rule_version: "finance.cash_impact.v1",
    source_type: "demo",
    provenance: asJson({ domain: "finance", deterministic: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertImpact({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    option_id: hold.id,
    dimension: "operational",
    quantification: "unknown",
    value_minor: null,
    currency: null,
    scale: null,
    unit: null,
    period: null,
    qualitative_label: null,
    qualitative_only: false,
    source_domain: "operations",
    source_ref: null,
    rule_version: null,
    source_type: "demo",
    provenance: asJson({ domain: "operations", unknown: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertImpact({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    option_id: continueSpend.id,
    dimension: "financial",
    quantification: "quantitative",
    value_minor: minorCol(-1800000),
    currency: "AUD",
    scale: 2,
    unit: "AUD",
    period: "2026-Q3",
    qualitative_label: null,
    qualitative_only: false,
    source_domain: "finance",
    source_ref: "bos-2-demo:cash",
    rule_version: "finance.cash_impact.v1",
    source_type: "demo",
    provenance: asJson({ domain: "finance", deterministic: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertImpact({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    option_id: hold.id,
    dimension: "customer",
    quantification: "qualitative",
    value_minor: null,
    currency: null,
    scale: null,
    unit: null,
    period: null,
    qualitative_label: "Possible delivery delay if applied to customer work",
    qualitative_only: true,
    source_domain: "customer",
    source_ref: "bos-5-demo-customer-ref",
    rule_version: null,
    source_type: "demo",
    provenance: asJson({ domain: "customer", qualitative: true }),
    is_demo: true,
    created_by: createdBy,
  });

  await decisions.updateContext(scope, cashContext.id, { selected_option_id: hold.id });

  const noEvidence = await owner.insertDecision(scope, {
    recommendationId: null,
    statement: "Expand a new service line without supporting evidence.",
    context: "Demo: pending decision with no evidence bundle.",
    ownerId: scope.userId,
    status: "pending",
    decision: null,
    rationale: null,
    decidedAt: null,
    reviewAt: isoDate(14),
    isDemo: true,
    createdBy,
  });
  await decisions.insertContext({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: noEvidence.id,
    question: "Should we expand the service line now?",
    problem_statement: "Growth hypothesis without evidence.",
    originating_signal_id: null,
    originating_recommendation_id: null,
    domain: "growth",
    owner_label: "Owner",
    stakeholders: asJson([]),
    urgency: "normal",
    due_at: isoDate(10) + "T00:00:00.000Z",
    evidence_completeness_bps: 0,
    assumptions: asJson(["Demand exists — unverified"]),
    constraints: asJson(["No evidence linked"]),
    source_type: "demo",
    source_ref: "bos-8-demo-no-evidence",
    provenance: asJson({ fixture: "bos-8-decision-action", noEvidence: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertOption({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: noEvidence.id,
    title: "Expand now",
    description: "Single option with no evidence.",
    status: "candidate",
    assumptions: asJson([]),
    constraints: asJson([]),
    expected_benefits: null,
    expected_costs: null,
    expected_risks: null,
    reversibility: "unknown",
    generated_by: "user",
    ai_generated: false,
    source_type: "demo",
    source_ref: "bos-8-demo-single-option",
    provenance: asJson({ fixture: "bos-8-decision-action" }),
    is_demo: true,
    created_by: createdBy,
  });

  const approvedNoAction = await owner.insertDecision(scope, {
    recommendationId: null,
    statement: "Adopt a standard weekly operations review.",
    context: "Demo: approved decision with no linked actions.",
    ownerId: scope.userId,
    status: "approved",
    decision: "approve",
    rationale: "Human owner approved in demo.",
    decidedAt: NOW,
    reviewAt: isoDate(-3),
    isDemo: true,
    createdBy,
  });
  await decisions.insertContext({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: approvedNoAction.id,
    question: "Should operations run a weekly review?",
    problem_statement: "Delivery visibility is uneven.",
    originating_signal_id: null,
    originating_recommendation_id: null,
    domain: "operations",
    owner_label: "Owner",
    stakeholders: asJson(["Operations"]),
    urgency: "high",
    due_at: isoDate(-5) + "T00:00:00.000Z",
    evidence_completeness_bps: 5000,
    assumptions: asJson(["Review capacity exists"]),
    constraints: asJson([]),
    source_type: "demo",
    source_ref: "bos-8-demo-approved-no-action",
    provenance: asJson({ fixture: "bos-8-decision-action", approvedWithoutAction: true }),
    is_demo: true,
    created_by: createdBy,
  });

  const mixed = await owner.insertDecision(scope, {
    recommendationId: null,
    statement: "Pilot a new customer success motion.",
    context: "Demo: expected vs actual incomparable currencies.",
    ownerId: scope.userId,
    status: "approved",
    decision: "approve",
    rationale: "Human approved the pilot.",
    decidedAt: NOW,
    reviewAt: isoDate(21),
    isDemo: true,
    createdBy,
  });
  const mixedOption = await decisions.insertOption({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: mixed.id,
    title: "Run a 90-day pilot",
    description: "Bounded pilot.",
    status: "selected",
    assumptions: asJson(["Currency of expected metric is AUD"]),
    constraints: asJson([]),
    expected_benefits: "Retention improvement",
    expected_costs: null,
    expected_risks: null,
    reversibility: "reversible",
    generated_by: "user",
    ai_generated: false,
    source_type: "demo",
    source_ref: "bos-8-demo-mixed-option",
    provenance: asJson({ fixture: "bos-8-decision-action" }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertContext({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: mixed.id,
    question: "Should we pilot a customer success motion?",
    problem_statement: "Retention risk on a high-value account.",
    originating_signal_id: null,
    originating_recommendation_id: null,
    domain: "customer",
    owner_label: "Owner",
    stakeholders: asJson(["Customer lead"]),
    urgency: "high",
    due_at: isoDate(3) + "T00:00:00.000Z",
    evidence_completeness_bps: 6000,
    assumptions: asJson(["Expected metric remains AUD"]),
    constraints: asJson([]),
    selected_option_id: mixedOption.id,
    source_type: "demo",
    source_ref: "bos-8-demo-mixed-context",
    provenance: asJson({ fixture: "bos-8-decision-action" }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertOutcome({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: mixed.id,
    selected_option_id: mixedOption.id,
    expected_outcome: "Reduce at-risk revenue",
    expected_metric_key: "customer_revenue_at_risk",
    expected_value: 50000,
    expected_unit: "currency",
    expected_currency: "AUD",
    expected_scale: 2,
    expected_period: "2026-Q3",
    actual_outcome: "USD actual recorded — incomparable",
    actual_metric_key: "customer_revenue_at_risk",
    actual_value: 40000,
    actual_unit: "currency",
    actual_currency: "USD",
    actual_scale: 2,
    actual_period: "2026-Q3",
    measurement_date: isoDate(0),
    status: "inconclusive",
    variance_value: null,
    variance_state: "unknown",
    explanation: "Currencies differ; variance remains unknown.",
    evidence_refs: asJson([{ sourceType: "kpi", sourceRef: "customer_revenue_at_risk", title: "At-risk revenue" }]),
    source_type: "demo",
    source_ref: "bos-8-demo-outcome-mixed-currency",
    provenance: asJson({ fixture: "bos-8-decision-action", incomparable: true }),
    is_demo: true,
    created_by: createdBy,
  });

  const closed = await owner.insertDecision(scope, {
    recommendationId: null,
    statement: "Standardise a profit leakage review cadence.",
    context: "Demo: measured outcome achieved.",
    ownerId: scope.userId,
    status: "closed",
    decision: "close",
    rationale: "Review completed.",
    decidedAt: "2026-07-01T09:00:00.000Z",
    reviewAt: isoDate(-10),
    isDemo: true,
    createdBy,
  });
  const closedOption = await decisions.insertOption({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: closed.id,
    title: "Monthly leakage review",
    description: "Selected option.",
    status: "selected",
    assumptions: asJson(["Leakage KPI remains defined"]),
    constraints: asJson([]),
    expected_benefits: "Earlier leakage detection",
    expected_costs: null,
    expected_risks: null,
    reversibility: "reversible",
    generated_by: "user",
    ai_generated: false,
    source_type: "demo",
    source_ref: "bos-8-demo-closed-option",
    provenance: asJson({ fixture: "bos-8-decision-action" }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertContext({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: closed.id,
    question: "Should profit leakage be reviewed monthly?",
    problem_statement: "Leakage was detected without a review cadence.",
    originating_signal_id: null,
    originating_recommendation_id: null,
    domain: "profit",
    owner_label: "Owner",
    stakeholders: asJson(["Finance"]),
    urgency: "normal",
    due_at: "2026-07-01T00:00:00.000Z",
    evidence_completeness_bps: 9000,
    assumptions: asJson(["Leakage total is sourced from Profit Intelligence"]),
    constraints: asJson([]),
    selected_option_id: closedOption.id,
    source_type: "demo",
    source_ref: "bos-8-demo-closed-context",
    provenance: asJson({ fixture: "bos-8-decision-action", capturedAt: "2026-07-01T09:00:00.000Z" }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertOutcome({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: closed.id,
    selected_option_id: closedOption.id,
    expected_outcome: "Complete one leakage review",
    expected_metric_key: "profit_leakage_reviews",
    expected_value: 1,
    expected_unit: "count",
    expected_currency: null,
    expected_scale: 0,
    expected_period: "2026-07",
    actual_outcome: "Review completed",
    actual_metric_key: "profit_leakage_reviews",
    actual_value: 1,
    actual_unit: "count",
    actual_currency: null,
    actual_scale: 0,
    actual_period: "2026-07",
    measurement_date: "2026-07-31",
    status: "achieved",
    variance_value: 0,
    variance_state: "computed",
    explanation: "Sourced count matched expected.",
    evidence_refs: asJson([{ sourceType: "kpi", sourceRef: "profit_leakage_total", title: "Leakage review completed" }]),
    source_type: "demo",
    source_ref: "bos-8-demo-outcome-achieved",
    provenance: asJson({ fixture: "bos-8-decision-action" }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertLesson({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: closed.id,
    selected_option_id: closedOption.id,
    assumptions_snapshot: asJson(["Leakage KPI remains defined"]),
    evidence_snapshot: asJson({ capturedAt: "2026-07-01T09:00:00.000Z", evidence: ["profit_leakage_total"] }),
    expected_outcome: "Complete one leakage review",
    actual_outcome: "Review completed",
    lesson_text: "A scheduled review made leakage visible without changing historical evidence.",
    draft_source: "platform_ai_director",
    status: "proposed_ai",
    review_status: "pending",
    source_type: "demo",
    source_ref: "bos-8-demo-lesson-ai",
    provenance: asJson({ fixture: "bos-8-decision-action", organisationalKnowledge: false }),
    is_demo: true,
    created_by: createdBy,
  });
  await decisions.insertLesson({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    decision_id: closed.id,
    selected_option_id: closedOption.id,
    assumptions_snapshot: asJson(["Leakage KPI remains defined"]),
    evidence_snapshot: asJson({ capturedAt: "2026-07-01T09:00:00.000Z" }),
    expected_outcome: "Complete one leakage review",
    actual_outcome: "Review completed",
    lesson_text: "Human-accepted: monthly cadence is sufficient when leakage facts are sourced.",
    draft_source: "user",
    status: "accepted",
    accepted_at: NOW,
    accepted_by: createdBy,
    review_status: "reviewed",
    source_type: "demo",
    source_ref: "bos-8-demo-lesson-accepted",
    provenance: asJson({ fixture: "bos-8-decision-action", organisationalKnowledge: true }),
    is_demo: true,
    created_by: createdBy,
  });

  return { created: true, isDemo: true };
}
