import type { EuBendingMethodRecord } from "@rtb/types";

export const EU_BENDING_IMPLEMENTATION_VERSION = "eu-bending-1.0.0" as const;
export const EU_BENDING_TOOL_REF = "EOS_EU_STEEL_BENDING" as const;

const MECHANICS_YIELD = "established-mechanics-first-yield-moment-equals-fy-times-elastic-section-modulus";
const MECHANICS_LTB = "established-mechanics-uniform-moment-elastic-critical-ltb-sqrt-pi2-EIy-L2-times-GJ-plus-pi2-EIw-L2";

export const EU_BENDING_ELASTIC_MAJOR_MECHANICS_RULE: EuBendingMethodRecord = {
  ruleId: "EU-BENDING-ELASTIC-MAJOR-MECHANICS-V1",
  methodId: "EU_BENDING_ELASTIC_MAJOR_MECHANICS",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_YIELD,
  calculationPurpose: "elastic first-yield moment about the major axis as a mechanics reference, not EN 1993 Mc,Rd",
  applicability: "steel members with explicit fy and major-axis elastic section modulus",
  requiredInputs: ["material.yieldStrength", "section.sectionModulusYy"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_BENDING",
  units: "N.m",
  implementationVersion: EU_BENDING_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["EU-BENDING-BM-ELASTIC-MAJOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "eu-bending-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "NO_ANNEX_DEPENDENCY",
  ruleRequiresNdp: false,
  axis: "MAJOR_AXIS",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const EU_BENDING_ELASTIC_MINOR_MECHANICS_RULE: EuBendingMethodRecord = {
  ruleId: "EU-BENDING-ELASTIC-MINOR-MECHANICS-V1",
  methodId: "EU_BENDING_ELASTIC_MINOR_MECHANICS",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_YIELD,
  calculationPurpose: "elastic first-yield moment about the minor axis as a mechanics reference, not EN 1993 Mc,Rd",
  applicability: "steel members with explicit fy and minor-axis elastic section modulus",
  requiredInputs: ["material.yieldStrength", "section.sectionModulusZz"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_BENDING",
  units: "N.m",
  implementationVersion: EU_BENDING_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["EU-BENDING-BM-ELASTIC-MINOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "eu-bending-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "NO_ANNEX_DEPENDENCY",
  ruleRequiresNdp: false,
  axis: "MINOR_AXIS",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const EU_BENDING_ELASTIC_LTB_MECHANICS_RULE: EuBendingMethodRecord = {
  ruleId: "EU-BENDING-ELASTIC-LTB-MECHANICS-V1",
  methodId: "EU_BENDING_ELASTIC_LTB_MECHANICS",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_LTB,
  calculationPurpose: "uniform-moment elastic critical LTB moment as a mechanics reference; no Eurocode reduction",
  applicability: "doubly-symmetric prismatic members with explicit E, G, Iminor, J, Iw, unbraced length, and LTB restraint",
  requiredInputs: ["material.elasticModulus", "material.shearModulus", "section.Izz", "section.torsionConstant", "section.warpingConstant", "stability.unbracedLengthM"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_LTB",
  units: "N.m",
  implementationVersion: EU_BENDING_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["EU-BENDING-BM-ELASTIC-LTB-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "eu-bending-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "NO_ANNEX_DEPENDENCY",
  ruleRequiresNdp: false,
  axis: "LTB",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const EU_SECTION_BENDING_CAPACITY_CODE_PROFILE_RULE: EuBendingMethodRecord = {
  ruleId: "EU-SECTION-BENDING-CAPACITY-CODE-PROFILE-V1",
  methodId: "EU_SECTION_BENDING_CAPACITY_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-section-bending-resistance-validation-required",
  calculationPurpose: "Eurocode-profile section bending resistance Mc,Rd",
  applicability: "not implemented; requires governed classification, elastic/plastic/effective mapping, partial factor, and confirmed edition",
  requiredInputs: ["material.yieldStrength", "section modulus", "classification", "ndp.partial-factor"],
  outputType: "EUROCODE_PROFILE_SECTION_CAPACITY",
  units: "N.m",
  implementationVersion: EU_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_SECTION_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: ["partial-factor"],
  annexDependency: "NDP_REQUIRED",
  ruleRequiresNdp: true,
  axis: "SECTION",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "FRAMEWORK_ONLY",
};

export const EU_MEMBER_BENDING_LTB_CODE_PROFILE_RULE: EuBendingMethodRecord = {
  ruleId: "EU-MEMBER-BENDING-LTB-CODE-PROFILE-V1",
  methodId: "EU_MEMBER_BENDING_LTB_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-member-bending-ltb-resistance-validation-required",
  calculationPurpose: "Eurocode-profile member bending resistance Mb,Rd",
  applicability: "not implemented; requires classification, LTB curve, reduction factor, moment factor, partial factor, edition, and National Annex/NDP",
  requiredInputs: ["classification", "ltb-curve", "unbracedLength", "momentDistribution", "ndp.partial-factor"],
  outputType: "EUROCODE_PROFILE_MEMBER_CAPACITY",
  units: "N.m",
  implementationVersion: EU_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_MEMBER_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: ["partial-factor"],
  annexDependency: "NDP_REQUIRED",
  ruleRequiresNdp: true,
  axis: "LTB",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "FRAMEWORK_ONLY",
};

export const EU_LTB_CURVE_SELECTION_CODE_PROFILE_RULE: EuBendingMethodRecord = {
  ruleId: "EU-LTB-CURVE-SELECTION-CODE-PROFILE-V1",
  methodId: "EU_LTB_CURVE_SELECTION_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-ltb-curve-selection-validation-required",
  calculationPurpose: "Eurocode-profile LTB curve/rule selection",
  applicability: "not implemented; curve coefficients and selection rules are unvalidated",
  requiredInputs: ["sectionFamily", "axis", "fabricationContext", "standardPart", "edition", "nationalAnnex"],
  outputType: "EUROCODE_PROFILE_LTB_CURVE",
  units: "1",
  implementationVersion: EU_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_MEMBER_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "ANNEX_OPTIONAL",
  ruleRequiresNdp: false,
  axis: "LTB",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "FRAMEWORK_ONLY",
};

export const EU_BENDING_SECTION_CLASSIFICATION_CODE_PROFILE_RULE: EuBendingMethodRecord = {
  ruleId: "EU-BENDING-SECTION-CLASSIFICATION-CODE-PROFILE-V1",
  methodId: "EU_BENDING_SECTION_CLASSIFICATION_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-section-classification-validation-required",
  calculationPurpose: "Eurocode-profile section classification for bending",
  applicability: "not implemented; classification limits, epsilon, and class mapping are unvalidated",
  requiredInputs: ["section geometry", "material.yieldStrength", "standardPart", "edition"],
  outputType: "EUROCODE_PROFILE_SECTION_CLASSIFICATION",
  units: "1",
  implementationVersion: EU_BENDING_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-bending-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_SECTION_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "ANNEX_OPTIONAL",
  ruleRequiresNdp: false,
  axis: "CLASSIFICATION",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "VALIDATION_REQUIRED",
};

export const EU_BENDING_METHOD_REGISTRY: readonly EuBendingMethodRecord[] = [
  EU_BENDING_ELASTIC_MAJOR_MECHANICS_RULE,
  EU_BENDING_ELASTIC_MINOR_MECHANICS_RULE,
  EU_BENDING_ELASTIC_LTB_MECHANICS_RULE,
  EU_SECTION_BENDING_CAPACITY_CODE_PROFILE_RULE,
  EU_MEMBER_BENDING_LTB_CODE_PROFILE_RULE,
  EU_LTB_CURVE_SELECTION_CODE_PROFILE_RULE,
  EU_BENDING_SECTION_CLASSIFICATION_CODE_PROFILE_RULE,
];

export const IMPLEMENTED_EU_BENDING_METHODS = [
  EU_BENDING_ELASTIC_MAJOR_MECHANICS_RULE.methodId,
  EU_BENDING_ELASTIC_MINOR_MECHANICS_RULE.methodId,
  EU_BENDING_ELASTIC_LTB_MECHANICS_RULE.methodId,
] as const;

export const FRAMEWORK_ONLY_EU_BENDING_METHODS = [
  EU_SECTION_BENDING_CAPACITY_CODE_PROFILE_RULE.methodId,
  EU_MEMBER_BENDING_LTB_CODE_PROFILE_RULE.methodId,
  EU_LTB_CURVE_SELECTION_CODE_PROFILE_RULE.methodId,
  EU_BENDING_SECTION_CLASSIFICATION_CODE_PROFILE_RULE.methodId,
] as const;
