import type { SecureComputePlane } from "../../secure-compute-contracts";
import { secureComputePlaneHarnessKeys } from "./fixture-harness";

export type SecureComputeProbeDefinition = {
  probeId: string;
  name: string;
  version: string;
  plane: SecureComputePlane;
  harnessKey: string;
  controlRefs: string[];
  status: "draft" | "active" | "deprecated" | "retired";
  productionSafe: true;
  mutatesAuthorization: false;
  mutatesRls: false;
  mutatesPolicy: false;
  mutatesRuntime: false;
};

export const SEED_SECURE_COMPUTE_PROBES: SecureComputeProbeDefinition[] = [
  {
    probeId: "sc-identity-ok",
    name: "Workload identity attributable",
    version: "1.0.0",
    plane: "WORKLOAD_IDENTITY",
    harnessKey: "identity.attributable",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-identity-missing",
    name: "Missing identity fail-closed",
    version: "1.0.0",
    plane: "WORKLOAD_IDENTITY",
    harnessKey: "identity.missing_fail_closed",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-tenant-deny",
    name: "Cross-tenant execution deny",
    version: "1.0.0",
    plane: "TENANT_WORKSPACE_SCOPE",
    harnessKey: "scope.cross_tenant_deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-workspace-deny",
    name: "Cross-workspace execution deny",
    version: "1.0.0",
    plane: "TENANT_WORKSPACE_SCOPE",
    harnessKey: "scope.cross_workspace_deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-role-deny",
    name: "Insufficient-role denial",
    version: "1.0.0",
    plane: "EXECUTION_AUTHORIZATION",
    harnessKey: "authz.role_insufficient_deny",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-policy-link",
    name: "Policy decision linkage",
    version: "1.0.0",
    plane: "EXECUTION_AUTHORIZATION",
    harnessKey: "authz.policy_linked",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-runtime-iso",
    name: "Runtime isolation assessment",
    version: "1.0.0",
    plane: "RUNTIME_ISOLATION",
    harnessKey: "runtime.isolation_assessed",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-fs-scope",
    name: "Filesystem scope where supported",
    version: "1.0.0",
    plane: "FILESYSTEM_SCOPE",
    harnessKey: "filesystem.scope_where_supported",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-net-unknown",
    name: "Network egress unknown posture",
    version: "1.0.0",
    plane: "NETWORK_EGRESS",
    harnessKey: "network.egress_unknown",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-secret-ref",
    name: "Authorised secret-reference handling",
    version: "1.0.0",
    plane: "SECRET_ACCESS",
    harnessKey: "secret.authorised_ref",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-resource",
    name: "Resource-bound semantics",
    version: "1.0.0",
    plane: "RESOURCE_LIMITS",
    harnessKey: "resource.limits_semantics",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-timeout",
    name: "Timeout/error handling",
    version: "1.0.0",
    plane: "EXECUTION_TIMEOUT",
    harnessKey: "timeout.error_not_pass",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-artefact",
    name: "Artefact identity/hash preservation",
    version: "1.0.0",
    plane: "ARTEFACT_INTEGRITY",
    harnessKey: "artefact.hash_preserved",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-provenance",
    name: "Execution provenance linkage",
    version: "1.0.0",
    plane: "EXECUTION_PROVENANCE",
    harnessKey: "provenance.linked",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-output",
    name: "Output scope preservation",
    version: "1.0.0",
    plane: "OUTPUT_HANDLING",
    harnessKey: "output.scope_preserved",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-temp",
    name: "Temporary-data handling",
    version: "1.0.0",
    plane: "TEMPORARY_DATA",
    harnessKey: "temp.cleanup_where_supported",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-logging",
    name: "Logging/evidence secret redaction",
    version: "1.0.0",
    plane: "LOGGING_TELEMETRY",
    harnessKey: "logging.no_secret_persist",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-host",
    name: "Host posture unknown handling",
    version: "1.0.0",
    plane: "HOST_POSTURE",
    harnessKey: "host.posture_unknown",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-bg-job",
    name: "Background-job scope",
    version: "1.0.0",
    plane: "TENANT_WORKSPACE_SCOPE",
    harnessKey: "background.job_scope",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
  {
    probeId: "sc-tee-na",
    name: "TEE/confidential computing NOT_APPLICABLE",
    version: "1.0.0",
    plane: "HOST_POSTURE",
    harnessKey: "tee.not_applicable",
    controlRefs: ["RTB-SEC-S07"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
    mutatesRuntime: false,
  },
];

export function assertSecureComputeHarnessCoverage(): void {
  for (const plane of [
    "WORKLOAD_IDENTITY",
    "TENANT_WORKSPACE_SCOPE",
    "EXECUTION_AUTHORIZATION",
    "RUNTIME_ISOLATION",
    "FILESYSTEM_SCOPE",
    "NETWORK_EGRESS",
    "SECRET_ACCESS",
    "RESOURCE_LIMITS",
    "EXECUTION_TIMEOUT",
    "ARTEFACT_INTEGRITY",
    "EXECUTION_PROVENANCE",
    "OUTPUT_HANDLING",
    "TEMPORARY_DATA",
    "LOGGING_TELEMETRY",
    "HOST_POSTURE",
  ] as const) {
    const keys = secureComputePlaneHarnessKeys(plane);
    if (keys.length === 0) throw new Error(`No harness keys for plane ${plane}`);
    const covered = SEED_SECURE_COMPUTE_PROBES.some(
      (p) => p.plane === plane && keys.includes(p.harnessKey),
    );
    if (!covered) throw new Error(`No seed probe covering plane ${plane}`);
  }
}
