import type { UsTensionMethodRecord } from "@rtb/types";
import { AISC_UNKNOWN_EDITION_TOKEN } from "@rtb/types";

export const US_TENSION_IMPLEMENTATION_VERSION = "us-tension-1.0.0" as const;
export const US_TENSION_TOOL_REF = "EOS_US_STEEL_TENSION" as const;

const MECHANICS_BASIS = "established-mechanics-nominal-tension-force-equals-stress-times-area";
const EDITIONS = [AISC_UNKNOWN_EDITION_TOKEN] as const;

export const US_TENSION_GROSS_YIELD_MECHANICS_RULE: UsTensionMethodRecord = {
  ruleId: "US-TENSION-GROSS-YIELD-MECHANICS-V1",
  methodId: "US_TENSION_GROSS_YIELD_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_BASIS,
  calculationPurpose: "nominal tensile yield resistance of the governed gross metal area",
  applicability: "steel tension members with explicit governed Fy and gross area; holes ignored; not AISC design strength",
  requiredInputs: ["material.yieldStrength", "section.area"],
  outputType: "ENGINEERING_MECHANICS_REFERENCE_GROSS_YIELD",
  units: "N",
  implementationVersion: US_TENSION_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-TENSION-BM-GROSS-YIELD-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-tension-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  loadBasisRequirement: "NONE",
  factorDependencies: [],
  localAmendmentDependencies: [],
  sectionPropertyDependencies: ["section.area"],
  materialPropertyDependencies: ["material.yieldStrength"],
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_TENSION_NET_FRACTURE_MECHANICS_RULE: UsTensionMethodRecord = {
  ruleId: "US-TENSION-NET-FRACTURE-MECHANICS-V1",
  methodId: "US_TENSION_NET_FRACTURE_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_BASIS,
  calculationPurpose: "nominal tensile fracture resistance of the explicit governed net metal area",
  applicability: "steel tension members with explicit governed Fu and net area; net area must not be inferred as Ag",
  requiredInputs: ["material.ultimateStrength", "section.netArea"],
  outputType: "ENGINEERING_MECHANICS_REFERENCE_NET_FRACTURE",
  units: "N",
  implementationVersion: US_TENSION_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-TENSION-BM-NET-FRACTURE-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-tension-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  loadBasisRequirement: "NONE",
  factorDependencies: [],
  localAmendmentDependencies: [],
  sectionPropertyDependencies: ["section.netArea"],
  materialPropertyDependencies: ["material.ultimateStrength"],
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_TENSION_EFFECTIVE_NET_FRACTURE_RULE: UsTensionMethodRecord = {
  ruleId: "US-TENSION-EFFECTIVE-NET-FRACTURE-V1",
  methodId: "US_TENSION_EFFECTIVE_NET_FRACTURE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-effective-net-area-shear-lag-validation-required",
  calculationPurpose: "AISC-profile effective-net-area / shear-lag tensile fracture",
  applicability: "not implemented; shear-lag factor U and Ae must be governed",
  requiredInputs: ["material.ultimateStrength", "section.netArea", "factor.shear-lag-U"],
  outputType: "AISC_EFFECTIVE_NET_FRACTURE",
  units: "N",
  implementationVersion: US_TENSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-tension-effective-net-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "NOMINAL_STRENGTH_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  loadBasisRequirement: "NONE",
  factorDependencies: ["shear-lag-U"],
  localAmendmentDependencies: [],
  sectionPropertyDependencies: ["section.netArea", "effectiveNetArea"],
  materialPropertyDependencies: ["material.ultimateStrength"],
  compatibleEditions: EDITIONS,
  scopeState: "VALIDATION_REQUIRED",
};

function aiscProfileRule(
  methodId: string,
  ruleId: string,
  designMethod: "LRFD" | "ASD",
  outputType: string,
  loadBasis: "STRENGTH" | "ALLOWABLE",
  factorId: string,
  requiredInputs: string[],
): UsTensionMethodRecord {
  return {
    ruleId,
    methodId,
    jurisdiction: "united-states",
    standardProfileRef: "us-steel-aisc360-intended",
    authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
    technicalBasisRef: "aisc360-tension-design-strength-validation-required",
    calculationPurpose: `${designMethod} AISC-profile tension strength; factors not populated in US-2`,
    applicability: "not implemented; requires governed edition, factor, areas, and compatible load basis",
    requiredInputs,
    outputType,
    units: "N",
    implementationVersion: US_TENSION_IMPLEMENTATION_VERSION,
    validationState: "FRAMEWORK_ONLY",
    benchmarkRefs: [],
    humanReviewState: "required",
    provenanceRef: "us-tension-code-profile-unvalidated-v1",
    clauseRef: null,
    intendedStandardProfile: "AISC360",
    standardConformanceState: "INTENDED_PROFILE",
    bindingState: "FRAMEWORK_ONLY",
    methodType: designMethod === "LRFD" ? "AISC_LRFD_DESIGN_STRENGTH" : "AISC_ASD_ALLOWABLE_STRENGTH",
    aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
    designMethodApplicability: designMethod,
    loadBasisRequirement: loadBasis,
    factorDependencies: [factorId],
    localAmendmentDependencies: [],
    sectionPropertyDependencies: requiredInputs.filter((name) => name.startsWith("section.")),
    materialPropertyDependencies: requiredInputs.filter((name) => name.startsWith("material.")),
    compatibleEditions: EDITIONS,
    scopeState: "FRAMEWORK_ONLY",
  };
}

export const US_TENSION_GROSS_YIELD_LRFD_RULE = aiscProfileRule(
  "US_TENSION_GROSS_YIELD_LRFD",
  "US-TENSION-GROSS-YIELD-LRFD-V1",
  "LRFD",
  "AISC_LRFD_DESIGN_STRENGTH_GROSS_YIELD",
  "STRENGTH",
  "phi-t-yield",
  ["material.yieldStrength", "section.area", "factor.phi-t-yield"],
);

export const US_TENSION_NET_FRACTURE_LRFD_RULE = aiscProfileRule(
  "US_TENSION_NET_FRACTURE_LRFD",
  "US-TENSION-NET-FRACTURE-LRFD-V1",
  "LRFD",
  "AISC_LRFD_DESIGN_STRENGTH_NET_FRACTURE",
  "STRENGTH",
  "phi-t-fracture",
  ["material.ultimateStrength", "section.netArea", "factor.phi-t-fracture"],
);

export const US_TENSION_GROSS_YIELD_ASD_RULE = aiscProfileRule(
  "US_TENSION_GROSS_YIELD_ASD",
  "US-TENSION-GROSS-YIELD-ASD-V1",
  "ASD",
  "AISC_ASD_ALLOWABLE_STRENGTH_GROSS_YIELD",
  "ALLOWABLE",
  "omega-t-yield",
  ["material.yieldStrength", "section.area", "factor.omega-t-yield"],
);

export const US_TENSION_NET_FRACTURE_ASD_RULE = aiscProfileRule(
  "US_TENSION_NET_FRACTURE_ASD",
  "US-TENSION-NET-FRACTURE-ASD-V1",
  "ASD",
  "AISC_ASD_ALLOWABLE_STRENGTH_NET_FRACTURE",
  "ALLOWABLE",
  "omega-t-fracture",
  ["material.ultimateStrength", "section.netArea", "factor.omega-t-fracture"],
);

export const US_TENSION_BLOCK_SHEAR_RULE: UsTensionMethodRecord = {
  ruleId: "US-TENSION-BLOCK-SHEAR-V1",
  methodId: "US_TENSION_BLOCK_SHEAR",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-block-shear-not-implemented",
  calculationPurpose: "block shear rupture — connection-adjacent; out of US-2 member tension scope",
  applicability: "not implemented",
  requiredInputs: [],
  outputType: "AISC_BLOCK_SHEAR",
  units: "N",
  implementationVersion: US_TENSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-tension-block-shear-unimplemented-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "NOMINAL_STRENGTH_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  loadBasisRequirement: "NONE",
  factorDependencies: [],
  localAmendmentDependencies: [],
  sectionPropertyDependencies: [],
  materialPropertyDependencies: [],
  compatibleEditions: EDITIONS,
  scopeState: "NOT_IMPLEMENTED",
};

export const US_TENSION_METHOD_REGISTRY: readonly UsTensionMethodRecord[] = [
  US_TENSION_GROSS_YIELD_MECHANICS_RULE,
  US_TENSION_NET_FRACTURE_MECHANICS_RULE,
  US_TENSION_EFFECTIVE_NET_FRACTURE_RULE,
  US_TENSION_GROSS_YIELD_LRFD_RULE,
  US_TENSION_NET_FRACTURE_LRFD_RULE,
  US_TENSION_GROSS_YIELD_ASD_RULE,
  US_TENSION_NET_FRACTURE_ASD_RULE,
  US_TENSION_BLOCK_SHEAR_RULE,
];

export const IMPLEMENTED_US_TENSION_METHODS = [
  US_TENSION_GROSS_YIELD_MECHANICS_RULE.methodId,
  US_TENSION_NET_FRACTURE_MECHANICS_RULE.methodId,
] as const;

export const FRAMEWORK_ONLY_US_TENSION_METHODS = [
  US_TENSION_EFFECTIVE_NET_FRACTURE_RULE.methodId,
  US_TENSION_GROSS_YIELD_LRFD_RULE.methodId,
  US_TENSION_NET_FRACTURE_LRFD_RULE.methodId,
  US_TENSION_GROSS_YIELD_ASD_RULE.methodId,
  US_TENSION_NET_FRACTURE_ASD_RULE.methodId,
  US_TENSION_BLOCK_SHEAR_RULE.methodId,
] as const;
