/**
 * Phase 12N certification gates A–BT (Digital Twin V1.0 GA closure).
 * 72 gates: A–Z (26) + AA–AZ (26) + BA–BT (20).
 */
export const PHASE_12N_DIGITAL_TWIN_GA_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 12A regression"],
  ["C", "Phase 12B regression"],
  ["D", "Phase 12C regression"],
  ["E", "Phase 12D regression"],
  ["F", "Phase 12E regression"],
  ["G", "Phase 12F regression"],
  ["H", "Phase 12G regression"],
  ["I", "Phase 12H regression"],
  ["J", "Phase 12I regression"],
  ["K", "Phase 12J regression"],
  ["L", "Phase 12K regression"],
  ["M", "Phase 12L spatial discovery pin"],
  ["N", "Phase 12M spatial core pin"],
  ["O", "PI v1 integrity"],
  ["P", "II v1 integrity"],
  ["Q", "AI v1 integrity"],
  ["R", "PC v1 integrity"],
  ["S", "Shared Spatial Domain consume pin"],
  ["T", "Ownership locks"],
  ["U", "V1.0.0 version freeze"],
  ["V", "GA status declaration"],
  ["W", "Package version alignment"],
  ["X", "Single authoritative version source"],
  ["Y", "Module manifest generator"],
  ["Z", "Module manifest snapshot"],
  ["AA", "Capability registry freeze"],
  ["AB", "Service registry freeze"],
  ["AC", "Event contract freeze"],
  ["AD", "Unavailable capability matrix"],
  ["AE", "Module registry drift"],
  ["AF", "Capability matrix document"],
  ["AG", "Public contracts document"],
  ["AH", "Commercial packaging document"],
  ["AI", "Operational certification document"],
  ["AJ", "Operations runbook"],
  ["AK", "Incident response runbook"],
  ["AL", "Recovery runbook"],
  ["AM", "Rollback runbook"],
  ["AN", "Performance baseline document"],
  ["AO", "Unavailable capabilities document"],
  ["AP", "Limitations document"],
  ["AQ", "Physical actuation unavailable"],
  ["AR", "Automatic control unavailable"],
  ["AS", "Predictive/PoF/RUL unavailable"],
  ["AT", "SHM unavailable"],
  ["AU", "Native solver unavailable"],
  ["AV", "Optimization/GIS unavailable"],
  ["AW", "Silent fixture/solver fallback forbidden"],
  ["AX", "Migration lineage 75–85"],
  ["AY", "No batch_86 migration"],
  ["AZ", "Hosted persistence"],
  ["BA", "Tenant isolation / RLS"],
  ["BB", "Real JWT matrix"],
  ["BC", "Workspace isolation / IDOR"],
  ["BD", "HTTP contracts"],
  ["BE", "Health/observability"],
  ["BF", "No production memory repository"],
  ["BG", "Idempotency"],
  ["BH", "Concurrency"],
  ["BI", "Engineering OS module page / entitlements"],
  ["BJ", "GA readiness marker"],
  ["BK", "Unavailable labels in UI"],
  ["BL", "Browser E2E"],
  ["BM", "Upgrade certification"],
  ["BN", "Backup/restore certification"],
  ["BO", "Unit and architecture tests"],
  ["BP", "Release tag integrity"],
  ["BQ", "Four-layer qualification / CalculiX boundary"],
  ["BR", "Spatial ownership resolved via SSD"],
  ["BS", "Simulation GA method boundary"],
  ["BT", "No post-12N feature expansion"],
] as const;

export type Phase12nGateId = (typeof PHASE_12N_DIGITAL_TWIN_GA_GATES)[number][0];

export const PHASE_12N_RELEASE_TAG = "digital-twin-v1.0.0" as const;
export const PHASE_12N_GATE_COUNT = PHASE_12N_DIGITAL_TWIN_GA_GATES.length;
