/**
 * Phase 10I certification gates A–AZ (Multi-Source Fusion, Source Reconciliation,
 * Predictive Readiness). Readiness only — predictive methods are never executed.
 */
export const PHASE_10I_ASSET_INTELLIGENCE_FUSION_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 10A regression"],
  ["C", "Phase 10B regression"],
  ["D", "Phase 10B.1 persistence regression"],
  ["E", "Phase 10C regression"],
  ["F", "Phase 10D regression"],
  ["G", "Phase 10E regression"],
  ["H", "Phase 10F regression"],
  ["I", "Phase 10G regression"],
  ["J", "Authoritative Phase 10H baseline"],
  ["K", "PI v1 integrity"],
  ["L", "II v1 integrity"],
  ["M", "Ownership locks"],
  ["N", "Fusion model doc/terminology"],
  ["O", "MultiSourceFusionEngine"],
  ["P", "Published-slice rule"],
  ["Q", "Source Reconciliation Engine"],
  ["R", "Autonomous resolution forbidden"],
  ["S", "PredictiveReadinessAssessor"],
  ["T", "predictiveMlEnabled=false"],
  ["U", "predictiveMethodsCertified=false"],
  ["V", "No Probability of Failure claim"],
  ["W", "No RUL claim"],
  ["X", "Evidence Confidence"],
  ["Y", "Trend Confidence"],
  ["Z", "Abstention"],
  ["AA", "Health composition unchanged"],
  ["AB", "Fusion not Health factor"],
  ["AC", "Governed review"],
  ["AD", "Segregation of duties"],
  ["AE", "Hosted migration batch_58"],
  ["AF", "Migration lineage 55/55b/56/57/58"],
  ["AG", "Hosted persistence"],
  ["AH", "Snapshot"],
  ["AI", "Timeline"],
  ["AJ", "Event/outbox integrity"],
  ["AK", "II boundary"],
  ["AL", "PI boundary"],
  ["AM", "AI governance"],
  ["AN", "HTTP contracts"],
  ["AO", "Real JWT role matrix"],
  ["AP", "Tenant isolation"],
  ["AQ", "Workspace isolation"],
  ["AR", "IDOR"],
  ["AS", "Idempotency"],
  ["AT", "Concurrency"],
  ["AU", "Health/observability"],
  ["AV", "Performance"],
  ["AW", "No memory production"],
  ["AX", "Secret exposure"],
  ["AY", "Artifact identity"],
  ["AZ", "Phase 10J readiness"],
] as const;

export type Phase10iGateId =
  (typeof PHASE_10I_ASSET_INTELLIGENCE_FUSION_GATES)[number][0];
