import type { BusinessProfitFactIngestInput } from "@rtb/types";

export const PROFIT_DEMO_FIXTURE = "bos-6-profit-intelligence";

export const PROFIT_DEMO_FACTS: BusinessProfitFactIngestInput[] = [
  {
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    dimensionType: "service",
    dimensionRef: "bos-6-demo-service-rework",
    dimensionName: "Rework mobilisation",
    revenueMinor: "1000000",
    directCostMinor: "4500000",
    currency: "AUD",
    valueState: "actual",
    attributionMethod: "source_direct",
    attributionConfidence: "high",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-rework",
    isDemo: true,
    provenance: { fixture: PROFIT_DEMO_FIXTURE, negativeContribution: true },
  },
  {
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    dimensionType: "customer",
    dimensionRef: "bos-5-demo-customer-grid",
    dimensionName: "Grid Expansion Co",
    revenueMinor: "200000000",
    directCostMinor: "192000000",
    currency: "AUD",
    valueState: "actual",
    attributionMethod: "manual",
    attributionConfidence: "medium",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-grid",
    isDemo: true,
    provenance: { fixture: PROFIT_DEMO_FIXTURE, highRevenueLowMargin: true },
  },
  {
    periodStart: "2026-04-01",
    periodEnd: "2026-06-30",
    dimensionType: "customer",
    dimensionRef: "bos-5-demo-customer-grid",
    dimensionName: "Grid Expansion Co",
    revenueMinor: "190000000",
    directCostMinor: "183000000",
    currency: "AUD",
    valueState: "actual",
    attributionMethod: "manual",
    attributionConfidence: "medium",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-grid-prior",
    isDemo: true,
    provenance: { fixture: PROFIT_DEMO_FIXTURE, recurringLowMargin: true },
  },
  {
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    dimensionType: "segment",
    dimensionRef: "bos-3-demo-market-au-infra",
    dimensionName: "Public infrastructure — Australia",
    revenueMinor: "255000000",
    directCostMinor: "204000000",
    allocatedCostMinor: "8000000",
    currency: "AUD",
    valueState: "actual",
    attributionMethod: "source_direct",
    attributionConfidence: "medium",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-segment-au",
    isDemo: true,
    provenance: { fixture: PROFIT_DEMO_FIXTURE, allocatedCostExplicit: true },
  },
  {
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    dimensionType: "opportunity",
    dimensionRef: "bos-3-demo-opp-northbound",
    dimensionName: "Northbound bridge inspection",
    revenueMinor: "80000000",
    directCostMinor: "58000000",
    currency: "AUD",
    valueState: "proposed",
    attributionMethod: "derived_from_known_components",
    attributionConfidence: "medium",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-proposed-northbound",
    isDemo: true,
    provenance: {
      fixture: PROFIT_DEMO_FIXTURE,
      valueState: "proposed",
      targetMarginBps: "2200",
      notRealized: true,
    },
  },
  {
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    dimensionType: "opportunity",
    dimensionRef: "bos-3-demo-opp-northbound",
    dimensionName: "Northbound bridge inspection",
    revenueMinor: "80000000",
    directCostMinor: "62000000",
    currency: "AUD",
    valueState: "actual",
    attributionMethod: "derived_from_known_components",
    attributionConfidence: "medium",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-realized-northbound-opp",
    isDemo: true,
    provenance: { fixture: PROFIT_DEMO_FIXTURE, valueState: "actual", realized: true },
  },
  {
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    dimensionType: "opportunity",
    dimensionRef: "bos-4-demo-price-discount",
    dimensionName: "Northbound discounted proposal",
    revenueMinor: "68000000",
    directCostMinor: "62000000",
    currency: "AUD",
    valueState: "proposed",
    attributionMethod: "derived_from_known_components",
    attributionConfidence: "medium",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-proposed-discount",
    isDemo: true,
    provenance: {
      fixture: PROFIT_DEMO_FIXTURE,
      valueState: "proposed",
      targetMarginBps: "2200",
      discountBps: "1500",
      notRealized: true,
    },
  },
  {
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    dimensionType: "service",
    dimensionRef: "bos-6-demo-service-usd",
    dimensionName: "NZ inspection day-rate",
    revenueMinor: "5000000",
    directCostMinor: "3100000",
    currency: "USD",
    valueState: "actual",
    attributionMethod: "imported",
    attributionConfidence: "low",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-usd",
    isDemo: true,
    provenance: { fixture: PROFIT_DEMO_FIXTURE, multiCurrency: true },
  },
  {
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    dimensionType: "service",
    dimensionRef: "bos-6-demo-service-refund",
    dimensionName: "Credit note — cancelled survey",
    revenueMinor: "-2000000",
    directCostMinor: "0",
    currency: "AUD",
    valueState: "actual",
    attributionMethod: "source_direct",
    attributionConfidence: "high",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-refund",
    isDemo: true,
    provenance: { fixture: PROFIT_DEMO_FIXTURE, negativeRevenue: true },
  },
  {
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    dimensionType: "project",
    dimensionRef: "bos-6-demo-project-cost-only",
    dimensionName: "Mobilisation without billable output",
    directCostMinor: "1500000",
    currency: "AUD",
    valueState: "actual",
    attributionMethod: "source_direct",
    attributionConfidence: "medium",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-cost-only",
    isDemo: true,
    provenance: { fixture: PROFIT_DEMO_FIXTURE, costWithoutRevenue: true },
  },
  {
    periodStart: "2024-01-01",
    periodEnd: "2024-03-31",
    dimensionType: "service",
    dimensionRef: "bos-6-demo-service-stale",
    dimensionName: "Archived survey package",
    revenueMinor: "4000000",
    directCostMinor: "2500000",
    currency: "AUD",
    valueState: "actual",
    attributionMethod: "imported",
    attributionConfidence: "low",
    sourceType: "demo",
    sourceRef: "bos-6-demo-fact-stale",
    sourceTimestamp: "2024-04-01T00:00:00.000Z",
    isDemo: true,
    provenance: { fixture: PROFIT_DEMO_FIXTURE, stale: true },
  },
];
