/**
 * Phase 11D — Project Controls capability matrix.
 *
 * Segregation of duties: the role that assesses cannot approve or publish.
 * CPM / cost / earned value / forecast / contingency / financial posting
 * capabilities remain absent. Change capabilities cover the *assessment*
 * lifecycle only — no capability here confers contractual change authority.
 */

export const PROJECT_CONTROLS_ROLES = [
  "viewer",
  "project_controls_engineer",
  "reviewer",
  "approver",
  "admin",
] as const;

export type ProjectControlsRole = (typeof PROJECT_CONTROLS_ROLES)[number];

export const PROJECT_CONTROLS_CAPABILITIES = [
  "progress.read",
  "progress.assess",
  "progress.submit_review",
  "progress.review",
  "progress.approve",
  "progress.publish",
  "progress.reject",
  "schedule.read",
  "schedule.assess",
  "schedule.submit_review",
  "schedule.review",
  "schedule.approve",
  "schedule.publish",
  "schedule.reject",
  "change.read",
  "change.assess",
  "change.submit_review",
  "change.review",
  "change.approve",
  "change.publish",
  "change.reject",
  "cost.read",
  "cost.assess",
  "cost.submit_review",
  "cost.review",
  "cost.approve",
  "cost.publish",
  "cost.reject",
  "productivity.read",
  "productivity.assess",
  "productivity.submit_review",
  "productivity.review",
  "productivity.approve",
  "productivity.publish",
  "productivity.reject",
  "forecast.read",
  "forecast.assess",
  "forecast.submit_review",
  "forecast.review",
  "forecast.approve",
  "forecast.publish",
  "forecast.reject",
  "decision.read",
  "decision.assess",
  "decision.submit_review",
  "decision.review",
  "decision.approve",
  "decision.publish",
  "decision.reject",
  "scenario.read",
  "scenario.assess",
  "scenario.submit_review",
  "scenario.review",
  "scenario.approve",
  "scenario.publish",
  "scenario.reject",
  "risk_opportunity.read",
  "risk_opportunity.assess",
  "risk_opportunity.submit_review",
  "risk_opportunity.review",
  "risk_opportunity.approve",
  "risk_opportunity.publish",
  "risk_opportunity.reject",
  "assurance.read",
  "assurance.assess",
  "assurance.submit_review",
  "assurance.review",
  "assurance.approve",
  "assurance.publish",
  "assurance.reject",
  "explainability.read",
  "explainability.assess",
  "explainability.submit_review",
  "explainability.review",
  "explainability.approve",
  "explainability.publish",
  "explainability.reject",
  "organizational_learning.read",
  "organizational_learning.assess",
  "organizational_learning.submit_review",
  "organizational_learning.review",
  "organizational_learning.approve",
  "organizational_learning.publish",
  "organizational_learning.reject",
  "profile.read",
  "profile.compose",
  "snapshot.read",
  "snapshot.create",
] as const;

export type ProjectControlsCapability = (typeof PROJECT_CONTROLS_CAPABILITIES)[number];

export const SELF_APPROVE_FORBIDDEN_CAPABILITIES: readonly ProjectControlsCapability[] = [
  "progress.approve",
  "progress.publish",
  "schedule.approve",
  "schedule.publish",
  "change.approve",
  "change.publish",
  "cost.approve",
  "cost.publish",
  "productivity.approve",
  "productivity.publish",
  "forecast.approve",
  "forecast.publish",
  "decision.approve",
  "decision.publish",
  "scenario.approve",
  "scenario.publish",
  "risk_opportunity.approve",
  "risk_opportunity.publish",
  "assurance.approve",
  "assurance.publish",
  "explainability.approve",
  "explainability.publish",
  "organizational_learning.approve",
  "organizational_learning.publish",
] as const;

const MATRIX: Record<ProjectControlsRole, readonly ProjectControlsCapability[]> = {
  viewer: [
    "progress.read",
    "schedule.read",
    "change.read",
    "cost.read",
    "productivity.read",
    "forecast.read",
    "decision.read",
    "scenario.read",
    "risk_opportunity.read",
    "assurance.read",
    "explainability.read",
    "profile.read",
    "snapshot.read",
  ],
  project_controls_engineer: [
    "progress.read",
    "progress.assess",
    "progress.submit_review",
    "schedule.read",
    "schedule.assess",
    "schedule.submit_review",
    "change.read",
    "change.assess",
    "change.submit_review",
    "cost.read",
    "cost.assess",
    "cost.submit_review",
    "productivity.read",
    "productivity.assess",
    "productivity.submit_review",
    "forecast.read",
    "forecast.assess",
    "forecast.submit_review",
    "decision.read",
    "decision.assess",
    "decision.submit_review",
    "scenario.read",
    "scenario.assess",
    "scenario.submit_review",
    "risk_opportunity.read",
    "risk_opportunity.assess",
    "risk_opportunity.submit_review",
    "assurance.read",
    "explainability.read",
    "assurance.assess",
    "assurance.submit_review",
    "explainability.assess",
    "explainability.submit_review",
    "organizational_learning.read",
    "organizational_learning.assess",
    "organizational_learning.submit_review",
    "profile.read",
    "profile.compose",
    "snapshot.read",
    "snapshot.create",
  ],
  reviewer: [
    "progress.read",
    "progress.review",
    "progress.reject",
    "schedule.read",
    "schedule.review",
    "schedule.reject",
    "change.read",
    "change.review",
    "change.reject",
    "cost.read",
    "cost.review",
    "cost.reject",
    "productivity.read",
    "productivity.review",
    "productivity.reject",
    "forecast.read",
    "forecast.review",
    "forecast.reject",
    "decision.read",
    "decision.review",
    "decision.reject",
    "scenario.read",
    "scenario.review",
    "scenario.reject",
    "risk_opportunity.read",
    "risk_opportunity.review",
    "risk_opportunity.reject",
    "assurance.read",
    "explainability.read",
    "assurance.review",
    "assurance.reject",
    "explainability.review",
    "explainability.reject",
    "organizational_learning.read",
    "organizational_learning.review",
    "organizational_learning.reject",
    "profile.read",
    "snapshot.read",
  ],
  approver: [
    "progress.read",
    "progress.review",
    "progress.approve",
    "progress.publish",
    "progress.reject",
    "schedule.read",
    "schedule.review",
    "schedule.approve",
    "schedule.publish",
    "schedule.reject",
    "change.read",
    "change.review",
    "change.approve",
    "change.publish",
    "change.reject",
    "cost.read",
    "cost.review",
    "cost.approve",
    "cost.publish",
    "cost.reject",
    "productivity.read",
    "productivity.review",
    "productivity.approve",
    "productivity.publish",
    "productivity.reject",
    "forecast.read",
    "forecast.review",
    "forecast.approve",
    "forecast.publish",
    "forecast.reject",
    "decision.read",
    "decision.review",
    "decision.approve",
    "decision.publish",
    "decision.reject",
    "scenario.read",
    "scenario.review",
    "scenario.approve",
    "scenario.publish",
    "scenario.reject",
    "risk_opportunity.read",
    "risk_opportunity.review",
    "risk_opportunity.approve",
    "risk_opportunity.publish",
    "risk_opportunity.reject",
    "assurance.read",
    "explainability.read",
    "assurance.review",
    "assurance.approve",
    "assurance.publish",
    "explainability.approve",
    "explainability.publish",
    "organizational_learning.read",
    "organizational_learning.review",
    "organizational_learning.approve",
    "organizational_learning.publish",
    "assurance.reject",
    "profile.read",
    "snapshot.read",
  ],
  admin: [...PROJECT_CONTROLS_CAPABILITIES],
};

export const PROJECT_CONTROLS_ROLE_MATRIX = MATRIX;

export function roleHasCapability(
  role: ProjectControlsRole,
  capability: ProjectControlsCapability,
): boolean {
  return MATRIX[role]?.includes(capability) ?? false;
}

export function assertProjectControlsCapability(
  role: ProjectControlsRole | undefined,
  capability: ProjectControlsCapability,
  options: { actorId?: string; assessedBy?: string } = {},
): void {
  if (!role) throw new Error(`project_controls_role_required:${capability}`);
  if (!roleHasCapability(role, capability)) {
    throw new Error(`project_controls_capability_denied:${role}:${capability}`);
  }
  if (
    SELF_APPROVE_FORBIDDEN_CAPABILITIES.includes(capability) &&
    options.actorId &&
    options.assessedBy &&
    options.actorId === options.assessedBy
  ) {
    throw new Error(`project_controls_self_approval_forbidden:${capability}`);
  }
}

/**
 * Reserved capabilities must never appear in the matrix. `change.*` and `cost.*`
 * are implemented *assessment* capability sets; earned value, CPM, float,
 * contingency and financial posting stay forbidden. Forecast intelligence
 * assessment capabilities (forecast.*) are implemented in Phase 11G; the
 * predictive ForecastProvider stays reserved.
 */
export function assertNoReservedCapabilities(): { ok: true } {
  const forbidden = /^(earned_value|cpm|float|contingency|posting)/;
  for (const capability of PROJECT_CONTROLS_CAPABILITIES) {
    if (forbidden.test(capability)) {
      throw new Error(`reserved_capability_must_not_be_granted:${capability}`);
    }
  }
  return { ok: true };
}
