import type { EuCompressionMethodRecord } from "@rtb/types";

export const EU_COMPRESSION_IMPLEMENTATION_VERSION = "eu-compression-1.0.0" as const;
export const EU_COMPRESSION_TOOL_REF = "EOS_EU_STEEL_COMPRESSION" as const;

const MECHANICS_SQUASH = "established-mechanics-nominal-squash-load-equals-yield-stress-times-gross-area";
const MECHANICS_EULER = "established-mechanics-euler-elastic-buckling-pcr-pi2-ei-over-le2";

export const EU_COMPRESSION_SQUASH_YIELD_MECHANICS_RULE: EuCompressionMethodRecord = {
  ruleId: "EU-COMPRESSION-SQUASH-YIELD-MECHANICS-V1",
  methodId: "EU_COMPRESSION_SQUASH_YIELD_MECHANICS",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_SQUASH,
  calculationPurpose: "nominal squash load as a mechanics reference, not EN 1993 member compression resistance",
  applicability: "steel compression members with explicit governed fy and gross area",
  requiredInputs: ["material.yieldStrength", "section.area"],
  outputType: "MECHANICS_REFERENCE_SQUASH",
  units: "N",
  implementationVersion: EU_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["EU-COMPRESSION-BM-SQUASH-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "eu-compression-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "NO_ANNEX_DEPENDENCY",
  ruleRequiresNdp: false,
  axis: "SQUASH",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const EU_COMPRESSION_EULER_MAJOR_MECHANICS_RULE: EuCompressionMethodRecord = {
  ruleId: "EU-COMPRESSION-EULER-MAJOR-MECHANICS-V1",
  methodId: "EU_COMPRESSION_EULER_MAJOR_MECHANICS",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_EULER,
  calculationPurpose: "Euler elastic buckling load about the major axis as a mechanics reference",
  applicability: "prismatic members with explicit E, Iyy, and governed major-axis effective length",
  requiredInputs: ["material.elasticModulus", "section.Iyy", "stability.effectiveLengthMajorM"],
  outputType: "MECHANICS_REFERENCE_EULER",
  units: "N",
  implementationVersion: EU_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["EU-COMPRESSION-BM-EULER-MAJOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "eu-compression-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "NO_ANNEX_DEPENDENCY",
  ruleRequiresNdp: false,
  axis: "MAJOR_AXIS",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const EU_COMPRESSION_EULER_MINOR_MECHANICS_RULE: EuCompressionMethodRecord = {
  ruleId: "EU-COMPRESSION-EULER-MINOR-MECHANICS-V1",
  methodId: "EU_COMPRESSION_EULER_MINOR_MECHANICS",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_EULER,
  calculationPurpose: "Euler elastic buckling load about the minor axis as a mechanics reference",
  applicability: "prismatic members with explicit E, Izz, and governed minor-axis effective length",
  requiredInputs: ["material.elasticModulus", "section.Izz", "stability.effectiveLengthMinorM"],
  outputType: "MECHANICS_REFERENCE_EULER",
  units: "N",
  implementationVersion: EU_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["EU-COMPRESSION-BM-EULER-MINOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "eu-compression-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "NO_ANNEX_DEPENDENCY",
  ruleRequiresNdp: false,
  axis: "MINOR_AXIS",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const EU_COMPRESSION_MEMBER_CAPACITY_CODE_PROFILE_RULE: EuCompressionMethodRecord = {
  ruleId: "EU-COMPRESSION-MEMBER-CAPACITY-CODE-PROFILE-V1",
  methodId: "EU_COMPRESSION_MEMBER_CAPACITY_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-member-compression-resistance-validation-required",
  calculationPurpose: "Eurocode-profile member compression resistance Nb,Rd",
  applicability: "not implemented; requires governed classification, buckling curve, reduction factor, partial factor, edition, and National Annex/NDP",
  requiredInputs: [
    "material.yieldStrength",
    "section.area",
    "ndp.partial-factor",
    "classification",
    "buckling-curve",
  ],
  outputType: "EUROCODE_PROFILE_MEMBER_CAPACITY",
  units: "N",
  implementationVersion: EU_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_MEMBER_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: ["partial-factor"],
  annexDependency: "NDP_REQUIRED",
  ruleRequiresNdp: true,
  axis: "SQUASH",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "FRAMEWORK_ONLY",
};

export const EU_BUCKLING_CURVE_SELECTION_CODE_PROFILE_RULE: EuCompressionMethodRecord = {
  ruleId: "EU-BUCKLING-CURVE-SELECTION-CODE-PROFILE-V1",
  methodId: "EU_BUCKLING_CURVE_SELECTION_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-buckling-curve-selection-validation-required",
  calculationPurpose: "Eurocode-profile buckling-curve selection",
  applicability: "not implemented; curve coefficients and selection rules are unvalidated",
  requiredInputs: ["sectionFamily", "axis", "fabricationContext", "materialContext", "standardPart", "edition", "nationalAnnex"],
  outputType: "EUROCODE_PROFILE_BUCKLING_CURVE",
  units: "1",
  implementationVersion: EU_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_MEMBER_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "ANNEX_OPTIONAL",
  ruleRequiresNdp: false,
  axis: "BUCKLING_CURVE",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "FRAMEWORK_ONLY",
};

export const EU_SECTION_CLASSIFICATION_CODE_PROFILE_RULE: EuCompressionMethodRecord = {
  ruleId: "EU-SECTION-CLASSIFICATION-CODE-PROFILE-V1",
  methodId: "EU_SECTION_CLASSIFICATION_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-section-classification-validation-required",
  calculationPurpose: "Eurocode-profile section classification for compression",
  applicability: "not implemented; classification limits are unvalidated",
  requiredInputs: ["section geometry", "material.yieldStrength", "standardPart", "edition"],
  outputType: "EUROCODE_PROFILE_SECTION_CLASSIFICATION",
  units: "1",
  implementationVersion: EU_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_MEMBER_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "ANNEX_OPTIONAL",
  ruleRequiresNdp: false,
  axis: "CLASSIFICATION",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "VALIDATION_REQUIRED",
};

export const EU_TORSIONAL_BUCKLING_CODE_PROFILE_RULE: EuCompressionMethodRecord = {
  ruleId: "EU-TORSIONAL-BUCKLING-CODE-PROFILE-V1",
  methodId: "EU_TORSIONAL_BUCKLING_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-torsional-buckling-not-implemented",
  calculationPurpose: "represent torsional buckling as an extensible mode without a numerical check",
  applicability: "architecture only; numerical check not implemented",
  requiredInputs: ["section.torsionConstant", "section.warpingConstant", "stability"],
  outputType: "EUROCODE_PROFILE_TORSIONAL",
  units: "N",
  implementationVersion: EU_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_MEMBER_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: ["partial-factor"],
  annexDependency: "NDP_REQUIRED",
  ruleRequiresNdp: true,
  axis: "TORSIONAL",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "NOT_IMPLEMENTED",
};

export const EU_FLEXURAL_TORSIONAL_BUCKLING_CODE_PROFILE_RULE: EuCompressionMethodRecord = {
  ruleId: "EU-FLEXURAL-TORSIONAL-BUCKLING-CODE-PROFILE-V1",
  methodId: "EU_FLEXURAL_TORSIONAL_BUCKLING_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-flexural-torsional-buckling-not-implemented",
  calculationPurpose: "represent flexural-torsional buckling as an extensible mode without a numerical check",
  applicability: "architecture only; numerical check not implemented",
  requiredInputs: ["section.Iyy", "section.Izz", "section.torsionConstant", "section.warpingConstant"],
  outputType: "EUROCODE_PROFILE_FLEXURAL_TORSIONAL",
  units: "N",
  implementationVersion: EU_COMPRESSION_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-compression-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_MEMBER_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: ["partial-factor"],
  annexDependency: "NDP_REQUIRED",
  ruleRequiresNdp: true,
  axis: "FLEXURAL_TORSIONAL",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "NOT_IMPLEMENTED",
};

export const EU_COMPRESSION_METHOD_REGISTRY: readonly EuCompressionMethodRecord[] = [
  EU_COMPRESSION_SQUASH_YIELD_MECHANICS_RULE,
  EU_COMPRESSION_EULER_MAJOR_MECHANICS_RULE,
  EU_COMPRESSION_EULER_MINOR_MECHANICS_RULE,
  EU_COMPRESSION_MEMBER_CAPACITY_CODE_PROFILE_RULE,
  EU_BUCKLING_CURVE_SELECTION_CODE_PROFILE_RULE,
  EU_SECTION_CLASSIFICATION_CODE_PROFILE_RULE,
  EU_TORSIONAL_BUCKLING_CODE_PROFILE_RULE,
  EU_FLEXURAL_TORSIONAL_BUCKLING_CODE_PROFILE_RULE,
];

export const IMPLEMENTED_EU_COMPRESSION_METHODS = [
  EU_COMPRESSION_SQUASH_YIELD_MECHANICS_RULE.methodId,
  EU_COMPRESSION_EULER_MAJOR_MECHANICS_RULE.methodId,
  EU_COMPRESSION_EULER_MINOR_MECHANICS_RULE.methodId,
] as const;

export const FRAMEWORK_ONLY_EU_COMPRESSION_METHODS = [
  EU_COMPRESSION_MEMBER_CAPACITY_CODE_PROFILE_RULE.methodId,
  EU_BUCKLING_CURVE_SELECTION_CODE_PROFILE_RULE.methodId,
  EU_SECTION_CLASSIFICATION_CODE_PROFILE_RULE.methodId,
  EU_TORSIONAL_BUCKLING_CODE_PROFILE_RULE.methodId,
  EU_FLEXURAL_TORSIONAL_BUCKLING_CODE_PROFILE_RULE.methodId,
] as const;
