import {
  AI_CONFORMANCE_AUTHORITY,
  AI_CONSTITUTIVE_ASSISTANCE_ADVISORY_ONLY,
  AI_CONSTITUTIVE_PARAMETER_AUTHORITY,
  AI_CONSTITUTIVE_PROFILE_AUTHORITY,
  AI_CONSTITUTIVE_SOURCE_CONFLICT_AUTHORITY,
  AI_ENGINEERING_APPROVAL,
  AI_NDP_AUTHORITY,
  CONCRETE_COMPRESSION_RESPONSE_PARAMETER_GUESSED,
  CONCRETE_STRAIN_VALUE_GUESSED,
  LLM_CONSTITUTIVE_MEMORY_ONLY_RULE_ALLOWED,
  LLM_CONSTITUTIVE_NUMERICAL_AUTHORITY,
  LLM_MEMORY_ONLY_RULE_ALLOWED,
  REINFORCEMENT_RESPONSE_PARAMETER_GUESSED,
} from "@rtb/types";

export function assertEuC1cConstitutiveAiBoundary(): void {
  if (!AI_CONSTITUTIVE_ASSISTANCE_ADVISORY_ONLY) throw new Error("constitutive AI assistance must remain advisory");
  if (LLM_CONSTITUTIVE_NUMERICAL_AUTHORITY || LLM_MEMORY_ONLY_RULE_ALLOWED || LLM_CONSTITUTIVE_MEMORY_ONLY_RULE_ALLOWED) {
    throw new Error("LLM must not originate constitutive numerical rules");
  }
  if (
    AI_CONSTITUTIVE_PARAMETER_AUTHORITY ||
    AI_CONSTITUTIVE_SOURCE_CONFLICT_AUTHORITY ||
    AI_CONSTITUTIVE_PROFILE_AUTHORITY ||
    AI_NDP_AUTHORITY ||
    AI_CONFORMANCE_AUTHORITY ||
    AI_ENGINEERING_APPROVAL
  ) {
    throw new Error("AI must not hold constitutive parameter, conflict, profile, NDP, conformance, or approval authority");
  }
  if (CONCRETE_COMPRESSION_RESPONSE_PARAMETER_GUESSED || CONCRETE_STRAIN_VALUE_GUESSED || REINFORCEMENT_RESPONSE_PARAMETER_GUESSED) {
    throw new Error("constitutive parameters must not be guessed");
  }
}
