import type {
  BusinessCustomerContactIngestInput,
  BusinessCustomerFactIngestInput,
  BusinessCustomerIngestInput,
} from "@rtb/types";

export const CUSTOMER_DEMO_FIXTURE = "bos-5-customer-intelligence";

export const CUSTOMER_DEMO_CUSTOMERS: BusinessCustomerIngestInput[] = [
  {
    organisationName: "Northbound Civils",
    tradingName: "Northbound",
    website: "https://northbound.example",
    domain: "northbound.example",
    industry: "civil",
    geography: "AU",
    customerStatus: "active",
    relationshipOwner: "Owner",
    acquiredAt: "2026-06-15",
    sourceType: "demo",
    sourceRef: "bos-5-demo-customer-northbound",
    isDemo: true,
    provenance: { fixture: CUSTOMER_DEMO_FIXTURE, convertedFrom: "bos-3-demo-lead-northbound" },
  },
  {
    organisationName: "Harbour Inspection Co",
    domain: "harbour.example",
    industry: "inspection",
    geography: "AU",
    customerStatus: "active",
    relationshipOwner: "Owner",
    acquiredAt: "2026-07-10",
    sourceType: "demo",
    sourceRef: "bos-5-demo-customer-harbour",
    isDemo: true,
    provenance: { fixture: CUSTOMER_DEMO_FIXTURE, revenueWithoutCost: true },
  },
  {
    organisationName: "Metro Interchange Authority",
    domain: "metro.example",
    industry: "infrastructure",
    geography: "AU",
    customerStatus: "active",
    relationshipOwner: "Owner",
    acquiredAt: "2026-05-01",
    sourceType: "demo",
    sourceRef: "bos-5-demo-customer-metro",
    isDemo: true,
    provenance: { fixture: CUSTOMER_DEMO_FIXTURE, highConcentration: true },
  },
  {
    organisationName: "Quiet Workshop Pty",
    industry: "inspection",
    geography: "AU",
    customerStatus: "active",
    sourceType: "demo",
    sourceRef: "bos-5-demo-customer-quiet",
    isDemo: true,
    provenance: { fixture: CUSTOMER_DEMO_FIXTURE, noContact: true, noFinancialData: true },
  },
  {
    organisationName: "Former Coastal Co",
    customerStatus: "archived",
    sourceType: "demo",
    sourceRef: "bos-5-demo-customer-archived",
    isDemo: true,
    provenance: { fixture: CUSTOMER_DEMO_FIXTURE, archived: true },
  },
];

export const CUSTOMER_DEMO_CONTACTS: Array<BusinessCustomerContactIngestInput & { customerSourceRef: string }> = [
  {
    customerSourceRef: "bos-5-demo-customer-harbour",
    customerId: "lookup",
    name: "Alex Rivera",
    role: "Operations manager",
    businessEmail: "ops@harbour.example",
    relationshipType: "commercial",
    primary: true,
    sourceType: "demo",
    sourceRef: "bos-5-demo-contact-harbour",
    isDemo: true,
    provenance: { fixture: CUSTOMER_DEMO_FIXTURE, lawfullySourced: true },
  },
  {
    customerSourceRef: "bos-5-demo-customer-northbound",
    customerId: "lookup",
    name: "Suppressed listing",
    role: "Unknown",
    suppressed: true,
    primary: false,
    sourceType: "demo",
    sourceRef: "bos-5-demo-contact-suppressed",
    isDemo: true,
    provenance: { fixture: CUSTOMER_DEMO_FIXTURE, suppressed: true },
  },
];

export const CUSTOMER_DEMO_FACTS: Array<BusinessCustomerFactIngestInput & { customerSourceRef: string }> = [
  {
    customerSourceRef: "bos-5-demo-customer-northbound",
    customerId: "lookup",
    periodStart: "2026-04-01",
    periodEnd: "2026-06-30",
    revenueMinor: "70000000",
    directCostMinor: "52000000",
    receivableOutstandingMinor: "8000000",
    receivableOverdueMinor: "500000",
    currency: "AUD",
    sourceType: "demo",
    sourceRef: "bos-5-demo-fact-northbound-q4",
    isDemo: true,
  },
  {
    customerSourceRef: "bos-5-demo-customer-northbound",
    customerId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    revenueMinor: "80000000",
    directCostMinor: "62000000",
    receivableOutstandingMinor: "9000000",
    receivableOverdueMinor: "400000",
    ageingCurrentMinor: "5000000",
    ageing130Minor: "3600000",
    ageing3160Minor: "400000",
    currency: "AUD",
    dueDate: "2026-08-01",
    paidDate: "2026-08-10",
    sourceType: "demo",
    sourceRef: "bos-5-demo-fact-northbound-q1",
    isDemo: true,
  },
  {
    customerSourceRef: "bos-5-demo-customer-harbour",
    customerId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    revenueMinor: "25000000",
    receivableOutstandingMinor: "12000000",
    receivableOverdueMinor: "6000000",
    currency: "AUD",
    sourceType: "demo",
    sourceRef: "bos-5-demo-fact-harbour",
    isDemo: true,
    provenance: { missingCost: true, overdueHealthyRelationship: true },
  },
  {
    customerSourceRef: "bos-5-demo-customer-metro",
    customerId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-09-30",
    revenueMinor: "150000000",
    directCostMinor: "120000000",
    currency: "AUD",
    sourceType: "demo",
    sourceRef: "bos-5-demo-fact-metro",
    isDemo: true,
    provenance: { highConcentration: true },
  },
];
