import type {
  BusinessRevenueDraftIngestInput,
  BusinessRevenueEngagementIngestInput,
  BusinessRevenuePricingIngestInput,
  BusinessRevenueProposalIngestInput,
  BusinessRevenueRequirementIngestInput,
} from "@rtb/types";

export const REVENUE_DEMO_FIXTURE = "bos-4-revenue-execution";

export const REVENUE_DEMO_ENGAGEMENTS: BusinessRevenueEngagementIngestInput[] = [
  {
    opportunityId: "lookup:bos-3-demo-opp-northbound",
    objective: "Prepare a supervised inspection proposal for Northbound Civils.",
    stakeholderSummary: "Public infrastructure owner; no personal outreach consent assumed.",
    valueProposition: "Condition survey of two river crossings using existing inspection capability.",
    keyNeeds: "Documented tender scope and site access windows.",
    proposedApproach: "Internal research brief, then human-reviewed proposal draft.",
    nextAction: "Complete pricing review",
    owner: "Owner",
    dueAt: "2026-09-01T00:00:00.000Z",
    status: "active",
    sourceType: "demo",
    sourceRef: "bos-4-demo-eng-northbound",
    isDemo: true,
    provenance: { fixture: REVENUE_DEMO_FIXTURE, live: false },
  },
];

export const REVENUE_DEMO_DRAFTS: BusinessRevenueDraftIngestInput[] = [
  {
    opportunityId: "lookup:bos-3-demo-opp-northbound",
    type: "internal_note",
    subject: "Internal research brief — Northbound",
    body: "Organisation-only context from Growth Intelligence. Do not send. Contact data is optional and not required.",
    purpose: "Internal research summary for human review.",
    generatedBy: "deterministic_rule",
    approvalStatus: "draft",
    sourceType: "demo",
    sourceRef: "bos-4-demo-draft-northbound",
    isDemo: true,
    evidenceRefs: [
      {
        sourceType: "growth_opportunity",
        sourceRef: "bos-3-demo-opp-northbound",
        title: "Northbound opportunity",
        excerpt: "Qualified opportunity from BOS-3 demo fixtures.",
      },
    ],
    provenance: { fixture: REVENUE_DEMO_FIXTURE, live: false, externalSend: false },
  },
];

export const REVENUE_DEMO_PROPOSALS: BusinessRevenueProposalIngestInput[] = [
  {
    opportunityId: "lookup:bos-3-demo-opp-northbound",
    proposalNumber: "BOS4-NB-001",
    title: "Northbound bridge inspection — internal draft",
    version: 1,
    status: "pricing_review",
    scopeSummary: "Two river crossings; visual and limited NDT.",
    customerRequirements: "Public tender specification (supplied).",
    assumptions: "Access during daylight; no diving.",
    exclusions: "Design, repair, or traffic management.",
    deliverables: "Condition report and photographic register.",
    commercialTermsSummary: "Fixed price subject to human approval.",
    proposedPriceMinor: "80000000",
    estimatedCostMinor: "62000000",
    currency: "AUD",
    scale: 2,
    targetMarginBps: "2200",
    owner: "Owner",
    sourceType: "demo",
    sourceRef: "bos-4-demo-proposal-northbound-v1",
    isDemo: true,
    evidenceRefs: [
      {
        sourceType: "growth_opportunity",
        sourceRef: "bos-3-demo-opp-northbound",
        title: "Opportunity evidence",
        excerpt: "Estimated value and strategic fit from Growth Intelligence.",
      },
    ],
    provenance: { fixture: REVENUE_DEMO_FIXTURE, live: false, generated: "deterministic_rule" },
  },
  {
    opportunityId: "lookup:bos-3-demo-opp-harbour",
    proposalNumber: "BOS4-HB-001",
    title: "Harbour survey — superseded draft",
    version: 1,
    status: "superseded",
    proposedPriceMinor: "25000000",
    estimatedCostMinor: "21000000",
    currency: "AUD",
    scale: 2,
    sourceType: "demo",
    sourceRef: "bos-4-demo-proposal-harbour-v1",
    isDemo: true,
    provenance: { fixture: REVENUE_DEMO_FIXTURE, live: false, superseded: true },
  },
];

export const REVENUE_DEMO_REQUIREMENTS: BusinessRevenueRequirementIngestInput[] = [
  {
    proposalId: "lookup:bos-4-demo-proposal-northbound-v1",
    requirement: "Provide inspection methodology aligned to the tender specification.",
    sourceReference: "tender-spec-s4",
    mandatory: true,
    response: "Visual plus limited NDT as documented in scope summary.",
    status: "reviewed",
    complianceStatus: "satisfied",
    generatedBy: "user",
    sourceType: "demo",
    sourceRef: "bos-4-demo-req-method",
    isDemo: true,
    evidenceRefs: [
      {
        sourceType: "proposal",
        sourceRef: "bos-4-demo-proposal-northbound-v1",
        title: "Scope summary",
        excerpt: "Visual and limited NDT.",
      },
    ],
    provenance: { fixture: REVENUE_DEMO_FIXTURE },
  },
  {
    proposalId: "lookup:bos-4-demo-proposal-northbound-v1",
    requirement: "Named certified diving supervisor.",
    sourceReference: "tender-spec-s9",
    mandatory: true,
    status: "open",
    complianceStatus: "unsatisfied",
    generatedBy: "deterministic_rule",
    sourceType: "demo",
    sourceRef: "bos-4-demo-req-diving",
    isDemo: true,
    provenance: { fixture: REVENUE_DEMO_FIXTURE, missingEvidence: true },
  },
];

export const REVENUE_DEMO_PRICING: BusinessRevenuePricingIngestInput[] = [
  {
    opportunityId: "lookup:bos-3-demo-opp-northbound",
    proposalId: "lookup:bos-4-demo-proposal-northbound-v1",
    scenarioName: "baseline",
    assumptions: "No discount. Direct cost from internal estimate.",
    revenueMinor: "80000000",
    estimatedDirectCostMinor: "62000000",
    currency: "AUD",
    scale: 2,
    sourceType: "demo",
    sourceRef: "bos-4-demo-price-baseline",
    isDemo: true,
    provenance: { fixture: REVENUE_DEMO_FIXTURE },
  },
  {
    opportunityId: "lookup:bos-3-demo-opp-northbound",
    proposalId: "lookup:bos-4-demo-proposal-northbound-v1",
    scenarioName: "discounted",
    assumptions: "15% discount requires approval.",
    revenueMinor: "80000000",
    estimatedDirectCostMinor: "62000000",
    discountBps: "1500",
    currency: "AUD",
    scale: 2,
    sourceType: "demo",
    sourceRef: "bos-4-demo-price-discount",
    isDemo: true,
    provenance: { fixture: REVENUE_DEMO_FIXTURE, discountBeyondAuthority: true },
  },
  {
    opportunityId: "lookup:bos-3-demo-opp-harbour",
    scenarioName: "zero-price",
    revenueMinor: "0",
    estimatedDirectCostMinor: "21000000",
    currency: "AUD",
    scale: 2,
    sourceType: "demo",
    sourceRef: "bos-4-demo-price-zero",
    isDemo: true,
    provenance: { fixture: REVENUE_DEMO_FIXTURE, zeroPrice: true },
  },
  {
    opportunityId: "lookup:bos-3-demo-opp-harbour",
    scenarioName: "missing-cost",
    revenueMinor: "25000000",
    currency: "AUD",
    scale: 2,
    sourceType: "demo",
    sourceRef: "bos-4-demo-price-missing-cost",
    isDemo: true,
    provenance: { fixture: REVENUE_DEMO_FIXTURE, missingDirectCost: true },
  },
  {
    opportunityId: "lookup:bos-3-demo-opp-metro",
    scenarioName: "negative-margin",
    revenueMinor: "150000000",
    estimatedDirectCostMinor: "160000000",
    currency: "AUD",
    scale: 2,
    sourceType: "demo",
    sourceRef: "bos-4-demo-price-negative",
    isDemo: true,
    provenance: { fixture: REVENUE_DEMO_FIXTURE, negativeMargin: true },
  },
];
