export const PHASE_9K_INSPECTION_V1_GA_GATES = [
  ["A", "Repository identity"],
  ["B", "Build identity"],
  ["C", "Version identity"],
  ["D", "Schema identity"],
  ["E", "PI v1 integrity"],
  ["F", "Prior Inspection phases"],
  ["G", "Module manifest"],
  ["H", "Public contracts"],
  ["I", "Capability Registry"],
  ["J", "Service Registry"],
  ["K", "Pack Registry"],
  ["L", "Registry/manifest drift"],
  ["M", "Commercial entitlement"],
  ["N", "Cross-module contracts"],
  ["O", "Provider assurance"],
  ["P", "AI Vision governance"],
  ["Q", "Human authority"],
  ["R", "Immutable evidence"],
  ["S", "Offline continuity"],
  ["T", "Mobile continuity"],
  ["U", "Idempotency"],
  ["V", "Event integrity"],
  ["W", "Tenant isolation"],
  ["X", "Workspace isolation"],
  ["Y", "Revocation"],
  ["Z", "Operations"],
  ["AA", "Browser E2E"],
  ["AB", "Accessibility"],
  ["AC", "Responsive"],
  ["AD", "Performance"],
  ["AE", "Secret exposure"],
  ["AF", "Artifact identity"],
  ["AG", "GA release eligibility"],
] as const;

export type Phase9kGateId = (typeof PHASE_9K_INSPECTION_V1_GA_GATES)[number][0];
