/**
 * Phase 10F certification gates A–AZ (foundational time series / trend / degradation).
 */
export const PHASE_10F_ASSET_INTELLIGENCE_TIMESERIES_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 10A regression"],
  ["C", "Phase 10B regression"],
  ["D", "Phase 10B.1 persistence regression"],
  ["E", "Phase 10C regression"],
  ["F", "Phase 10D regression"],
  ["G", "Phase 10E regression"],
  ["H", "PI v1 integrity"],
  ["I", "II v1 integrity"],
  ["J", "Ownership lock"],
  ["K", "Engineering Time Series model"],
  ["L", "Change Detection Engine"],
  ["M", "Trend Confidence"],
  ["N", "Trend Intelligence"],
  ["O", "Governed Degradation Analysis"],
  ["P", "Failure/timeseries/degradation boundary"],
  ["Q", "Evidence Confidence integration"],
  ["R", "Abstention on inadequate trend confidence"],
  ["S", "Governed degradation review"],
  ["T", "Hosted migration"],
  ["U", "Hosted timeseries persistence"],
  ["V", "State versioning"],
  ["W", "Snapshot integration"],
  ["X", "Timeline"],
  ["Y", "Health composition boundary"],
  ["Z", "No predictive ML"],
  ["AA", "II public-contract boundary"],
  ["AB", "AI governance"],
  ["AC", "Real JWT role matrix"],
  ["AD", "Tenant isolation"],
  ["AE", "Workspace isolation"],
  ["AF", "IDOR"],
  ["AG", "Idempotency"],
  ["AH", "Concurrency"],
  ["AI", "Event/outbox integrity"],
  ["AJ", "HTTP contracts"],
  ["AK", "Health/observability"],
  ["AL", "Performance"],
  ["AM", "No memory production"],
  ["AN", "No PoF/RUL/accuracy claims"],
  ["AO", "Secret exposure"],
  ["AP", "Artifact identity"],
  ["AQ", "Phase 10G readiness"],
] as const;

export type Phase10fGateId = (typeof PHASE_10F_ASSET_INTELLIGENCE_TIMESERIES_GATES)[number][0];
