import type { IsolationProbeDefinition } from "../isolation-contracts";

function probe(
  partial: Omit<
    IsolationProbeDefinition,
    "productionSafe" | "mutatesAuthorization" | "mutatesRls" | "status"
  > & { status?: IsolationProbeDefinition["status"] },
): IsolationProbeDefinition {
  return {
    ...partial,
    status: partial.status ?? "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
  };
}

/** Versioned built-in probes — harness keys only, no unrestricted code. */
export const SEED_ISOLATION_PROBES: IsolationProbeDefinition[] = [
  probe({
    probeId: "iso-db-cross-tenant-deny",
    name: "Database RLS cross-tenant deny",
    version: "1.0.0",
    targetPlane: "DATABASE",
    scope: "platform",
    requiredActorContexts: ["tenant_a_user"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "critical",
    harnessKey: "database.cross_tenant_deny",
  }),
  probe({
    probeId: "iso-db-cross-workspace-deny",
    name: "Database RLS cross-workspace deny",
    version: "1.0.0",
    targetPlane: "DATABASE",
    scope: "platform",
    requiredActorContexts: ["workspace_a_user"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "critical",
    harnessKey: "database.cross_workspace_deny",
  }),
  probe({
    probeId: "iso-db-same-tenant-allow",
    name: "Database same-tenant authorized allow",
    version: "1.0.0",
    targetPlane: "DATABASE",
    scope: "platform",
    requiredActorContexts: ["tenant_a_user"],
    expectedOutcome: "allow",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "high",
    harnessKey: "database.same_tenant_allow",
  }),
  probe({
    probeId: "iso-api-idor-deny",
    name: "API IDOR foreign tenant deny",
    version: "1.0.0",
    targetPlane: "API",
    scope: "platform",
    requiredActorContexts: ["tenant_a_user"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only_no_body_leak",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "critical",
    harnessKey: "api.idor_foreign_tenant",
  }),
  probe({
    probeId: "iso-api-role-insufficient",
    name: "API privileged endpoint non-privileged deny",
    version: "1.0.0",
    targetPlane: "API",
    scope: "platform",
    requiredActorContexts: ["non_privileged_user"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-S01"],
    evidencePolicy: "refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "high",
    harnessKey: "api.role_insufficient",
  }),
  probe({
    probeId: "iso-files-cross-tenant-deny",
    name: "Platform Files cross-tenant deny",
    version: "1.0.0",
    targetPlane: "FILES",
    scope: "platform",
    requiredActorContexts: ["tenant_a_user"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_status_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "critical",
    harnessKey: "files.cross_tenant_deny",
  }),
  probe({
    probeId: "iso-search-cross-tenant",
    name: "Search cross-tenant filter",
    version: "1.0.0",
    targetPlane: "SEARCH",
    scope: "platform",
    requiredActorContexts: ["tenant_a_user"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "critical",
    harnessKey: "search.cross_tenant_filter",
  }),
  probe({
    probeId: "iso-kg-cross-tenant",
    name: "Knowledge Graph cross-tenant deny",
    version: "1.0.0",
    targetPlane: "KNOWLEDGE_GRAPH",
    scope: "platform",
    requiredActorContexts: ["tenant_a_user"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "critical",
    harnessKey: "kg.cross_tenant_deny",
  }),
  probe({
    probeId: "iso-ai-context-cross-tenant",
    name: "AI context cross-tenant deny",
    version: "1.0.0",
    targetPlane: "AI_CONTEXT",
    scope: "platform",
    requiredActorContexts: ["tenant_a_user"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-S05"],
    evidencePolicy: "context_refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "critical",
    harnessKey: "ai.cross_tenant_context_deny",
  }),
  probe({
    probeId: "iso-job-tenant-context",
    name: "Background job tenant context preserved",
    version: "1.0.0",
    targetPlane: "BACKGROUND_JOB",
    scope: "platform",
    requiredActorContexts: ["job_worker"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "high",
    harnessKey: "job.foreign_object_deny",
  }),
  probe({
    probeId: "iso-event-tenant-scope",
    name: "Event Bus tenant scoping",
    version: "1.0.0",
    targetPlane: "EVENT",
    scope: "platform",
    requiredActorContexts: ["event_consumer"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "high",
    harnessKey: "event.cross_tenant_deny",
  }),
  probe({
    probeId: "iso-eeh-workspace-isolation",
    name: "Execution Host workspace isolation",
    version: "1.0.0",
    targetPlane: "EXECUTION_HOST",
    scope: "platform",
    requiredActorContexts: ["execution_host"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "critical",
    harnessKey: "execution_host.cross_job_deny",
  }),
  probe({
    probeId: "iso-solver-workspace-isolation",
    name: "Solver workspace isolation",
    version: "1.0.0",
    targetPlane: "SOLVER_WORKSPACE",
    scope: "platform",
    requiredActorContexts: ["solver_job"],
    expectedOutcome: "deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "refs_only_no_commercial_solver",
    freshnessPolicy: "max_age_24h",
    timeoutPolicyMs: 5000,
    riskClassification: "critical",
    harnessKey: "solver.cross_job_deny",
  }),
  probe({
    probeId: "iso-cache-applicability",
    name: "Shared cache isolation applicability",
    version: "1.0.0",
    targetPlane: "CACHE",
    scope: "platform",
    requiredActorContexts: ["platform"],
    expectedOutcome: "not_applicable",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    evidencePolicy: "applicability_only",
    freshnessPolicy: "max_age_168h",
    timeoutPolicyMs: 1000,
    riskClassification: "low",
    harnessKey: "cache.not_applicable",
  }),
];
