/**
 * Phase 10K certification gates A–BM (Asset Intelligence V1.0 GA closure).
 * 65 gates: A–Z (26) + AA–AZ (26) + BA–BM (13).
 */
export const PHASE_10K_ASSET_INTELLIGENCE_GA_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 10A regression"],
  ["C", "Phase 10B regression"],
  ["D", "Phase 10B.1 regression"],
  ["E", "Phase 10C regression"],
  ["F", "Phase 10D regression"],
  ["G", "Phase 10E regression"],
  ["H", "Phase 10F regression"],
  ["I", "Phase 10G regression"],
  ["J", "Phase 10H regression"],
  ["K", "Phase 10I regression"],
  ["L", "Phase 10J regression"],
  ["M", "PI v1 integrity"],
  ["N", "II v1 integrity"],
  ["O", "Ownership locks"],
  ["P", "V1.0.0 version freeze"],
  ["Q", "GA status declaration"],
  ["R", "Package version alignment"],
  ["S", "Single authoritative version source"],
  ["T", "Module manifest generator"],
  ["U", "Module manifest snapshot"],
  ["V", "Capability registry freeze"],
  ["W", "Service registry freeze"],
  ["X", "Event contract freeze"],
  ["Y", "Unavailable capability matrix"],
  ["Z", "Module registry drift"],
  ["AA", "Capability matrix document"],
  ["AB", "Public contracts document"],
  ["AC", "Commercial packaging document"],
  ["AD", "Operations runbook"],
  ["AE", "Incident response runbook"],
  ["AF", "Recovery runbook"],
  ["AG", "Rollback runbook"],
  ["AH", "Performance baseline document"],
  ["AI", "Unavailable capabilities document"],
  ["AJ", "Limitations document"],
  ["AK", "Predictive execution unavailable"],
  ["AL", "PoF unavailable"],
  ["AM", "RUL unavailable"],
  ["AN", "Predictive ML disabled"],
  ["AO", "Health contribution locks"],
  ["AP", "Risk/Maintenance/CMMS boundary"],
  ["AQ", "Migration lineage 55–59"],
  ["AR", "No migration rewrite"],
  ["AS", "Hosted persistence"],
  ["AT", "Tenant isolation / RLS"],
  ["AU", "Real JWT matrix"],
  ["AV", "Workspace isolation / IDOR"],
  ["AW", "HTTP contracts"],
  ["AX", "Health/observability"],
  ["AY", "No production memory repository"],
  ["AZ", "Idempotency"],
  ["BA", "Concurrency"],
  ["BB", "Engineering OS module page"],
  ["BC", "GA readiness marker"],
  ["BD", "Unavailable labels in UI"],
  ["BE", "Browser E2E"],
  ["BF", "Accessibility"],
  ["BG", "Responsive viewports"],
  ["BH", "Upgrade certification"],
  ["BI", "Backup/restore certification"],
  ["BJ", "Unit and architecture tests"],
  ["BK", "Secret exposure"],
  ["BL", "Artifact identity"],
  ["BM", "Release tag integrity"],
] as const;

export type Phase10kGateId = (typeof PHASE_10K_ASSET_INTELLIGENCE_GA_GATES)[number][0];

export const PHASE_10K_RELEASE_TAG = "asset-intelligence-v1.0.0" as const;
export const PHASE_10K_GATE_COUNT = PHASE_10K_ASSET_INTELLIGENCE_GA_GATES.length;
