export const PHASE_10A_ASSET_INTELLIGENCE_DISCOVERY_GATES = [
  ["A", "Repository identity"],
  ["B", "PI v1 tag integrity"],
  ["C", "II v1 tag integrity"],
  ["D", "Existing asset inventory"],
  ["E", "Shared-domain ownership"],
  ["F", "Duplicate asset ownership"],
  ["G", "Identity/state separation"],
  ["H", "Multi-hierarchy model"],
  ["I", "Condition model"],
  ["J", "Criticality model"],
  ["K", "Reliability model"],
  ["L", "Risk boundary"],
  ["M", "Failure model"],
  ["N", "Degradation model"],
  ["O", "RUL governance"],
  ["P", "Lifecycle model"],
  ["Q", "II consumption boundary"],
  ["R", "PI relationship"],
  ["S", "Project Controls boundary"],
  ["T", "Digital Twin boundary"],
  ["U", "SHM boundary"],
  ["V", "Maintenance boundary"],
  ["W", "SDK reuse"],
  ["X", "Pack strategy"],
  ["Y", "Knowledge Graph boundary"],
  ["Z", "AI governance"],
  ["AA", "Event contracts"],
  ["AB", "Public contract drafts"],
  ["AC", "Capability drafts"],
  ["AD", "Service drafts"],
  ["AE", "Commercial boundary"],
  ["AF", "Discovery manifest"],
  ["AG", "Package placement"],
  ["AH", "No production Asset Intelligence claim"],
  ["AI", "Secret exposure"],
  ["AJ", "Artifact identity"],
  ["AK", "Phase 10B readiness"],
] as const;

export type Phase10aGateId = (typeof PHASE_10A_ASSET_INTELLIGENCE_DISCOVERY_GATES)[number][0];
