import type {
  EosAiCapabilityRecord,
  EosComplianceMatrixCell,
  EosDisciplineGapRow,
  EosEngineeringStandardRecord,
  EosHorizontalModuleInventoryRow,
  EosJurisdictionProfile,
  EosPrivacyPolicyProfile,
  EosRegionalDeploymentPolicy,
} from "@rtb/types";
import {
  EOS_ARCHITECTURE_LAYERS,
  EOS_AUTONOMOUS_ENGINEERING_APPROVAL,
  EOS_COMPLIANCE_CATEGORIES,
  EOS_EU_ONLY_ARCHITECTURE,
  EOS_EU_MARKET_READY,
  EOS_GLOBAL_FIRST_ARCHITECTURE,
  EOS_JURISDICTION_PROFILE_IDS,
  EOS_SECURITY_BASELINE_CONTROLS,
} from "@rtb/types";
import { SURVEILLANCE_PROHIBITIONS } from "../pilot/a14a-profile";

export const EOS_EU_0_PHASE = "EOS-EU-0" as const;

export const EOS_GLOBAL_ARCHITECTURE_PRINCIPLE = {
  layers: EOS_ARCHITECTURE_LAYERS,
  globalFirst: EOS_GLOBAL_FIRST_ARCHITECTURE,
  euOnlyProduct: EOS_EU_ONLY_ARCHITECTURE,
  euMarketReady: EOS_EU_MARKET_READY,
  euHighWaterMarkBaseline: true,
  autonomousEngineeringApproval: EOS_AUTONOMOUS_ENGINEERING_APPROVAL,
} as const;

export const EOS_JURISDICTION_PROFILES: readonly EosJurisdictionProfile[] = [
  {
    jurisdictionId: "global-baseline",
    country: null,
    region: "GLOBAL",
    subJurisdiction: null,
    legalRegime: "tenant-selected",
    privacyRegime: "jurisdiction-profile",
    aiRegime: "jurisdiction-profile",
    cybersecurityRegime: "enterprise-baseline",
    engineeringStandardFamilies: [],
    professionalApprovalRules: "human-authorized-where-required",
    dataResidencyRules: "deployment-policy",
    internationalTransferRules: "deployment-policy",
    retentionRules: "retention-class",
    language: "configurable",
    units: "CONFIGURABLE",
    effectiveFrom: "2026-10-05",
    effectiveTo: null,
    version: "1.0.0",
    authority: "EOS architecture",
    evidenceReference: "EOS-EU-0",
  },
  {
    jurisdictionId: "australia",
    country: "AU",
    region: "APAC",
    subJurisdiction: null,
    legalRegime: "australia",
    privacyRegime: "australia-privacy-profile",
    aiRegime: "australia-ai-profile",
    cybersecurityRegime: "australia-cyber-profile",
    engineeringStandardFamilies: ["AS", "AS-NZS"],
    professionalApprovalRules: "registered-professional-engineer-where-required",
    dataResidencyRules: "preferred-australia-configurable",
    internationalTransferRules: "approval-when-required",
    retentionRules: "project-and-statutory-classes",
    language: "en-AU",
    units: "SI",
    effectiveFrom: "2026-10-05",
    effectiveTo: null,
    version: "1.0.0",
    authority: "EOS architecture",
    evidenceReference: "EOS-EU-0",
  },
  {
    jurisdictionId: "eu-eea",
    country: null,
    region: "EU_EEA",
    subJurisdiction: "member-state-annex",
    legalRegime: "eu-eea",
    privacyRegime: "eu-gdpr-high-water-mark-profile",
    aiRegime: "eu-ai-act-high-water-mark-profile",
    cybersecurityRegime: "nis2-alignment-profile",
    engineeringStandardFamilies: ["EN", "EUROCODE", "NATIONAL_ANNEX"],
    professionalApprovalRules: "competent-person-member-state-rules",
    dataResidencyRules: "eea-preferred-configurable",
    internationalTransferRules: "transfer-mechanism-required",
    retentionRules: "purpose-and-statutory-classes",
    language: "configurable",
    units: "SI",
    effectiveFrom: "2026-10-05",
    effectiveTo: null,
    version: "1.0.0",
    authority: "EOS architecture",
    evidenceReference: "EOS-EU-0",
  },
  {
    jurisdictionId: "united-kingdom",
    country: "GB",
    region: "UK",
    subJurisdiction: null,
    legalRegime: "united-kingdom",
    privacyRegime: "uk-gdpr-profile",
    aiRegime: "uk-ai-profile",
    cybersecurityRegime: "uk-cyber-profile",
    engineeringStandardFamilies: ["BS", "EN", "NATIONAL_ANNEX"],
    professionalApprovalRules: "chartered-or-competent-person-where-required",
    dataResidencyRules: "uk-preferred-configurable",
    internationalTransferRules: "approval-when-required",
    retentionRules: "purpose-and-statutory-classes",
    language: "en-GB",
    units: "SI",
    effectiveFrom: "2026-10-05",
    effectiveTo: null,
    version: "1.0.0",
    authority: "EOS architecture",
    evidenceReference: "EOS-EU-0",
  },
  {
    jurisdictionId: "united-states",
    country: "US",
    region: "AMERICAS",
    subJurisdiction: "state",
    legalRegime: "united-states",
    privacyRegime: "us-state-and-sector-profile",
    aiRegime: "us-ai-profile",
    cybersecurityRegime: "us-cyber-profile",
    engineeringStandardFamilies: ["AISC", "ACI", "ASCE", "API", "NFPA", "IEEE"],
    professionalApprovalRules: "licensed-professional-engineer-where-required",
    dataResidencyRules: "us-preferred-configurable",
    internationalTransferRules: "approval-when-required",
    retentionRules: "project-and-statutory-classes",
    language: "en-US",
    units: "US_CUSTOMARY",
    effectiveFrom: "2026-10-05",
    effectiveTo: null,
    version: "1.0.0",
    authority: "EOS architecture",
    evidenceReference: "EOS-EU-0",
  },
  {
    jurisdictionId: "canada",
    country: "CA",
    region: "AMERICAS",
    subJurisdiction: "province",
    legalRegime: "canada",
    privacyRegime: "canada-privacy-profile",
    aiRegime: "canada-ai-profile",
    cybersecurityRegime: "canada-cyber-profile",
    engineeringStandardFamilies: ["CSA"],
    professionalApprovalRules: "licensed-professional-engineer-where-required",
    dataResidencyRules: "canada-preferred-configurable",
    internationalTransferRules: "approval-when-required",
    retentionRules: "project-and-statutory-classes",
    language: "en-CA",
    units: "SI",
    effectiveFrom: "2026-10-05",
    effectiveTo: null,
    version: "1.0.0",
    authority: "EOS architecture",
    evidenceReference: "EOS-EU-0",
  },
  {
    jurisdictionId: "middle-east",
    country: null,
    region: "MIDDLE_EAST",
    subJurisdiction: "country",
    legalRegime: "middle-east-configurable",
    privacyRegime: "middle-east-privacy-profile",
    aiRegime: "middle-east-ai-profile",
    cybersecurityRegime: "middle-east-cyber-profile",
    engineeringStandardFamilies: ["CONFIGURABLE"],
    professionalApprovalRules: "local-competent-person-where-required",
    dataResidencyRules: "customer-or-country-configurable",
    internationalTransferRules: "approval-when-required",
    retentionRules: "project-and-statutory-classes",
    language: "configurable",
    units: "SI",
    effectiveFrom: "2026-10-05",
    effectiveTo: null,
    version: "1.0.0",
    authority: "EOS architecture",
    evidenceReference: "EOS-EU-0",
  },
  {
    jurisdictionId: "apac-other",
    country: null,
    region: "APAC",
    subJurisdiction: "country",
    legalRegime: "apac-configurable",
    privacyRegime: "apac-privacy-profile",
    aiRegime: "apac-ai-profile",
    cybersecurityRegime: "apac-cyber-profile",
    engineeringStandardFamilies: ["CONFIGURABLE"],
    professionalApprovalRules: "local-competent-person-where-required",
    dataResidencyRules: "customer-or-country-configurable",
    internationalTransferRules: "approval-when-required",
    retentionRules: "project-and-statutory-classes",
    language: "configurable",
    units: "SI",
    effectiveFrom: "2026-10-05",
    effectiveTo: null,
    version: "1.0.0",
    authority: "EOS architecture",
    evidenceReference: "EOS-EU-0",
  },
  {
    jurisdictionId: "other",
    country: null,
    region: "OTHER",
    subJurisdiction: null,
    legalRegime: "tenant-selected",
    privacyRegime: "jurisdiction-profile",
    aiRegime: "jurisdiction-profile",
    cybersecurityRegime: "enterprise-baseline",
    engineeringStandardFamilies: ["CONFIGURABLE"],
    professionalApprovalRules: "human-authorized-where-required",
    dataResidencyRules: "deployment-policy",
    internationalTransferRules: "deployment-policy",
    retentionRules: "retention-class",
    language: "configurable",
    units: "CONFIGURABLE",
    effectiveFrom: "2026-10-05",
    effectiveTo: null,
    version: "1.0.0",
    authority: "EOS architecture",
    evidenceReference: "EOS-EU-0",
  },
];

export const EOS_STANDARD_FAMILY_EXAMPLES: readonly EosEngineeringStandardRecord[] = [
  {
    standardFamily: "AS",
    standardCode: "AS-FAMILY",
    edition: null,
    amendment: null,
    nationalAnnex: null,
    jurisdiction: "australia",
    discipline: null,
    effectiveDate: null,
    supersededDate: null,
    approvalStatus: "REFERENCE",
    sourceReference: "EOS-EU-0 standards framework",
  },
  {
    standardFamily: "EN",
    standardCode: "EUROCODE-FAMILY",
    edition: null,
    amendment: null,
    nationalAnnex: "member-state-annex",
    jurisdiction: "eu-eea",
    discipline: null,
    effectiveDate: null,
    supersededDate: null,
    approvalStatus: "REFERENCE",
    sourceReference: "EOS-EU-0 standards framework",
  },
  {
    standardFamily: "AISC",
    standardCode: "AISC-FAMILY",
    edition: null,
    amendment: null,
    nationalAnnex: null,
    jurisdiction: "united-states",
    discipline: "STRUCTURAL",
    effectiveDate: null,
    supersededDate: null,
    approvalStatus: "REFERENCE",
    sourceReference: "EOS-EU-0 standards framework",
  },
  {
    standardFamily: "CSA",
    standardCode: "CSA-FAMILY",
    edition: null,
    amendment: null,
    nationalAnnex: null,
    jurisdiction: "canada",
    discipline: null,
    effectiveDate: null,
    supersededDate: null,
    approvalStatus: "REFERENCE",
    sourceReference: "EOS-EU-0 standards framework",
  },
];

export const EOS_PRIVACY_POLICY_PROFILES: readonly EosPrivacyPolicyProfile[] = [
  {
    profileId: "engineering-record",
    dataCategory: "engineeringData",
    personalData: false,
    specialCategoryData: false,
    purpose: "governed-engineering-work",
    lawfulBasisProfile: "jurisdiction-selected",
    retentionClass: "project-lifecycle",
    deletionPolicy: "retain-until-class-expires",
    residencyPolicy: "deployment-policy",
    transferPolicy: "deployment-policy",
    accessClass: "tenant-workspace-role",
    auditRequirement: "required",
    dataSubjectRightsApplicability: "JURISDICTION_PROFILE",
  },
  {
    profileId: "identity-account",
    dataCategory: "personalData",
    personalData: true,
    specialCategoryData: false,
    purpose: "authentication-and-authorization",
    lawfulBasisProfile: "jurisdiction-selected",
    retentionClass: "account-lifecycle",
    deletionPolicy: "delete-or-anonymize-on-account-close",
    residencyPolicy: "deployment-policy",
    transferPolicy: "deployment-policy",
    accessClass: "identity-admin",
    auditRequirement: "required",
    dataSubjectRightsApplicability: "ALWAYS_EVALUATE",
  },
];

export const EOS_DEFAULT_REGIONAL_DEPLOYMENT: EosRegionalDeploymentPolicy = {
  preferredRegion: null,
  requiredRegion: null,
  allowedRegions: ["australia", "eu-eea", "united-kingdom", "united-states", "canada", "middle-east", "apac-other", "customer-controlled"],
  prohibitedRegions: [],
  transferPermitted: false,
  transferMechanism: null,
  crossBorderApprovalRequired: true,
};

export const EOS_ORGANIZATIONAL_INTELLIGENCE_BOUNDARY = {
  employeeSurveillanceDefault: "PROHIBITED" as const,
  personalBehaviorProfilingDefault: "PROHIBITED" as const,
  mayLearn: [
    "approved lessons",
    "validated workflows",
    "project outcomes",
    "decision precedents",
    "approved standards",
  ],
  mustNotCreate: [
    "employee surveillance",
    "productivity rankings",
    "hidden behavioral profiles",
    "automated employment decisions",
  ],
  surveillanceFlags: SURVEILLANCE_PROHIBITIONS,
};

export const EOS_SECURITY_BASELINE = {
  controls: EOS_SECURITY_BASELINE_CONTROLS,
  certified: false,
  nis2Alignment: "EXTENSIBLE_NOT_CERTIFIED" as const,
  soc2Alignment: "EXTENSIBLE_NOT_CERTIFIED" as const,
  iso27001Alignment: "EXTENSIBLE_NOT_CERTIFIED" as const,
};

export const EOS_HORIZONTAL_MODULE_INVENTORY: readonly EosHorizontalModuleInventoryRow[] = [
  {
    MODULE_ID: "engineering_core",
    MODULE_NAME: "Engineering Core",
    PURPOSE: "Projects, assets, documents, workbench, decisions, and governed engineering objects",
    AI_PRESENT: "YES",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "MATERIAL",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "engineering_review",
    MODULE_NAME: "Engineering Review",
    PURPOSE: "Pre-issue and bounded review with identity assurance and malware gates",
    AI_PRESENT: "YES",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "MATERIAL",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "project_controls",
    MODULE_NAME: "Project Controls",
    PURPOSE: "Progress, schedule, cost, change, and forecast intelligence",
    AI_PRESENT: "YES",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "ADVISORY",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "project_intelligence",
    MODULE_NAME: "Project Intelligence",
    PURPOSE: "Document, meeting, finding, and knowledge intelligence",
    AI_PRESENT: "YES",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "ADVISORY",
    EXTERNAL_SYSTEM_ACCESS: "YES",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "asset_intelligence",
    MODULE_NAME: "Asset Intelligence",
    PURPOSE: "Asset health, reliability, and lifecycle intelligence",
    AI_PRESENT: "YES",
    PERSONAL_DATA_PRESENT: "NO",
    ENGINEERING_DECISION_IMPACT: "ADVISORY",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "inspection_intelligence",
    MODULE_NAME: "Inspection Intelligence",
    PURPOSE: "Inspection workflows, condition, and evidence",
    AI_PRESENT: "YES",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "ADVISORY",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "digital_twin",
    MODULE_NAME: "Digital Twin",
    PURPOSE: "Twin state, simulation adapters, and digital thread",
    AI_PRESENT: "YES",
    PERSONAL_DATA_PRESENT: "NO",
    ENGINEERING_DECISION_IMPACT: "ADVISORY",
    EXTERNAL_SYSTEM_ACCESS: "YES",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "managed_repository",
    MODULE_NAME: "Managed Repository",
    PURPOSE: "Governed engineering information repository and binary storage",
    AI_PRESENT: "NO",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "NONE",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "m365_connector",
    MODULE_NAME: "M365 Connector",
    PURPOSE: "Sites.Selected SharePoint READ connector",
    AI_PRESENT: "NO",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "NONE",
    EXTERNAL_SYSTEM_ACCESS: "YES",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "external_tools",
    MODULE_NAME: "External Tools",
    PURPOSE: "Governed solver and tool adapters including SPACE GASS boundary",
    AI_PRESENT: "NO",
    PERSONAL_DATA_PRESENT: "NO",
    ENGINEERING_DECISION_IMPACT: "MATERIAL",
    EXTERNAL_SYSTEM_ACCESS: "YES",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "ai_workspace",
    MODULE_NAME: "AI Workspace",
    PURPOSE: "Engineering AI ask, grounding, and human review workspace",
    AI_PRESENT: "YES",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "ADVISORY",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "organizational_intelligence",
    MODULE_NAME: "Organizational Intelligence",
    PURPOSE: "Approved lessons and workflow learning; not employee surveillance",
    AI_PRESENT: "YES",
    PERSONAL_DATA_PRESENT: "NO",
    ENGINEERING_DECISION_IMPACT: "ADVISORY",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "commerce_entitlement",
    MODULE_NAME: "Commerce / Entitlement",
    PURPOSE: "Product, licence, seat, and installation entitlement",
    AI_PRESENT: "NO",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "NONE",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "NO",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "identity_authentication",
    MODULE_NAME: "Identity / Authentication",
    PURPOSE: "Auth, MFA/AAL2, tenant and workspace membership",
    AI_PRESENT: "NO",
    PERSONAL_DATA_PRESENT: "YES",
    ENGINEERING_DECISION_IMPACT: "NONE",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
  {
    MODULE_ID: "audit_observability",
    MODULE_NAME: "Audit / Observability",
    PURPOSE: "Security logging, correlation, and system health",
    AI_PRESENT: "NO",
    PERSONAL_DATA_PRESENT: "POSSIBLE",
    ENGINEERING_DECISION_IMPACT: "NONE",
    EXTERNAL_SYSTEM_ACCESS: "NO",
    CURRENT_JURISDICTION_ASSUMPTION: "NONE_GLOBAL_NEUTRAL",
    EU_REVIEW_REQUIRED: "YES",
    GLOBAL_REVIEW_REQUIRED: "YES",
  },
];

export const EOS_DISCIPLINE_GAP_REGISTER: readonly EosDisciplineGapRow[] = [
  { disciplineId: "STRUCTURAL", name: "Structural", maturity: "REFERENCE_PARTIALLY_IMPLEMENTED" },
  { disciplineId: "CIVIL", name: "Civil", maturity: "NOT_YET_DEDICATED" },
  { disciplineId: "GEOTECHNICAL", name: "Geotechnical", maturity: "NOT_YET_DEDICATED" },
  { disciplineId: "MECHANICAL", name: "Mechanical", maturity: "NOT_YET_DEDICATED" },
  { disciplineId: "PIPING", name: "Piping", maturity: "NOT_YET_DEDICATED" },
  { disciplineId: "PROCESS", name: "Process", maturity: "NOT_YET_DEDICATED" },
  { disciplineId: "ELECTRICAL", name: "Electrical", maturity: "NOT_YET_DEDICATED" },
  { disciplineId: "INSTRUMENTATION_CONTROL", name: "Instrumentation & Control", maturity: "NOT_YET_DEDICATED" },
];

function cell(
  profileId: EosComplianceMatrixCell["profileId"],
  category: EosComplianceMatrixCell["category"],
  status: EosComplianceMatrixCell["status"],
  note: string,
): EosComplianceMatrixCell {
  return { profileId, category, status, note };
}

export const EOS_GLOBAL_COMPLIANCE_MATRIX: readonly EosComplianceMatrixCell[] = EOS_JURISDICTION_PROFILE_IDS.filter(
  (id) => id !== "other",
).flatMap((profileId) =>
  EOS_COMPLIANCE_CATEGORIES.map((category) => {
    if (category === "ENGINEERING_STANDARDS") {
      return cell(profileId, category, "KNOWN", "Standards families are profile metadata; no country engine is implemented.");
    }
    if (category === "CYBERSECURITY") {
      return cell(profileId, category, "KNOWN", "Global security baseline is architectural; no NIS2/SOC2/ISO certification is claimed.");
    }
    if (category === "AI_TRANSPARENCY") {
      return cell(profileId, category, "KNOWN", "Intended purpose, provenance, and human oversight metadata are required.");
    }
    if (category === "DATA_RESIDENCY" || category === "CROSS_BORDER_TRANSFER") {
      return cell(profileId, category, "REQUIRES_TECHNICAL_IMPLEMENTATION", "Regional deployment policy is defined; hosting topology is not fixed.");
    }
    if (category === "AI_REGULATION" || category === "HIGH_RISK_RESTRICTED_USES" || category === "PROFESSIONAL_ENGINEERING_AUTHORITY") {
      return cell(profileId, category, "REQUIRES_LEGAL_REVIEW", "Classification fields exist; no legal determination is made in EOS-EU-0.");
    }
    return cell(profileId, category, "REQUIRES_LEGAL_REVIEW", "Privacy/retention profiles are jurisdiction-selectable, not a universal legal conclusion.");
  }),
);

export const EOS_SAMPLE_AI_CAPABILITY: EosAiCapabilityRecord = {
  capabilityId: "engineering-ask-advisory",
  name: "Engineering Ask",
  module: "ai_workspace",
  discipline: null,
  intendedPurpose: "Advisory grounded answers for named engineers; not design approval",
  AIType: "GENERATIVE",
  modelOrTool: "platform-ai-director",
  provider: "platform",
  version: "1.0.0",
  inputCategories: ["engineeringData", "AIInput"],
  outputCategories: ["AI_SUGGESTION", "INFORMATIONAL"],
  engineeringImpact: "advisory",
  humanOversightRequired: true,
  autonomousActionAllowed: false,
  governedNumericalOutputAllowed: false,
  evidenceRequired: true,
  provenanceRequired: true,
  riskClassification: "requires-assessment",
  jurisdictionApplicability: ["global-baseline"],
  deploymentRegion: EOS_DEFAULT_REGIONAL_DEPLOYMENT.allowedRegions,
  dataCategories: ["engineeringData", "AIInput", "AIOutput"],
  reviewStatus: "DRAFT",
  effectiveVersion: "1.0.0",
};
