/**
 * Phase 10J certification gates A–BG (Predictive Method Governance).
 */
export const PHASE_10J_ASSET_INTELLIGENCE_PREDICTIVE_GOVERNANCE_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 10A regression"],
  ["C", "Phase 10B regression"],
  ["D", "Phase 10B.1 regression"],
  ["E", "Phase 10C regression"],
  ["F", "Phase 10D regression"],
  ["G", "Phase 10E regression"],
  ["H", "Phase 10F regression"],
  ["I", "Phase 10G regression"],
  ["J", "Phase 10H regression"],
  ["K", "Phase 10I regression"],
  ["L", "PI v1 integrity"],
  ["M", "II v1 integrity"],
  ["N", "Ownership locks"],
  ["O", "Predictive terminology"],
  ["P", "Objective Registry"],
  ["Q", "Objective-specific readiness"],
  ["R", "Method Registry"],
  ["S", "Method classes"],
  ["T", "Method Eligibility Engine"],
  ["U", "Method Candidate"],
  ["V", "Qualification Framework"],
  ["W", "Validation Metric Registry"],
  ["X", "Qualification State"],
  ["Y", "Governed review"],
  ["Z", "Segregation of duties"],
  ["AA", "Production execution policy"],
  ["AB", "ML governance"],
  ["AC", "Physics-method compatibility"],
  ["AD", "Statistical-method compatibility"],
  ["AE", "Abstention"],
  ["AF", "Fusion provenance"],
  ["AG", "Evidence Confidence"],
  ["AH", "Trend Confidence"],
  ["AI", "Freshness policy"],
  ["AJ", "Hosted migration"],
  ["AK", "Migration lineage"],
  ["AL", "Hosted persistence"],
  ["AM", "Snapshot"],
  ["AN", "Timeline"],
  ["AO", "Event/outbox"],
  ["AP", "Health boundary"],
  ["AQ", "Risk/Maintenance/Priority boundary"],
  ["AR", "PoF remains uncertified"],
  ["AS", "RUL remains uncertified"],
  ["AT", "HTTP contracts"],
  ["AU", "Real JWT matrix"],
  ["AV", "Tenant isolation"],
  ["AW", "Workspace isolation"],
  ["AX", "IDOR"],
  ["AY", "Idempotency"],
  ["AZ", "Concurrency"],
  ["BA", "Health/observability"],
  ["BB", "No production memory"],
  ["BC", "Predictive ML disabled by default"],
  ["BD", "Production predictive execution disabled"],
  ["BE", "Secret exposure"],
  ["BF", "Artifact identity"],
  ["BG", "Asset Intelligence GA readiness / Phase 10K"],
] as const;

export type Phase10jGateId =
  (typeof PHASE_10J_ASSET_INTELLIGENCE_PREDICTIVE_GOVERNANCE_GATES)[number][0];
