export const PHASE_9F_INSPECTION_MOBILE_PRODUCT_GATES = [
  ["A", "Repository and build identity"],
  ["B", "Prior phase regression"],
  ["C", "Project Intelligence v1 tag integrity"],
  ["D", "Engineering Mobile SDK"],
  ["E", "Mobile capability manifest"],
  ["F", "Tablet UX"],
  ["G", "Phone UX"],
  ["H", "Camera capture"],
  ["I", "Media security"],
  ["J", "QR and barcode resolution"],
  ["K", "Photo annotation"],
  ["L", "User attestation"],
  ["M", "Workflow execution record"],
  ["N", "Touch optimization"],
  ["O", "Mobile form continuity"],
  ["P", "Connectivity and sync readiness"],
  ["Q", "Pack-aware mobile forms"],
  ["R", "Mobile events and audit"],
  ["S", "Entitlement"],
  ["T", "Tenant isolation"],
  ["U", "Workspace isolation"],
  ["V", "Privacy"],
  ["W", "Browser E2E"],
  ["X", "Accessibility"],
  ["Y", "Responsive layouts"],
  ["Z", "Performance"],
  ["AA", "No AI Vision implementation"],
  ["AB", "No Asset Intelligence ownership"],
  ["AC", "No Digital Twin ownership"],
  ["AD", "Secret exposure"],
  ["AE", "Artifact identity"],
  ["AF", "Release eligibility"],
] as const;

export type Phase9fGateId = (typeof PHASE_9F_INSPECTION_MOBILE_PRODUCT_GATES)[number][0];
