import type { D1dValidationDebtItem } from "@rtb/types";
import { AU_VALIDATION_DEBT_REGISTER } from "../au-validation/debt";
import { EU_VALIDATION_DEBT_REGISTER } from "../eu-validation/debt";
import { US_VALIDATION_DEBT_REGISTER } from "../us-validation/debt";

const CATEGORY: Record<string, string> = {
  "AU-VD-EDITION": "STANDARD_IDENTITY",
  "AU-VD-AMENDMENT": "STANDARD_IDENTITY",
  "AU-VD-TENSION-CODE": "CODE_PROFILE_RESISTANCE",
  "AU-VD-COMPRESSION-CODE": "CODE_PROFILE_RESISTANCE",
  "AU-VD-CLASSIFICATION": "SECTION_CLASSIFICATION",
  "AU-VD-BENDING-CODE": "CODE_PROFILE_RESISTANCE",
  "AU-VD-LTB-CODE": "LTB",
  "AU-VD-SHEAR-CODE": "CODE_PROFILE_RESISTANCE",
  "AU-VD-WEB-SLENDERNESS": "SHEAR_WEB_STABILITY",
  "AU-VD-INTERACTION": "INTERACTION",
  "AU-VD-SLS-CRITERIA": "SERVICEABILITY",
  "AU-VD-THIRD-PARTY": "EXTERNAL_TOOL_COMPARISON",
  "AU-VD-HUMAN": "HUMAN_ENGINEERING_VALIDATION",
  "AU-VD-SOLVER": "GENERAL_ANALYSIS",
  "EU-VD-EDITION": "STANDARD_IDENTITY",
  "EU-VD-AMENDMENT": "STANDARD_IDENTITY",
  "EU-VD-ANNEX": "STANDARD_IDENTITY",
  "EU-VD-NDP": "STANDARD_IDENTITY",
  "EU-VD-MATERIAL": "MATERIAL_DATA",
  "EU-VD-CLASSIFICATION": "SECTION_CLASSIFICATION",
  "EU-VD-TENSION-CODE": "CODE_PROFILE_RESISTANCE",
  "EU-VD-COMPRESSION-CODE": "CODE_PROFILE_RESISTANCE",
  "EU-VD-BUCKLING-CURVES": "MEMBER_STABILITY",
  "EU-VD-BENDING-CODE": "CODE_PROFILE_RESISTANCE",
  "EU-VD-LTB-CODE": "LTB",
  "EU-VD-SHEAR-CODE": "CODE_PROFILE_RESISTANCE",
  "EU-VD-WEB-SLENDERNESS": "SHEAR_WEB_STABILITY",
  "EU-VD-WEB-BUCKLING": "SHEAR_WEB_STABILITY",
  "EU-VD-INTERACTION": "INTERACTION",
  "EU-VD-SLS-CRITERIA": "SERVICEABILITY",
  "EU-VD-THIRD-PARTY": "EXTERNAL_TOOL_COMPARISON",
  "EU-VD-HUMAN": "HUMAN_ENGINEERING_VALIDATION",
  "EU-VD-SOLVER": "GENERAL_ANALYSIS",
  "EU-VD-CONNECTION": "CONNECTIONS",
  "US-VD-EDITION": "STANDARD_IDENTITY",
  "US-VD-AMENDMENT": "STANDARD_IDENTITY",
  "US-VD-ADOPTION": "STANDARD_IDENTITY",
  "US-VD-LOAD-EDITION": "STANDARD_IDENTITY",
  "US-VD-AMENDMENT-SET": "STANDARD_IDENTITY",
  "US-VD-MATERIAL": "MATERIAL_DATA",
  "US-VD-CATALOG": "SECTION_CATALOGS",
  "US-VD-EFFECTIVE-NET": "CODE_PROFILE_RESISTANCE",
  "US-VD-HOLE-DEDUCTION": "CODE_PROFILE_RESISTANCE",
  "US-VD-TENSION-LRFD": "CODE_PROFILE_RESISTANCE",
  "US-VD-TENSION-ASD": "CODE_PROFILE_RESISTANCE",
  "US-VD-COMPRESSION-CODE": "CODE_PROFILE_RESISTANCE",
  "US-VD-STABILITY-METHOD": "MEMBER_STABILITY",
  "US-VD-CLASSIFICATION": "SECTION_CLASSIFICATION",
  "US-VD-TORSIONAL": "MEMBER_STABILITY",
  "US-VD-FT-BUCKLING": "MEMBER_STABILITY",
  "US-VD-FLEXURAL-CODE": "CODE_PROFILE_RESISTANCE",
  "US-VD-LTB-CODE": "LTB",
  "US-VD-CB": "LTB",
  "US-VD-TRANSITION": "LTB",
  "US-VD-SHEAR-AREA": "SHEAR_WEB_STABILITY",
  "US-VD-WEB-SLENDERNESS": "SHEAR_WEB_STABILITY",
  "US-VD-WEB-STABILITY": "SHEAR_WEB_STABILITY",
  "US-VD-TENSION-FIELD": "SHEAR_WEB_STABILITY",
  "US-VD-INTERACTION": "INTERACTION",
  "US-VD-SLS-CRITERIA": "SERVICEABILITY",
  "US-VD-THIRD-PARTY": "EXTERNAL_TOOL_COMPARISON",
  "US-VD-HUMAN": "HUMAN_ENGINEERING_VALIDATION",
  "US-VD-SOLVER": "GENERAL_ANALYSIS",
  "US-VD-CONNECTION": "CONNECTIONS",
  "US-VD-SEISMIC": "SEISMIC",
};

const FUTURE: Record<string, string> = {
  STANDARD_IDENTITY: "AU/EU/US steel conformance hardening track",
  CODE_PROFILE_RESISTANCE: "AU/EU/US steel conformance hardening track",
  SECTION_CLASSIFICATION: "AU/EU/US steel conformance hardening track",
  LOCAL_BUCKLING: "AU/EU/US steel conformance hardening track",
  MEMBER_STABILITY: "AU/EU/US steel conformance hardening track",
  LTB: "AU/EU/US steel conformance hardening track",
  SHEAR_WEB_STABILITY: "AU/EU/US steel conformance hardening track",
  INTERACTION: "AU/EU/US steel conformance hardening track",
  SERVICEABILITY: "AU/EU/US steel conformance hardening track",
  MATERIAL_DATA: "AU/EU/US steel conformance hardening track",
  SECTION_CATALOGS: "AU/EU/US steel conformance hardening track",
  EXTERNAL_TOOL_COMPARISON: "D1G / commercial-release track",
  HUMAN_ENGINEERING_VALIDATION: "AU/EU/US steel conformance hardening track",
  GENERAL_ANALYSIS: "D1G",
  CONNECTIONS: "D1F",
  SEISMIC: "later bounded seismic subphase; not D1E",
  PROFESSIONAL_CERTIFICATION: "D1L",
};

function wrap(
  jurisdiction: "AU" | "EU" | "US",
  debtId: string,
  description: string,
  priority: D1dValidationDebtItem["priority"],
): D1dValidationDebtItem {
  const category = CATEGORY[debtId] ?? "ENHANCEMENT";
  return {
    debtId,
    category,
    jurisdiction,
    capability: debtId.replace(/^(AU|EU|US)-VD-/, "").toLowerCase(),
    description,
    priority,
    blockingState: "UNRESOLVED",
    requiredEvidence: "independent standard-identity, method, and human-review evidence",
    ownerWorkstream: `${jurisdiction}_STEEL_CONFORMANCE_HARDENING`,
    recommendedFuturePhase: FUTURE[category] ?? "later certification track",
  };
}

export const D1D_VALIDATION_DEBT_REGISTER: readonly D1dValidationDebtItem[] = [
  ...AU_VALIDATION_DEBT_REGISTER.map((row) => wrap("AU", row.debtId, row.description, row.priority)),
  ...EU_VALIDATION_DEBT_REGISTER.map((row) => wrap("EU", row.debtId, row.description, row.priority)),
  ...US_VALIDATION_DEBT_REGISTER.map((row) => wrap("US", row.debtId, row.description, row.priority)),
  {
    debtId: "D1D-VD-LOCAL-BUCKLING-GLOBAL",
    category: "LOCAL_BUCKLING",
    jurisdiction: "GLOBAL",
    capability: "local buckling",
    description: "no jurisdiction has a validated local-buckling code method",
    priority: "SAFETY_CRITICAL",
    blockingState: "UNRESOLVED",
    requiredEvidence: "jurisdiction-specific classification/local-buckling rules with edition evidence",
    ownerWorkstream: "STEEL_CONFORMANCE_HARDENING",
    recommendedFuturePhase: FUTURE.LOCAL_BUCKLING,
  },
  {
    debtId: "D1D-VD-PROFESSIONAL-CERTIFICATION",
    category: "PROFESSIONAL_CERTIFICATION",
    jurisdiction: "GLOBAL",
    capability: "professional certification",
    description: "D1D does not certify software or approve construction",
    priority: "COMMERCIAL_RELEASE_CRITICAL",
    blockingState: "UNRESOLVED",
    requiredEvidence: "D1L certification gate plus independent human validation",
    ownerWorkstream: "D1L",
    recommendedFuturePhase: "D1L",
  },
];

export const D1D_VALIDATION_PRIORITY_PLAN = [
  { rank: 1, priority: "SAFETY_CRITICAL" as const, items: D1D_VALIDATION_DEBT_REGISTER.filter((row) => row.priority === "SAFETY_CRITICAL").map((row) => row.debtId) },
  { rank: 2, priority: "CONFORMANCE_CRITICAL" as const, items: D1D_VALIDATION_DEBT_REGISTER.filter((row) => row.priority === "CONFORMANCE_CRITICAL").map((row) => row.debtId) },
  { rank: 3, priority: "COMMERCIAL_RELEASE_CRITICAL" as const, items: D1D_VALIDATION_DEBT_REGISTER.filter((row) => row.priority === "COMMERCIAL_RELEASE_CRITICAL").map((row) => row.debtId) },
  { rank: 4, priority: "ENHANCEMENT" as const, items: D1D_VALIDATION_DEBT_REGISTER.filter((row) => row.priority === "ENHANCEMENT").map((row) => row.debtId) },
] as const;
