export const D1D_STANDARD_GOVERNANCE_MATRIX = {
  AU: {
    standardProfile: "AS 4100 intended profile (au-steel-as4100-intended)",
    editionGovernance: "UNKNOWN_PENDING_CONFIRMATION; silent inference forbidden",
    amendmentGovernance: "UNKNOWN_PENDING_CONFIRMATION; historical context immutable",
    nationalAnnex: "NOT_APPLICABLE",
    ndp: "NOT_APPLICABLE",
    buildingCodeAdoption: "not an AS 4100 member-design substitute; D1B bind required",
    loadStandardDependency: "AS/NZS 1170 via D1C demand handoff; no parallel combination engine",
    designMethod: "AS 4100 capacity reduction remains framework-only",
    localAmendments: "not modelled as a National Annex; project overrides fail closed",
    directContractProfile: "not a substitute for AS 4100 conformance",
  },
  EU: {
    eurocodeFamily: "EN 1993 registered; not hardcoded to EU membership",
    part: "initial steel part EN 1993-1-1; other parts remain stubs",
    edition: "UNKNOWN_PENDING_CONFIRMATION; first- and second-generation isolation",
    nationalAnnex: "required when annex applies; no default annex; not inferred from location",
    ndp: "modelled; values not guessed; missing NDP fails closed",
    buildingCodeAdoption: "country and standard remain separate",
    loadStandardDependency: "EN 1990 / EN 1991 via D1C; no parallel EU combination engine",
    designMethod: "Eurocode partial factors remain framework-only",
    localAmendments: "National Annex / NDP, not US local-amendment semantics",
    directContractProfile: "UK / non-EU Eurocode use remains possible",
  },
  US: {
    buildingCodeAdoption: "adopting authority / building-code edition modelled; datasets not populated",
    aiscProfile: "AISC 360 family registered; edition UNKNOWN_PENDING_CONFIRMATION",
    loadStandardDependency: "ASCE 7 via D1C; no parallel US combination engine",
    lrfdAsd: "explicit; no default; no silent conversion; no mixed-method authority",
    localAmendments: "identity/base-code/edition compatibility explicit; values not guessed",
    directContractProfile: "contractual AISC profile allowed; does not equal building-code compliance",
    seismicStandardDependency: "AISC 341 modelled as dependency only; not a member design engine",
    connectionStandardDependency: "AISC 360/358 connection design not in member scope",
  },
} as const;
