import type { D1dPhaseInventoryRecord } from "@rtb/types";

export const D1D_PHASE_INVENTORY: readonly D1dPhaseInventoryRecord[] = [
  {
    phase: "EOS-D1D-0",
    scope: "common steel object model, adapter contracts, jurisdiction-neutral mechanics boundary",
    commit: "bfb00709d9bb1ecf63dc213172af2af45977bdd1",
    verdict: "PASS",
    implementedCapability: "global steel framework and adapter routing",
    frameworkOnlyCapability: "AS 4100 / EN 1993 / AISC 360 resistance equations",
    validationState: "FRAMEWORK_ONLY",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "no jurisdiction design equations; not a complete steel product",
    validationDebt: "all jurisdiction code-profile methods",
    riskImpact: "D0-R01 reduced by shared contract; standards-implementation risks remain open",
  },
  {
    phase: "EOS-D1D-AU-1",
    scope: "AU tension mechanics and AS 4100 profile binding",
    commit: "0ad9007a3f0b2128c8f544b226e95d4c6b7aba79",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "gross-yield and net-fracture mechanics",
    frameworkOnlyCapability: "AS 4100 φNt / code tension strength",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "mechanics ≠ AS 4100 tension design",
    validationDebt: "AU-VD-EDITION, AU-VD-TENSION-CODE",
    riskImpact: "D0-R01 reduced; conformance remaining",
  },
  {
    phase: "EOS-D1D-AU-2",
    scope: "AU compression / Euler stability mechanics",
    commit: "2c56e42cabfcce08b32459616f1bc159998de575",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "squash yield and Euler major/minor",
    frameworkOnlyCapability: "AS 4100 member compression capacity",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "Euler ≠ code compression design",
    validationDebt: "AU-VD-COMPRESSION-CODE, AU-VD-CLASSIFICATION",
    riskImpact: "stability governance reduced; code curve remaining",
  },
  {
    phase: "EOS-D1D-AU-3",
    scope: "AU bending / elastic LTB mechanics",
    commit: "03cedc18bd8586dd12868e386edf798f10efa8f0",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "elastic major/minor My and uniform-moment Mcr",
    frameworkOnlyCapability: "AS 4100 member moment capacity",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "elastic My/Mcr ≠ code flexural design",
    validationDebt: "AU-VD-BENDING-CODE, AU-VD-LTB-CODE",
    riskImpact: "mechanics bounded; code LTB remaining",
  },
  {
    phase: "EOS-D1D-AU-4",
    scope: "AU shear / elastic plate buckling mechanics",
    commit: "f125f14a3c6d2480744ec7bd8f72ce05a62a5756",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "von Mises shear yield and elastic plate buckling",
    frameworkOnlyCapability: "AS 4100 shear capacity / web rules",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "elastic shear ≠ code shear design",
    validationDebt: "AU-VD-SHEAR-CODE, AU-VD-WEB-SLENDERNESS",
    riskImpact: "mechanics bounded; web code remaining",
  },
  {
    phase: "EOS-D1D-AU-5",
    scope: "AU combined-action framework",
    commit: "b8eff3ed20e3fbf04ebdefad4194184393660592",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "interaction detection and fail-closed gap",
    frameworkOnlyCapability: "numerical AS 4100 interaction equations",
    validationState: "FRAMEWORK_ONLY",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "IMPLEMENTED_INTERACTION_METHODS = NONE",
    validationDebt: "AU-VD-INTERACTION",
    riskImpact: "fail-closed interaction; no code combined-action",
  },
  {
    phase: "EOS-D1D-AU-6",
    scope: "AU member orchestration and governed serviceability",
    commit: "70ed3b1407215034ea0eeaf82eeafa18b48afa3c",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "fail-closed member orchestration; D1C deflection reuse",
    frameworkOnlyCapability: "complete AS 4100 member design",
    validationState: "ORCHESTRATION_VALIDATED",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "mechanics complete ≠ code design complete",
    validationDebt: "AU-VD-SLS-CRITERIA, AU-VD-HUMAN",
    riskImpact: "approval remains separate",
  },
  {
    phase: "EOS-D1D-AU-7",
    scope: "AU independent validation / conformance / release gate",
    commit: "a63957ccfced88c3ca5acb5a6c595c30fd388127",
    verdict: "PASS",
    implementedCapability: "AU validation inventory, matrix, debt, claim classification",
    frameworkOnlyCapability: "AS 4100 conformance and pack certification",
    validationState: "BENCHMARKED_ENGINEERING_CAPABILITY",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "AU_STEEL_PACK_CERTIFIED = NO",
    validationDebt: "AU_VALIDATION_DEBT_REGISTER",
    riskImpact: "D0-R01/D0-R03 reduced; remaining canonical risks open",
  },
  {
    phase: "EOS-D1D-EU-1",
    scope: "Eurocode steel family / part / annex / NDP governance",
    commit: "848f0e35a72f9e58fd448a0de03a0d3533bc1724",
    verdict: "PASS",
    implementedCapability: "EN 1993 binding architecture",
    frameworkOnlyCapability: "EN 1993 resistance equations and Annex/NDP values",
    validationState: "FRAMEWORK_ONLY",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "edition UNKNOWN_PENDING_CONFIRMATION",
    validationDebt: "EU-VD-EDITION, EU-VD-ANNEX, EU-VD-NDP",
    riskImpact: "D0-R02 already closed by D1B; annex datasets remaining",
  },
  {
    phase: "EOS-D1D-EU-2",
    scope: "EU tension mechanics",
    commit: "0c1086862d7f2d1d1619696d46e3862b85afabb6",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "gross-yield and net-fracture mechanics",
    frameworkOnlyCapability: "EN 1993 Nt,Rd",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "mechanics ≠ EN 1993 tension resistance",
    validationDebt: "EU-VD-TENSION-CODE",
    riskImpact: "mechanics bounded",
  },
  {
    phase: "EOS-D1D-EU-3",
    scope: "EU compression / Euler mechanics",
    commit: "176edfc995e1ac3fa49a97bf44d3fad6afc208d3",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "squash yield and Euler major/minor",
    frameworkOnlyCapability: "EN 1993 Nb,Rd / buckling curves",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "Euler ≠ EN 1993 member compression",
    validationDebt: "EU-VD-COMPRESSION-CODE, EU-VD-BUCKLING-CURVES",
    riskImpact: "mechanics bounded",
  },
  {
    phase: "EOS-D1D-EU-4",
    scope: "EU bending / elastic LTB mechanics",
    commit: "29a730203b1b13c1ee3446480eae81e1fd429f0c",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "elastic My and uniform-moment Mcr",
    frameworkOnlyCapability: "EN 1993 Mc,Rd / Mb,Rd",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "elastic bending/LTB ≠ EN 1993 flexural resistance",
    validationDebt: "EU-VD-BENDING-CODE, EU-VD-LTB-CODE",
    riskImpact: "mechanics bounded",
  },
  {
    phase: "EOS-D1D-EU-5",
    scope: "EU shear / elastic web buckling mechanics",
    commit: "db2a418792b9f38b0a485e1bd052b50585dca70e",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "von Mises shear yield and elastic plate buckling",
    frameworkOnlyCapability: "EN 1993 Vpl,Rd / EN 1993-1-5 web rules",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "elastic shear ≠ EN 1993 shear/web resistance",
    validationDebt: "EU-VD-SHEAR-CODE, EU-VD-WEB-BUCKLING",
    riskImpact: "mechanics bounded",
  },
  {
    phase: "EOS-D1D-EU-6",
    scope: "EU combined-action framework",
    commit: "0200ab1c014636f836a13d0f3445fef8fb95a1f8",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "interaction detection and fail-closed gap",
    frameworkOnlyCapability: "numerical EN 1993 interaction",
    validationState: "FRAMEWORK_ONLY",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "IMPLEMENTED_EU_INTERACTION_METHODS = NONE",
    validationDebt: "EU-VD-INTERACTION",
    riskImpact: "fail-closed interaction",
  },
  {
    phase: "EOS-D1D-EU-7",
    scope: "EU member orchestration and governed serviceability",
    commit: "31bcd8ecdc4fec00f079c2eb31d7ea6f392079fd",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "fail-closed Eurocode member orchestration",
    frameworkOnlyCapability: "complete EN 1993 member design",
    validationState: "ORCHESTRATION_VALIDATED",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "mechanics complete ≠ Eurocode design complete",
    validationDebt: "EU-VD-SLS-CRITERIA, EU-VD-HUMAN",
    riskImpact: "approval remains separate",
  },
  {
    phase: "EOS-D1D-EU-8",
    scope: "EU independent validation / conformance / release gate",
    commit: "6768bb1be172c8978daf0127b9fa161a6b72bea5",
    verdict: "PASS",
    implementedCapability: "EU validation inventory, matrix, debt, claim classification",
    frameworkOnlyCapability: "Eurocode conformance and pack certification",
    validationState: "BENCHMARKED_ENGINEERING_REFERENCE_CAPABILITY",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "EU_STEEL_PACK_CERTIFIED = NO",
    validationDebt: "EU_VALIDATION_DEBT_REGISTER",
    riskImpact: "D0-R01/D0-R03 reduced; remaining canonical risks open",
  },
  {
    phase: "EOS-D1D-US-1",
    scope: "AISC family, LRFD/ASD, building-code adoption, direct-contract governance",
    commit: "db0c608b9a16e9c0ddcea15d4eee63f55fa36e77",
    verdict: "PASS",
    implementedCapability: "US steel standard-binding architecture",
    frameworkOnlyCapability: "AISC 360 strengths and adoption datasets",
    validationState: "FRAMEWORK_ONLY",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "AISC edition UNKNOWN_PENDING_CONFIRMATION",
    validationDebt: "US-VD-EDITION, US-VD-ADOPTION",
    riskImpact: "jurisdiction/standard separation preserved",
  },
  {
    phase: "EOS-D1D-US-2",
    scope: "US tension mechanics",
    commit: "91bcd9eaadd4ecf1d3604e5cd51df697a14516f8",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "gross-yield and net-fracture mechanics",
    frameworkOnlyCapability: "AISC LRFD/ASD tension strengths",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "mechanics ≠ AISC tension design strength",
    validationDebt: "US-VD-TENSION-LRFD, US-VD-TENSION-ASD",
    riskImpact: "mechanics bounded",
  },
  {
    phase: "EOS-D1D-US-3",
    scope: "US compression / Euler stability mechanics",
    commit: "ecfd852de95518c11a883948f261f0a6781ad151",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "squash yield and Euler major/minor",
    frameworkOnlyCapability: "AISC member compression strength",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "Euler ≠ AISC member compression strength",
    validationDebt: "US-VD-COMPRESSION-CODE, US-VD-CLASSIFICATION",
    riskImpact: "K not defaulted; code curve remaining",
  },
  {
    phase: "EOS-D1D-US-4",
    scope: "US bending / elastic LTB mechanics",
    commit: "58a423cebe4cc556b83461ffea979ff827d6171c",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "elastic My and uniform-moment Mcr",
    frameworkOnlyCapability: "AISC flexural strength / Cb / Lp-Lr",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "elastic bending/LTB ≠ AISC flexural strength",
    validationDebt: "US-VD-FLEXURAL-CODE, US-VD-LTB-CODE, US-VD-CB",
    riskImpact: "mechanics bounded",
  },
  {
    phase: "EOS-D1D-US-5",
    scope: "US shear / elastic web buckling mechanics",
    commit: "7dd29fb52b12ab210334b8a32916753d7d8bce24",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "von Mises shear yield and elastic plate buckling",
    frameworkOnlyCapability: "AISC shear/web strength",
    validationState: "NUMERICALLY_VALIDATED_MECHANICS",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "elastic shear ≠ AISC shear/web strength",
    validationDebt: "US-VD-SHEAR-AREA, US-VD-WEB-STABILITY",
    riskImpact: "mechanics bounded",
  },
  {
    phase: "EOS-D1D-US-6",
    scope: "US combined-action framework",
    commit: "f31b356d810c5308ce2d6e0058e969eb72d430e4",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "interaction detection and fail-closed gap",
    frameworkOnlyCapability: "numerical AISC interaction",
    validationState: "FRAMEWORK_ONLY",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "IMPLEMENTED_US_INTERACTION_METHODS = NONE",
    validationDebt: "US-VD-INTERACTION",
    riskImpact: "fail-closed interaction",
  },
  {
    phase: "EOS-D1D-US-7",
    scope: "US member orchestration and four-layer result model",
    commit: "bd01cdb60dedd24d7c6452c8e5af72e6ea8faf77",
    verdict: "PASS_WITH_LIMITATIONS",
    implementedCapability: "fail-closed AISC/building-code/approval orchestration",
    frameworkOnlyCapability: "complete AISC member design",
    validationState: "ORCHESTRATION_VALIDATED",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "AISC member check ≠ building-code compliance",
    validationDebt: "US-VD-SLS-CRITERIA, US-VD-HUMAN",
    riskImpact: "approval remains separate",
  },
  {
    phase: "EOS-D1D-US-8",
    scope: "US independent validation / conformance / release gate",
    commit: "c3e1396bb67d1f5b8638f6c8189d55a37269d77f",
    verdict: "PASS",
    implementedCapability: "US validation inventory, matrix, debt, claim classification",
    frameworkOnlyCapability: "AISC conformance, building-code compliance, pack certification",
    validationState: "BENCHMARKED_ENGINEERING_REFERENCE_CAPABILITY",
    conformanceState: "INTENDED_PROFILE",
    releaseState: "INTERNAL_ENGINEERING_REFERENCE",
    knownLimitations: "US_STEEL_PACK_CERTIFIED = NO",
    validationDebt: "US_VALIDATION_DEBT_REGISTER",
    riskImpact: "D0-R01/D0-R03 reduced; remaining canonical risks open",
  },
];

export const D1D_SOURCE_CONTROL_TRACEABILITY = "PASS" as const;
export const D1D_SOURCE_CONTROL_ANOMALIES: readonly string[] = [];
