import type { D1dCommonMechanicsRecord } from "@rtb/types";

const AU_EU_US = ["AU", "EU", "US"] as const;
const NOT_CODE = "not AS 4100, EN 1993, National Annex/NDP, AISC, LRFD, ASD, or local-amendment strength";

export const COMMON_STEEL_MECHANICS_INVENTORY: readonly D1dCommonMechanicsRecord[] = [
  {
    commonMethodId: "COMMON_TENSION_GROSS_YIELD",
    supportedInputs: ["Fy or fy", "Ag"],
    supportedOutputs: "nominalTensionForceN",
    units: "N",
    assumptions: "stress × area; holes ignored",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not AS 4100 φNt, EN 1993 Nt,Rd, or AISC Pn; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_TENSION_NET_FRACTURE",
    supportedInputs: ["Fu or fu", "An"],
    supportedOutputs: "nominalTensionForceN",
    units: "N",
    assumptions: "explicit net area required; not inferred from Ag",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not effective-net-area, block shear, or code fracture strength; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_COMPRESSION_SQUASH_YIELD",
    supportedInputs: ["Fy or fy", "Ag"],
    supportedOutputs: "nominalTensionForceN applied as squash",
    units: "N",
    assumptions: "yield × area; no slenderness reduction",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code compression strength curve; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_EULER_MAJOR",
    supportedInputs: ["E", "Iyy", "Le major"],
    supportedOutputs: "eulerLoadN",
    units: "N",
    assumptions: "elastic Euler; explicit effective length",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not AS 4100 Nc, EN 1993 Nb,Rd, or AISC Pn; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_EULER_MINOR",
    supportedInputs: ["E", "Izz", "Le minor"],
    supportedOutputs: "eulerLoadN",
    units: "N",
    assumptions: "elastic Euler; explicit effective length",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code member compression strength; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_EFFECTIVE_LENGTH_HELPERS",
    supportedInputs: ["explicit Le or K×L with provenance", "restraint description"],
    supportedOutputs: "assertEffectiveLengthGovernance / axisLength",
    units: "m",
    assumptions: "no silent K; support labels do not define K",
    benchmarkState: "NOT_APPLICABLE",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not AISC K tables, EN buckling length, or AS 4100 ke; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_ELASTIC_BENDING_MAJOR",
    supportedInputs: ["Fy or fy", "Sx or Zyy"],
    supportedOutputs: "firstYieldMomentNm",
    units: "N.m",
    assumptions: "elastic first yield My = f S",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not AS 4100 Ms/Mb, EN 1993 Mc,Rd, or AISC Mn; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_ELASTIC_BENDING_MINOR",
    supportedInputs: ["Fy or fy", "Sy or Zzz"],
    supportedOutputs: "firstYieldMomentNm",
    units: "N.m",
    assumptions: "elastic first yield My = f S",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code flexural strength; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_ELASTIC_LTB",
    supportedInputs: ["E", "G", "Iminor", "J", "Iw", "unbraced length"],
    supportedOutputs: "elasticLtbMomentNm",
    units: "N.m",
    assumptions: "uniform-moment elastic Mcr; no Cb/αm/χLT",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not AS 4100 Mb, EN 1993 Mb,Rd, or AISC Mn; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_ELASTIC_SHEAR_MAJOR",
    supportedInputs: ["Fy or fy", "Av or Aw"],
    supportedOutputs: "vonMisesShearYieldN",
    units: "N",
    assumptions: "Vy = fy Av / √3; shear area explicit",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not AS 4100 Vv, EN 1993 Vpl,Rd, or AISC Vn; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_ELASTIC_SHEAR_MINOR",
    supportedInputs: ["Fy or fy", "Av or Aw"],
    supportedOutputs: "vonMisesShearYieldN",
    units: "N",
    assumptions: "same von Mises yield reference on the supplied shear area",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not code minor-axis shear strength; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_ELASTIC_SHEAR_PLATE_BUCKLING",
    supportedInputs: ["E", "ν", "kv", "web depth", "web thickness", "shear area"],
    supportedOutputs: "elasticShearBucklingForceN",
    units: "N",
    assumptions: "kv must be supplied; never defaulted from aspect ratio",
    benchmarkState: "PASS",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: `not tension-field, EN 1993-1-5, or AISC web strength; ${NOT_CODE}`,
  },
  {
    commonMethodId: "COMMON_D1C_BOUNDED_STATICS_DEFLECTION",
    supportedInputs: ["governed D1C demand handoff", "optional explicit SLS criterion"],
    supportedOutputs: "consumeDemandHandoff / D1C deflection reuse",
    units: "N, N.m, m",
    assumptions: "bounded first-order demand; no duplicate load-combination engine",
    benchmarkState: "NOT_APPLICABLE",
    supportedJurisdictions: AU_EU_US,
    unsupportedInterpretations: "not general FEA, nonlinear analysis, plate/shell/solid FEA, dynamics, or eigen-buckling",
  },
];
