import type { AiDataSecurityPlane } from "../../ai-data-contracts";
import { planeHarnessKeys } from "./fixture-harness";

export type AiDataProbeDefinition = {
  probeId: string;
  name: string;
  version: string;
  plane: AiDataSecurityPlane;
  harnessKey: string;
  controlRefs: string[];
  status: "draft" | "active" | "deprecated" | "retired";
  productionSafe: true;
  mutatesAuthorization: false;
  mutatesRls: false;
  mutatesPolicy: false;
};

export const SEED_AI_DATA_PROBES: AiDataProbeDefinition[] = [
  {
    probeId: "aid-ingest-auth",
    name: "Authorized ingestion retains classification",
    version: "1.0.0",
    plane: "DATA_INGESTION",
    harnessKey: "ingestion.authorized_retain",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-ingest-deny",
    name: "Unauthorized ingestion denied",
    version: "1.0.0",
    plane: "DATA_INGESTION",
    harnessKey: "ingestion.unauthorized_deny",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-storage-meta",
    name: "Storage security metadata preserved",
    version: "1.0.0",
    plane: "DATA_STORAGE",
    harnessKey: "storage.metadata_preserved",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-retrieval-deny",
    name: "Retrieval cross-tenant deny",
    version: "1.0.0",
    plane: "RETRIEVAL",
    harnessKey: "retrieval.cross_tenant_deny",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-context-deny",
    name: "AI context cross-tenant deny",
    version: "1.0.0",
    plane: "AI_CONTEXT",
    harnessKey: "ai_context.cross_tenant_deny",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-prompt-boundary",
    name: "Prompt boundary assessment",
    version: "1.0.0",
    plane: "PROMPT",
    harnessKey: "prompt.boundary_assessed",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-provider-approved",
    name: "Approved provider posture",
    version: "1.0.0",
    plane: "MODEL_PROVIDER",
    harnessKey: "provider.approved",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-provider-unknown",
    name: "Unknown provider fail-closed",
    version: "1.0.0",
    plane: "MODEL_PROVIDER",
    harnessKey: "provider.unknown_fail_closed",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-tool-in",
    name: "Tool input scope preserved",
    version: "1.0.0",
    plane: "TOOL_INPUT",
    harnessKey: "tool_input.scope_preserved",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-tool-out",
    name: "Tool output provenance retained",
    version: "1.0.0",
    plane: "TOOL_OUTPUT",
    harnessKey: "tool_output.provenance_retained",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-model-out",
    name: "Model output disclosure assessed",
    version: "1.0.0",
    plane: "MODEL_OUTPUT",
    harnessKey: "model_output.disclosure_assessed",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-persist",
    name: "Persistence metadata retained",
    version: "1.0.0",
    plane: "PERSISTENCE",
    harnessKey: "persistence.metadata_retained",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-logging",
    name: "Logging/telemetry secret non-exposure",
    version: "1.0.0",
    plane: "LOGGING_TELEMETRY",
    harnessKey: "logging.no_secret_persist",
    controlRefs: ["RTB-SEC-S04"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
  {
    probeId: "aid-egress",
    name: "Data egress policy evidenced",
    version: "1.0.0",
    plane: "DATA_EGRESS",
    harnessKey: "egress.policy_evidenced",
    controlRefs: ["RTB-SEC-S05"],
    status: "active",
    productionSafe: true,
    mutatesAuthorization: false,
    mutatesRls: false,
    mutatesPolicy: false,
  },
];

export function assertHarnessCoverage(): void {
  for (const plane of [
    "DATA_INGESTION",
    "DATA_STORAGE",
    "RETRIEVAL",
    "AI_CONTEXT",
    "PROMPT",
    "MODEL_PROVIDER",
    "TOOL_INPUT",
    "TOOL_OUTPUT",
    "MODEL_OUTPUT",
    "PERSISTENCE",
    "LOGGING_TELEMETRY",
    "DATA_EGRESS",
  ] as const) {
    const keys = planeHarnessKeys(plane);
    if (keys.length === 0) throw new Error(`Missing harness coverage for ${plane}`);
  }
}
