import { describe, expect, it } from "vitest";
import {
  AUTHORITATIVE_PROFILE_VALIDATION_REQUIRED_FOR_CONFORMANCE,
  AUTHORITATIVE_STANDARD_DERIVED_REQUIRED_FOR_INITIAL_IMPLEMENTATION,
  COPYRIGHTED_STANDARD_TEXT_REPRODUCED,
  DEFAULT_EU_CONCRETE_NATIONAL_ANNEX,
  ENGINEERING_REFERENCE_IMPLEMENTATION_EQUALS_STANDARD_CONFORMANCE,
  EOS_D1E_EU_C1B_CLOSED,
  EU_C1B_CONFORMANCE_VALIDATION_STRICT,
  EU_C1B_ENGINEER_VALIDATION_REQUIRED_FOR_PROMOTION,
  EU_C1B_FORMULA_FINGERPRINT,
  EU_C1B_IMPLEMENTABLE_NUMERICAL_RULE_COUNT,
  EU_C1B_IMPLEMENTABLE_REFERENCE_RULE_COUNT,
  EU_C1B_MULTI_SOURCE_RULE_VALIDATION,
  EU_C1B_NDP_CLASSIFICATION_EVIDENCE_BASED,
  EU_C1B_NUMERICAL_VALIDATION_REQUIREMENTS,
  EU_C1B_PARAMETER_PROVENANCE_REQUIRED,
  EU_C1B_PARTIAL_FACTOR_GUESSED,
  EU_C1B_RULE_AUTHORITY_MODEL,
  EU_C1B_RULE_CLASSIFICATION_COMPLETE,
  EU_C1B_RULE_EVIDENCE_RECORD,
  EU_C1B_RULE_MATURITY_MODEL,
  EU_C1B_SECTION_MODEL_PARAMETER_GUESSED,
  EU_C1B_SOURCE_CONFLICT_FAILS_CLOSED,
  EU_C1B_STRAIN_PARAMETER_GUESSED,
  EU_C1_ACCEPTANCE_POLICY_CORRECTED,
  EU_C1_RESUME_GATE,
  EU_CONCRETE_PACK_CERTIFIED,
  EU_CONCRETE_PRODUCT_CLAIM_LEVEL,
  EU_CONCRETE_STANDARD_CONFORMANCE_STATE,
  EXTERNAL_SOFTWARE_RESULT_EQUALS_RULE_AUTHORITY,
  FULL_STANDARD_TEXT_REQUIRED_FOR_RULE_IMPLEMENTATION,
  LICENSED_STANDARD_DOCUMENT_REQUIRED_FOR_IMPLEMENTATION,
  LLM_MEMORY_ONLY_RULE_ALLOWED,
  MODEL_SUGGESTED_PARAMETER_REQUIRES_EXTERNAL_VALIDATION,
  NATIONAL_ANNEX_INFERRED_FROM_LOCATION,
  NON_REPRODUCTIVE_RULE_IMPLEMENTATION_MODEL,
  NUMERICAL_VALIDATION_EQUALS_STANDARD_CONFORMANCE,
  PARALLEL_EU_RULE_ENGINE_CREATED,
  READY_TO_RESUME_EU_C1,
  REFERENCE_IMPLEMENTED_REQUIRES_LICENSED_STANDARD_FILE,
  SECONDARY_SOURCE_REQUIRES_VALIDATION,
  STANDARD_CONTENT_IP_REVIEW_SEPARATE_FROM_ENGINEERING_VALIDATION,
  STANDARD_DOCUMENT_REQUIRED_AT_RUNTIME,
  STANDARD_DOCUMENT_REQUIRED_IN_REPOSITORY,
  STANDARD_PROFILE_CAN_BE_BOUND_WITHOUT_STANDARD_DOCUMENT,
} from "@rtb/types";
import { CONCRETE_CAPABILITY_MANIFEST, D1E_INTERNAL_ROADMAP, D1E_VALIDATION_DEBT_REGISTER } from "./capability";
import { EU_C1A_PLANNED_RULE_IDS } from "./eu-c1a";
import {
  EU_C1B_INVENTORY_RECLASS,
  EU_C1B_PARAMETER_PROVENANCE,
  EU_C1B_RULE_EVIDENCE_RECORDS,
  assertEuC1ResumeGate,
  assertEuC1bNoGuessedParameters,
  formulaFingerprint,
} from "./eu-c1b";
import { IMPLEMENTED_EU_CONCRETE_CODE_FLEXURE_METHODS } from "./eu-flexure";

describe("EOS-D1E-EU-C1B Eurocode concrete rule-authority recovery", () => {
  it("decouples licensed standard files from implementation authority without reproducing standard text", () => {
    expect(LICENSED_STANDARD_DOCUMENT_REQUIRED_FOR_IMPLEMENTATION).toBe(false);
    expect(STANDARD_DOCUMENT_REQUIRED_AT_RUNTIME).toBe(false);
    expect(STANDARD_DOCUMENT_REQUIRED_IN_REPOSITORY).toBe(false);
    expect(FULL_STANDARD_TEXT_REQUIRED_FOR_RULE_IMPLEMENTATION).toBe(false);
    expect(COPYRIGHTED_STANDARD_TEXT_REPRODUCED).toBe(false);
    expect(STANDARD_CONTENT_IP_REVIEW_SEPARATE_FROM_ENGINEERING_VALIDATION).toBe(true);
    expect(NON_REPRODUCTIVE_RULE_IMPLEMENTATION_MODEL).toBe(true);
    expect(STANDARD_PROFILE_CAN_BE_BOUND_WITHOUT_STANDARD_DOCUMENT).toBe(true);
    expect(EU_C1B_RULE_AUTHORITY_MODEL).toBe(true);
    expect(AUTHORITATIVE_STANDARD_DERIVED_REQUIRED_FOR_INITIAL_IMPLEMENTATION).toBe(false);
    expect(AUTHORITATIVE_PROFILE_VALIDATION_REQUIRED_FOR_CONFORMANCE).toBe(true);
    expect(ENGINEERING_REFERENCE_IMPLEMENTATION_EQUALS_STANDARD_CONFORMANCE).toBe(false);
    expect(NUMERICAL_VALIDATION_EQUALS_STANDARD_CONFORMANCE).toBe(false);
    expect(EU_C1B_MULTI_SOURCE_RULE_VALIDATION).toBe(true);
    expect(SECONDARY_SOURCE_REQUIRES_VALIDATION).toBe(true);
    expect(LLM_MEMORY_ONLY_RULE_ALLOWED).toBe(false);
    expect(MODEL_SUGGESTED_PARAMETER_REQUIRES_EXTERNAL_VALIDATION).toBe(true);
    expect(PARALLEL_EU_RULE_ENGINE_CREATED).toBe(false);
    expect([...IMPLEMENTED_EU_CONCRETE_CODE_FLEXURE_METHODS]).toEqual([
      "EU_RC_FLEXURE_EN1992_UNIAXIAL_MAJOR",
      "EU_RC_FLEXURE_EN1992_UNIAXIAL_MINOR",
    ]);
  });

  it("reclassifies the C1 inventory without guessing coefficients or claiming conformance", () => {
    expect(EU_C1B_RULE_EVIDENCE_RECORD).toBe(true);
    expect(EU_C1B_FORMULA_FINGERPRINT).toBe(true);
    expect(EU_C1B_PARAMETER_PROVENANCE_REQUIRED).toBe(true);
    expect(EU_C1B_RULE_CLASSIFICATION_COMPLETE).toBe(true);
    expect(EU_C1B_NDP_CLASSIFICATION_EVIDENCE_BASED).toBe(true);
    expect(DEFAULT_EU_CONCRETE_NATIONAL_ANNEX).toBe(false);
    expect(NATIONAL_ANNEX_INFERRED_FROM_LOCATION).toBe(false);
    expect(EU_C1B_INVENTORY_RECLASS).toHaveLength(EU_C1A_PLANNED_RULE_IDS.length);
    expect(EU_C1B_RULE_EVIDENCE_RECORDS.map((row) => row.ruleId)).toEqual([...EU_C1A_PLANNED_RULE_IDS]);
    const implementable = EU_C1B_INVENTORY_RECLASS.filter((row) => row.IMPLEMENTABLE);
    expect(implementable).toHaveLength(EU_C1B_IMPLEMENTABLE_REFERENCE_RULE_COUNT);
    expect(EU_C1B_IMPLEMENTABLE_NUMERICAL_RULE_COUNT).toBe(3);
    expect(implementable.map((row) => row.ruleId).sort()).toEqual([
      "EU_C1_CONCRETE_CHAR_PROPERTIES",
      "EU_C1_CONCRETE_TENSION_TREATMENT",
      "EU_C1_REINFORCEMENT_CHAR_PROPERTIES",
    ]);
    expect(EU_C1B_INVENTORY_RECLASS.find((row) => row.ruleId === "EU_C1_PARTIAL_FACTOR_GAMMA_C")?.STILL_BLOCKED).toBe(true);
    expect(EU_C1B_INVENTORY_RECLASS.find((row) => row.ruleId === "EU_C1_PARTIAL_FACTOR_GAMMA_C")?.REQUIRES_NATIONAL_CHOICE).toBe("UNRESOLVED");
    expect(EU_C1B_PARTIAL_FACTOR_GUESSED).toBe(false);
    expect(EU_C1B_STRAIN_PARAMETER_GUESSED).toBe(false);
    expect(EU_C1B_SECTION_MODEL_PARAMETER_GUESSED).toBe(false);
    expect(EU_C1B_PARAMETER_PROVENANCE.find((row) => row.parameterId === "gamma_c")?.value).toBeNull();
    expect(formulaFingerprint({
      ruleId: "EU_C1_CONCRETE_CHAR_PROPERTIES",
      operations: ["REQUIRE_EXPLICIT_GOVERNED_PROPERTY", "FORBID_GRADE_SYNTHESIS"],
      parameterIds: ["compressiveStrength", "elasticModulus"],
    })).toMatch(/^fp:[0-9a-f]{8}$/);
    assertEuC1bNoGuessedParameters();
    expect(EU_CONCRETE_STANDARD_CONFORMANCE_STATE).toBe("INTENDED_PROFILE");
    expect(EU_CONCRETE_PACK_CERTIFIED).toBe(false);
    expect(EU_CONCRETE_PRODUCT_CLAIM_LEVEL).toBe("EU_CONCRETE_MECHANICS_REFERENCE_CAPABILITY");
  });

  it("opens the C1 resume gate for the bounded non-PDF-dependent subset", () => {
    expect(EU_C1B_RULE_MATURITY_MODEL).toBe(true);
    expect(REFERENCE_IMPLEMENTED_REQUIRES_LICENSED_STANDARD_FILE).toBe(false);
    expect(EU_C1B_NUMERICAL_VALIDATION_REQUIREMENTS).toBe(true);
    expect(EU_C1B_ENGINEER_VALIDATION_REQUIRED_FOR_PROMOTION).toBe(true);
    expect(EU_C1B_CONFORMANCE_VALIDATION_STRICT).toBe(true);
    expect(EU_C1B_SOURCE_CONFLICT_FAILS_CLOSED).toBe(true);
    expect(EXTERNAL_SOFTWARE_RESULT_EQUALS_RULE_AUTHORITY).toBe(false);
    expect(EU_C1_ACCEPTANCE_POLICY_CORRECTED).toBe(true);
    expect(assertEuC1ResumeGate()).toBe("PASS");
    expect(EU_C1_RESUME_GATE).toBe("PASS");
    expect(READY_TO_RESUME_EU_C1).toBe(true);
    expect(EOS_D1E_EU_C1B_CLOSED).toBe(true);
    expect(D1E_INTERNAL_ROADMAP.find((row) => row.id === "EOS-D1E-EU-C1B")?.status).toBe("CLOSED");
    expect(D1E_INTERNAL_ROADMAP.find((row) => row.id === "EOS-D1E-EU-C1")?.status).toBe("CLOSED");
    expect(CONCRETE_CAPABILITY_MANIFEST.some((row) => row.capabilityId === "D1E.EU.C1B.RULE_AUTHORITY")).toBe(true);
    expect(CONCRETE_CAPABILITY_MANIFEST.find((row) => row.capabilityId === "D1E.EU.C1B.RULE_AUTHORITY")?.implementationState).toBe("POLICY_CORRECTION_ONLY");
    expect(D1E_VALIDATION_DEBT_REGISTER.map((row) => row.debtId)).toEqual(expect.arrayContaining([
      "D1E-EU-C1B-VD-COEFFICIENTS",
      "D1E-EU-C1B-VD-CONFORMANCE",
    ]));
  });
});
