import { describe, expect, it } from "vitest";
import {
  COPYRIGHTED_EN1992_TEXT_COMMITTED,
  DEFAULT_EU_CONCRETE_NATIONAL_ANNEX,
  D1E_EU_VALIDATION_DEBT_UPDATED,
  D1E_FROZEN_ARCHITECTURE_PRESERVED,
  EOS_D1E_EU_C1A_CLOSED,
  EU_C1A_AUTHORITY_POLICY_ENFORCED,
  EU_C1A_BASE_PROFILE_WITHOUT_ANNEX_SUPPORTED,
  EU_C1A_C1_RULE_IDS_STABLE,
  EU_C1A_C2_DEPENDENCY_INVENTORY_COMPLETE,
  EU_C1A_CONCRETE_STRAIN_PARAMETER_SET_IDENTIFIED,
  EU_C1A_CONCRETE_STRAIN_VALUE_GUESSED,
  EU_C1A_EVIDENCE_CONFLICT_DETECTION,
  EU_C1A_EXISTING_GOVERNED_EVIDENCE_FOUND,
  EU_C1A_GAMMA_C_AUTHORITY_BOUND,
  EU_C1A_GAMMA_C_DEPENDENCY_CLASS,
  EU_C1A_GAMMA_S_AUTHORITY_BOUND,
  EU_C1A_GAMMA_S_DEPENDENCY_CLASS,
  EU_C1A_HUMAN_CONFIRMATION_CONTRACT,
  EU_C1A_HUMAN_ENGINEERING_CONFIRMATION_REQUIRED,
  EU_C1A_HUMAN_INPUT_REQUIRED,
  EU_C1A_IMPLEMENTABLE_BASE_RULE_COUNT,
  EU_C1A_IMPLEMENTABLE_C1_RULE_COUNT,
  EU_C1A_MATERIAL_APPLICABILITY_MODEL,
  EU_C1A_NATIONAL_ANNEX_INFERRED_FROM_LOCATION,
  EU_C1A_NDP_CATALOG_GOVERNED,
  EU_C1A_NDP_VALUE_GUESSED,
  EU_C1A_NUMERICAL_RULE_IMPLEMENTATION_COUNT,
  EU_C1A_PARAMETER_DEPENDENCY_CLASSIFICATION_COMPLETE,
  EU_C1A_PILOT_NATIONAL_ANNEX,
  EU_C1A_REQUIRED_RULE_INVENTORY_COMPLETE,
  EU_C1A_RULE_AUTHORITY_MATRIX,
  EU_C1A_RULE_EVIDENCE_MANIFEST,
  EU_C1A_RULE_READINESS_CLASSIFICATION,
  EU_C1A_RULE_SOURCE_PRECEDENCE,
  EU_C1A_SECTION_MODEL_PARAMETER_GUESSED,
  EU_C1A_SECTION_MODEL_PARAMETER_SET_IDENTIFIED,
  EU_C1A_STANDARD_AMENDMENT_STATE,
  EU_C1A_STANDARD_EDITION,
  EU_C1A_STANDARD_FAMILY_CONFIRMED,
  EU_C1A_STANDARD_GENERATION,
  EU_C1A_STANDARD_PART_CONFIRMED,
  EU_C1A_STANDARD_PROFILE_EXACTLY_RESOLVED,
  EU_C1A_TECHNICAL_BASIS_REFERENCES_COMPLETE,
  EU_CONCRETE_IMPLEMENTATION_MATURITY,
  EU_CONCRETE_PACK_CERTIFIED,
  EU_CONCRETE_PRODUCT_CLAIM_LEVEL,
  EU_CONCRETE_STANDARD_CONFORMANCE_STATE,
  EU_CONCRETE_STANDARD_EDITION,
  EU_C1A_READY_TO_RESUME_EU_C1,
  EU_C1A_RESUME_GATE,
  IMPLEMENTED_EU_CONCRETE_CODE_FLEXURE_METHODS,
  LLM_MEMORY_ONLY_RULE_ALLOWED,
  PARALLEL_EU_C1A_ARCHITECTURE_CREATED,
  RECOMMENDED_D1E_NEXT_PHASE,
  STANDARD_TEXT_REQUIRED_BY_RUNTIME,
  UNAUTHORIZED_CAPABILITY_PROMOTION,
  UNRESOLVED_EVIDENCE_CONFLICT_FAILS_CLOSED,
} from "@rtb/types";
import { CONCRETE_CAPABILITY_MANIFEST, D1E_INTERNAL_ROADMAP, D1E_VALIDATION_DEBT_REGISTER } from "./capability";
import {
  EU_C1A_C2_DEPENDENCY_INVENTORY,
  EU_C1A_EXISTING_GOVERNED_EVIDENCE,
  EU_C1A_HUMAN_CONFIRMATION_TEMPLATE,
  EU_C1A_HUMAN_INPUT_FIELDS,
  EU_C1A_PLANNED_RULE_IDS,
  EU_C1A_PRESENT_BLOCKERS,
  EU_C1A_REQUIRED_RULE_CATEGORIES,
  EU_C1A_RULE_AUTHORITY_MATRIX_ROWS,
  EU_C1A_RULE_EVIDENCE_RECORDS,
  assertEuC1aResumeGate,
  assertEuC1aEvidenceConflictsFailClosed,
  assertEuC1aHumanConfirmationContract,
  assertHumanConfirmedEuC1aProfile,
} from "./eu-c1a";
import { GOVERNED_EU_CONCRETE_NDP_CATALOG } from "./eu-standard";
import { IMPLEMENTED_EU_CONCRETE_CODE_FLEXURE_METHODS as IMPLEMENTED_FLEXURE } from "./eu-flexure";

describe("EOS-D1E-EU-C1A Eurocode concrete rule-evidence recovery", () => {
  it("preserves the frozen D1E architecture and does not implement numerical rules", () => {
    expect(D1E_FROZEN_ARCHITECTURE_PRESERVED).toBe(true);
    expect(PARALLEL_EU_C1A_ARCHITECTURE_CREATED).toBe(false);
    expect(EU_C1A_NUMERICAL_RULE_IMPLEMENTATION_COUNT).toBe(0);
    expect(IMPLEMENTED_EU_CONCRETE_CODE_FLEXURE_METHODS).toBe("NONE");
    expect(IMPLEMENTED_FLEXURE).toBe("NONE");
    expect(EU_CONCRETE_PRODUCT_CLAIM_LEVEL).toBe("EU_CONCRETE_MECHANICS_REFERENCE_CAPABILITY");
    expect(EU_CONCRETE_STANDARD_CONFORMANCE_STATE).toBe("INTENDED_PROFILE");
    expect(EU_CONCRETE_PACK_CERTIFIED).toBe(false);
    expect(EU_CONCRETE_IMPLEMENTATION_MATURITY).toBe("FRAMEWORK_PLUS_COMMON_MECHANICS");
    expect(UNAUTHORIZED_CAPABILITY_PROMOTION).toBe(false);
  });

  it("records existing governed evidence without resolving generation or edition", () => {
    expect(EU_C1A_EXISTING_GOVERNED_EVIDENCE_FOUND).toBe(true);
    expect(EU_C1A_EXISTING_GOVERNED_EVIDENCE.length).toBeGreaterThan(0);
    expect(EU_C1A_STANDARD_FAMILY_CONFIRMED).toBe(true);
    expect(EU_C1A_STANDARD_PART_CONFIRMED).toBe(true);
    expect(EU_C1A_STANDARD_GENERATION).toBe("UNKNOWN_PENDING_CONFIRMATION");
    expect(EU_C1A_STANDARD_EDITION).toBe("UNKNOWN_PENDING_CONFIRMATION");
    expect(EU_C1A_STANDARD_AMENDMENT_STATE).toBe("UNKNOWN_PENDING_CONFIRMATION");
    expect(EU_CONCRETE_STANDARD_EDITION).toBe("UNKNOWN_PENDING_CONFIRMATION");
    expect(EU_C1A_STANDARD_PROFILE_EXACTLY_RESOLVED).toBe(false);
    expect(EU_C1A_HUMAN_INPUT_REQUIRED).toBe(true);
  });

  it("publishes a human confirmation contract and evidence manifest without guessed values", () => {
    expect(EU_C1A_HUMAN_CONFIRMATION_CONTRACT).toBe(true);
    expect(EU_C1A_HUMAN_ENGINEERING_CONFIRMATION_REQUIRED).toBe(true);
    expect(EU_C1A_HUMAN_INPUT_FIELDS).toEqual([
      "standardFamily",
      "standardPart",
      "standardGeneration",
      "standardEdition",
      "amendmentState",
      "corrigendumState",
      "technicalBasisIdentifier",
      "authoritySourceIdentifier",
    ]);
    expect(EU_C1A_HUMAN_CONFIRMATION_TEMPLATE.standardFamily).toBe("EN 1992");
    expect(EU_C1A_HUMAN_CONFIRMATION_TEMPLATE.standardPart).toBe("EN_1992_1_1");
    expect(EU_C1A_HUMAN_CONFIRMATION_TEMPLATE.standardEdition).toBeNull();
    expect(EU_C1A_RULE_EVIDENCE_MANIFEST).toBe(true);
    expect(EU_C1A_RULE_EVIDENCE_RECORDS).toHaveLength(EU_C1A_PLANNED_RULE_IDS.length);
    expect(EU_C1A_RULE_EVIDENCE_RECORDS.every((row) => row.parameterValue === null)).toBe(true);
    expect(EU_C1A_RULE_EVIDENCE_RECORDS.every((row) => row.dependencyClass === "UNRESOLVED")).toBe(true);
    expect(EU_C1A_RULE_EVIDENCE_RECORDS.every((row) => row.readyForImplementation === false)).toBe(true);
    assertEuC1aHumanConfirmationContract();
    expect(() => assertHumanConfirmedEuC1aProfile(null)).toThrow(/HUMAN_CONFIRMATION_REQUIRED/);
  });

  it("classifies C1 parameters as unresolved and keeps NDP/annex unbound", () => {
    expect(EU_C1A_PARAMETER_DEPENDENCY_CLASSIFICATION_COMPLETE).toBe(true);
    expect(EU_C1A_REQUIRED_RULE_INVENTORY_COMPLETE).toBe(true);
    expect(EU_C1A_REQUIRED_RULE_CATEGORIES).toHaveLength(10);
    expect(EU_C1A_GAMMA_C_DEPENDENCY_CLASS).toBe("UNRESOLVED");
    expect(EU_C1A_GAMMA_C_AUTHORITY_BOUND).toBe(false);
    expect(EU_C1A_GAMMA_S_DEPENDENCY_CLASS).toBe("UNRESOLVED");
    expect(EU_C1A_GAMMA_S_AUTHORITY_BOUND).toBe(false);
    expect(EU_C1A_CONCRETE_STRAIN_PARAMETER_SET_IDENTIFIED).toBe(false);
    expect(EU_C1A_CONCRETE_STRAIN_VALUE_GUESSED).toBe(false);
    expect(EU_C1A_SECTION_MODEL_PARAMETER_SET_IDENTIFIED).toBe(false);
    expect(EU_C1A_SECTION_MODEL_PARAMETER_GUESSED).toBe(false);
    expect(EU_C1A_MATERIAL_APPLICABILITY_MODEL).toBe(true);
    expect(DEFAULT_EU_CONCRETE_NATIONAL_ANNEX).toBe(false);
    expect(EU_C1A_NATIONAL_ANNEX_INFERRED_FROM_LOCATION).toBe(false);
    expect(EU_C1A_BASE_PROFILE_WITHOUT_ANNEX_SUPPORTED).toBe(true);
    expect(EU_C1A_PILOT_NATIONAL_ANNEX).toBe("UNBOUND");
    expect(EU_C1A_NDP_CATALOG_GOVERNED).toBe(true);
    expect(GOVERNED_EU_CONCRETE_NDP_CATALOG).toEqual([]);
    expect(EU_C1A_NDP_VALUE_GUESSED).toBe(false);
  });

  it("keeps the C1 resume gate closed until human-confirmed profile evidence exists", () => {
    expect(EU_C1A_AUTHORITY_POLICY_ENFORCED).toBe(true);
    expect(LLM_MEMORY_ONLY_RULE_ALLOWED).toBe(false);
    expect(STANDARD_TEXT_REQUIRED_BY_RUNTIME).toBe(false);
    expect(COPYRIGHTED_EN1992_TEXT_COMMITTED).toBe(false);
    expect(EU_C1A_RULE_SOURCE_PRECEDENCE).toBe("PASS");
    expect(EU_C1A_EVIDENCE_CONFLICT_DETECTION).toBe(true);
    expect(UNRESOLVED_EVIDENCE_CONFLICT_FAILS_CLOSED).toBe(true);
    expect(EU_C1A_C1_RULE_IDS_STABLE).toBe(true);
    expect(EU_C1A_TECHNICAL_BASIS_REFERENCES_COMPLETE).toBe(true);
    expect(EU_C1A_RULE_AUTHORITY_MATRIX).toBe(true);
    expect(EU_C1A_RULE_READINESS_CLASSIFICATION).toBe(true);
    expect(EU_C1A_RULE_AUTHORITY_MATRIX_ROWS).toHaveLength(12);
    expect(EU_C1A_RULE_AUTHORITY_MATRIX_ROWS.every((row) => row.readiness !== "READY_FOR_IMPLEMENTATION")).toBe(true);
    expect(EU_C1A_IMPLEMENTABLE_BASE_RULE_COUNT).toBe(0);
    expect(EU_C1A_IMPLEMENTABLE_C1_RULE_COUNT).toBe(0);
    expect(EU_C1A_C2_DEPENDENCY_INVENTORY_COMPLETE).toBe(true);
    expect(EU_C1A_C2_DEPENDENCY_INVENTORY.filter((row) => row.classification === "UNBOUND").length).toBeGreaterThan(0);
    expect(EU_C1A_RESUME_GATE).toBe("FAIL");
    expect(assertEuC1aResumeGate()).toBe("FAIL");
    assertEuC1aEvidenceConflictsFailClosed();
    expect(EU_C1A_PRESENT_BLOCKERS).toEqual([
      "MISSING_STANDARD_GENERATION",
      "MISSING_STANDARD_EDITION",
      "MISSING_AMENDMENT_STATE",
      "MISSING_RULE_AUTHORITY",
      "MISSING_PARTIAL_FACTOR_AUTHORITY",
      "MISSING_STRAIN_RULE_AUTHORITY",
      "MISSING_SECTION_MODEL_AUTHORITY",
      "HUMAN_CONFIRMATION_REQUIRED",
    ]);
    expect(EU_C1A_READY_TO_RESUME_EU_C1).toBe(false);
    expect(EOS_D1E_EU_C1A_CLOSED).toBe(false);
    expect(RECOMMENDED_D1E_NEXT_PHASE).toBe("EOS-D1E-EU-C1");
    expect(D1E_INTERNAL_ROADMAP.find((row) => row.id === "EOS-D1E-EU-C1A")?.status).toBe("BLOCKED");
    expect(D1E_INTERNAL_ROADMAP.find((row) => row.id === "EOS-D1E-EU-C1")?.status).toBe("THIS_PHASE");
    expect(CONCRETE_CAPABILITY_MANIFEST.some((row) => row.capabilityId === "D1E.EU.C1A.RULE_EVIDENCE")).toBe(true);
    expect(CONCRETE_CAPABILITY_MANIFEST.find((row) => row.capabilityId === "D1E.EU.C1A.RULE_EVIDENCE")?.implementationState).toBe("EVIDENCE_BINDING_ONLY");
    expect(D1E_EU_VALIDATION_DEBT_UPDATED).toBe(true);
    expect(D1E_VALIDATION_DEBT_REGISTER.map((row) => row.debtId)).toEqual(expect.arrayContaining([
      "D1E-EU-C1A-VD-PROFILE",
      "D1E-EU-C1A-VD-HUMAN",
      "D1E-EU-C1A-VD-PARAMETER-CLASS",
    ]));
  });
});
