import { describe, expect, it } from "vitest";
import {
  D1C_TORSIONAL_ACTION_ID,
  EU_C5_IMPLEMENTED_METHOD_IDS,
  EU_C5_T2_FINAL_EXTERNAL_ACTION_REQUIRED,
  EU_C5_T2_FINAL_TORSION_DISPOSITION,
  EU_C5_T2_IMPLEMENTATION_AUTHORIZED,
  EU_C5_T2_SELECTED_PROFILE_ID,
  NUMERICAL_EU_CONCRETE_TORSION_IMPLEMENTED,
} from "@rtb/types";

describe("EOS-D1E-EU-C5-T2 profile binding decision", () => {
  it("binds no national annex and does not implement torsion", () => {
    expect(EU_C5_T2_SELECTED_PROFILE_ID).toBe("NONE");
    expect(EU_C5_T2_IMPLEMENTATION_AUTHORIZED).toBe(false);
    expect(EU_C5_T2_FINAL_TORSION_DISPOSITION).toBe("BLOCKED_REQUIRED_NATIONAL_ANNEX");
    expect(EU_C5_T2_FINAL_EXTERNAL_ACTION_REQUIRED).toBe("LICENSED_OR_VALIDATED_PROFILE_INPUT_REQUIRED");
    expect(NUMERICAL_EU_CONCRETE_TORSION_IMPLEMENTED).toBe(true);
    expect(D1C_TORSIONAL_ACTION_ID).toBe("MEMBER_TORSION");
    expect(EU_C5_IMPLEMENTED_METHOD_IDS).toContain("EU_RC_SHEAR_EN1992_WITHOUT_TRANSVERSE_REINFORCEMENT");
    expect(EU_C5_IMPLEMENTED_METHOD_IDS).toContain("EU_RC_PUNCHING_EN1992_INTERIOR_RECTANGULAR_CONCRETE");
  });
});
