import type { DeliverableDefinition, DeliverableMaturityProfile, MaturityDimension, MaturityPurpose } from "./types";

export const DEFAULT_DELIVERABLE_MATURITY_PROFILE_ID = "EOS-DEFAULT-DELIVERABLE-MATURITY";
export const DEFAULT_DELIVERABLE_MATURITY_PROFILE_VERSION = "v1";

const ALL_DIMENSIONS: readonly MaturityDimension[] = [
  "CONTENT",
  "TRACEABILITY",
  "COORDINATION",
  "REVIEW",
  "CONFIGURATION",
  "SUPPORTING_EVIDENCE",
];

export const DEFAULT_DELIVERABLE_MATURITY_PROFILE: DeliverableMaturityProfile = {
  profileId: DEFAULT_DELIVERABLE_MATURITY_PROFILE_ID,
  profileVersion: DEFAULT_DELIVERABLE_MATURITY_PROFILE_VERSION,
  name: "Default deliverable maturity",
  origin: "TEMPLATE",
  dimensions: ALL_DIMENSIONS,
  requiredDimensionsByPurpose: {
    FOR_INTERNAL_COORDINATION: ["CONTENT", "COORDINATION"],
    FOR_ENGINEERING_REVIEW: ["CONTENT", "TRACEABILITY", "COORDINATION", "REVIEW", "CONFIGURATION", "SUPPORTING_EVIDENCE"],
    FOR_BASELINE: ALL_DIMENSIONS,
    FOR_CONSTRUCTION_USE: ALL_DIMENSIONS,
    FOR_COMMISSIONING: ["CONTENT", "REVIEW", "CONFIGURATION", "SUPPORTING_EVIDENCE"],
    FOR_OPERATIONS: ["CONTENT", "CONFIGURATION", "REVIEW"],
  },
};

export const EXAMPLE_FEED_DELIVERABLE_DEFINITIONS: readonly DeliverableDefinition[] = [
  {
    definitionId: "EOS-DLV-PROC-DB-FEED",
    definitionVersion: "v1",
    code: "PROC-DB-FEED",
    name: "Process Design Basis",
    purpose: "EXAMPLE FEED process design-basis expectation. Not mandatory for every FEED project.",
    origin: "EXAMPLE",
    artifactClasses: ["document", "decision"],
    responsibleDiscipline: "PROCESS",
    contributingDisciplines: ["MECHANICAL", "PIPING"],
    lifecycleStages: ["FEED"],
    multidisciplinary: true,
    requiredRoles: ["PRIMARY"],
    coordinationRequired: true,
    analysisRequired: false,
    reviewRequired: true,
    traceabilityRequired: true,
    configurationRequired: false,
  },
  {
    definitionId: "EOS-DLV-MECH-DS-FEED",
    definitionVersion: "v1",
    code: "MECH-DS-FEED",
    name: "Equipment Datasheet Package",
    purpose: "EXAMPLE FEED equipment datasheet expectation.",
    origin: "EXAMPLE",
    artifactClasses: ["document"],
    responsibleDiscipline: "MECHANICAL",
    contributingDisciplines: ["PROCESS"],
    lifecycleStages: ["FEED"],
    multidisciplinary: false,
    requiredRoles: ["PRIMARY"],
    coordinationRequired: false,
    analysisRequired: false,
    reviewRequired: true,
    traceabilityRequired: false,
    configurationRequired: false,
  },
  {
    definitionId: "EOS-DLV-PIPE-DB-FEED",
    definitionVersion: "v1",
    code: "PIPE-DB-FEED",
    name: "Piping Design Basis",
    purpose: "EXAMPLE FEED piping design-basis expectation.",
    origin: "EXAMPLE",
    artifactClasses: ["document"],
    responsibleDiscipline: "PIPING",
    contributingDisciplines: ["PROCESS", "MECHANICAL"],
    lifecycleStages: ["FEED"],
    multidisciplinary: true,
    requiredRoles: ["PRIMARY"],
    coordinationRequired: true,
    analysisRequired: false,
    reviewRequired: true,
    traceabilityRequired: false,
    configurationRequired: false,
  },
  {
    definitionId: "EOS-DLV-STR-DC-FEED",
    definitionVersion: "v1",
    code: "STR-DC-FEED",
    name: "Structural Design Criteria",
    purpose: "EXAMPLE FEED structural design-criteria expectation.",
    origin: "EXAMPLE",
    artifactClasses: ["document"],
    responsibleDiscipline: "STRUCTURAL",
    contributingDisciplines: ["CIVIL"],
    lifecycleStages: ["FEED"],
    multidisciplinary: false,
    requiredRoles: ["PRIMARY"],
    coordinationRequired: false,
    analysisRequired: false,
    reviewRequired: true,
    traceabilityRequired: true,
    configurationRequired: false,
  },
  {
    definitionId: "EOS-DLV-STR-ANL-FEED",
    definitionVersion: "v1",
    code: "STR-ANL-FEED",
    name: "Structural Analysis Package",
    purpose: "EXAMPLE FEED structural analysis package. May bind Analysis Result + Review without a placeholder document.",
    origin: "EXAMPLE",
    artifactClasses: ["analysis_result", "review_package", "document"],
    responsibleDiscipline: "STRUCTURAL",
    contributingDisciplines: ["MECHANICAL", "CIVIL"],
    lifecycleStages: ["FEED"],
    multidisciplinary: true,
    requiredRoles: ["PRIMARY", "CALCULATION", "REVIEW"],
    coordinationRequired: true,
    analysisRequired: true,
    reviewRequired: true,
    traceabilityRequired: true,
    configurationRequired: true,
  },
  {
    definitionId: "EOS-DLV-ELEC-DB-FEED",
    definitionVersion: "v1",
    code: "ELEC-DB-FEED",
    name: "Electrical Design Basis",
    purpose: "EXAMPLE FEED electrical design-basis expectation.",
    origin: "EXAMPLE",
    artifactClasses: ["document"],
    responsibleDiscipline: "ELECTRICAL",
    contributingDisciplines: [],
    lifecycleStages: ["FEED"],
    multidisciplinary: false,
    requiredRoles: ["PRIMARY"],
    coordinationRequired: false,
    analysisRequired: false,
    reviewRequired: true,
    traceabilityRequired: false,
    configurationRequired: false,
  },
  {
    definitionId: "EOS-DLV-IANDC-PH-FEED",
    definitionVersion: "v1",
    code: "IANDC-PH-FEED",
    name: "Instrumentation Philosophy",
    purpose: "EXAMPLE FEED instrumentation philosophy expectation.",
    origin: "EXAMPLE",
    artifactClasses: ["document"],
    responsibleDiscipline: "INSTRUMENTATION_CONTROL",
    contributingDisciplines: ["PROCESS", "ELECTRICAL"],
    lifecycleStages: ["FEED"],
    multidisciplinary: true,
    requiredRoles: ["PRIMARY"],
    coordinationRequired: true,
    analysisRequired: false,
    reviewRequired: true,
    traceabilityRequired: false,
    configurationRequired: false,
  },
  {
    definitionId: "EOS-DLV-IFACE-PKG-FEED",
    definitionVersion: "v1",
    code: "IFACE-PKG-FEED",
    name: "Interface Data Package",
    purpose: "EXAMPLE multidisciplinary interface package. Coordination is not proven by document count.",
    origin: "EXAMPLE",
    artifactClasses: ["interface", "register", "document"],
    responsibleDiscipline: "PROCESS",
    contributingDisciplines: ["PROCESS", "MECHANICAL", "PIPING", "STRUCTURAL"],
    lifecycleStages: ["FEED"],
    multidisciplinary: true,
    requiredRoles: ["PRIMARY"],
    coordinationRequired: true,
    analysisRequired: false,
    reviewRequired: false,
    traceabilityRequired: false,
    configurationRequired: false,
  },
  {
    definitionId: "EOS-DLV-REV-FEED",
    definitionVersion: "v1",
    code: "REV-FEED",
    name: "Engineering Review Package",
    purpose: "EXAMPLE FEED Review Package expectation. Review remains the owner of Findings.",
    origin: "EXAMPLE",
    artifactClasses: ["review_package"],
    responsibleDiscipline: "PROCESS",
    contributingDisciplines: ["STRUCTURAL", "MECHANICAL"],
    lifecycleStages: ["FEED"],
    multidisciplinary: true,
    requiredRoles: ["REVIEW"],
    coordinationRequired: false,
    analysisRequired: false,
    reviewRequired: true,
    traceabilityRequired: false,
    configurationRequired: false,
  },
  {
    definitionId: "EOS-DLV-CFG-FEED",
    definitionVersion: "v1",
    code: "CFG-FEED",
    name: "FEED Configuration Baseline",
    purpose: "EXAMPLE FEED configuration baseline expectation. Uses canonical Configuration, not a filename.",
    origin: "EXAMPLE",
    artifactClasses: ["configuration_baseline"],
    responsibleDiscipline: "PROCESS",
    contributingDisciplines: [],
    lifecycleStages: ["FEED"],
    multidisciplinary: false,
    requiredRoles: ["CONFIGURATION"],
    coordinationRequired: false,
    analysisRequired: false,
    reviewRequired: false,
    traceabilityRequired: false,
    configurationRequired: true,
  },
];

export function deliverableDefinitionById(id: string, version: string): DeliverableDefinition | null {
  return EXAMPLE_FEED_DELIVERABLE_DEFINITIONS.find((row) => row.definitionId === id && row.definitionVersion === version) ?? null;
}

export function deliverableDefinitionByCode(code: string): DeliverableDefinition | null {
  return EXAMPLE_FEED_DELIVERABLE_DEFINITIONS.find((row) => row.code === code) ?? null;
}

export function maturityProfileById(id: string, version: string): DeliverableMaturityProfile | null {
  if (id === DEFAULT_DELIVERABLE_MATURITY_PROFILE_ID && version === DEFAULT_DELIVERABLE_MATURITY_PROFILE_VERSION) {
    return DEFAULT_DELIVERABLE_MATURITY_PROFILE;
  }
  return null;
}

export function requiredDimensionsFor(purpose: MaturityPurpose, profile: DeliverableMaturityProfile = DEFAULT_DELIVERABLE_MATURITY_PROFILE): readonly MaturityDimension[] {
  return profile.requiredDimensionsByPurpose[purpose] ?? ["CONTENT"];
}

export function unknownMaturityProfileRejected(id: string, version: string): boolean {
  return maturityProfileById(id, version) == null;
}
