export const EU_MEMBER_IMPLEMENTATION_VERSION = "eu-member-1.0.0" as const;
export const EU_MEMBER_TOOL_REF = "EOS_EU_STEEL_MEMBER_DESIGN" as const;

export const EU_MEMBER_CHECK_TAXONOMY = [
  "TENSION",
  "COMPRESSION",
  "COMPRESSION_STABILITY",
  "BENDING_MAJOR",
  "BENDING_MINOR",
  "LTB",
  "SHEAR_MAJOR",
  "SHEAR_MINOR",
  "WEB_STABILITY",
  "COMBINED_ACTION",
  "DEFLECTION",
  "OTHER_SERVICEABILITY",
] as const;

export const EU_MEMBER_UNSUPPORTED_METHODS = {
  EN1993_CODE_PROFILE_CAPACITY: "VALIDATION_REQUIRED",
  NUMERICAL_INTERACTION: false,
  DEFAULT_LN: false,
  VIBRATION: false,
  CONNECTIONS: false,
  FOUNDATIONS: false,
  GENERAL_FEA: false,
} as const;
