import type {
  BusinessWorkCapacityIngestInput,
  BusinessWorkCostIngestInput,
  BusinessWorkItemIngestInput,
  BusinessWorkMilestoneIngestInput,
} from "@rtb/types";

export const OPERATIONS_DEMO_FIXTURE = "bos-7-work-operations";

export const OPERATIONS_DEMO_WORK: BusinessWorkItemIngestInput[] = [
  {
    reference: "JOB-HARBOUR-01",
    name: "Harbour inspection mobilisation",
    description: "Customer job with overdue milestone and cost ahead of progress.",
    workType: "customer_job",
    owner: "Operations lead",
    status: "active",
    plannedStart: "2026-06-01",
    plannedFinish: "2026-07-31",
    actualStart: "2026-06-03",
    progressBps: "3500",
    currency: "AUD",
    contractedValueMinor: "18000000",
    budgetCostMinor: "10000000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-harbour",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, customerSourceRef: "bos-5-demo-customer-harbour" },
  },
  {
    reference: "PKG-NORTHBOUND-01",
    name: "Northbound delivery package",
    description: "Won opportunity linked to work. Engineering project stored as a stable reference only.",
    workType: "delivery_package",
    owner: "Delivery manager",
    status: "active",
    plannedStart: "2026-07-01",
    plannedFinish: "2026-10-31",
    actualStart: "2026-07-04",
    progressBps: "6200",
    currency: "AUD",
    contractedValueMinor: "80000000",
    budgetCostMinor: "62000000",
    linkedEngineeringProjectId: "eng-project-northbound-ref",
    linkedEngineeringProjectRef: "EOS-PRJ-NORTHBOUND",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-northbound",
    isDemo: true,
    provenance: {
      fixture: OPERATIONS_DEMO_FIXTURE,
      customerSourceRef: "bos-5-demo-customer-northbound",
      opportunitySourceRef: "bos-3-demo-opp-northbound",
      engineeringLinkMode: "stable_reference",
    },
  },
  {
    reference: "INT-OPS-PLATFORM",
    name: "Internal operating cadence",
    description: "Internal initiative with no customer and no progress evidence.",
    workType: "internal_initiative",
    owner: "Owner",
    status: "planned",
    plannedStart: "2026-08-01",
    plannedFinish: "2026-12-31",
    currency: "AUD",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-internal",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, noCustomer: true, noProgress: true },
  },
  {
    reference: "JOB-GRID-HOLD",
    name: "Grid expansion hold",
    description: "Blocked work with no owner.",
    workType: "business_project",
    status: "on_hold",
    plannedStart: "2026-05-01",
    plannedFinish: "2026-09-15",
    progressBps: "2000",
    currency: "AUD",
    budgetCostMinor: "50000000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-grid",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, customerSourceRef: "bos-5-demo-customer-grid", noOwner: true },
  },
  {
    reference: "JOB-METRO-DONE",
    name: "Metro interchange close-out",
    description: "Completed work with an unresolved linked action.",
    workType: "service_engagement",
    owner: "Close-out lead",
    status: "completed",
    plannedStart: "2026-03-01",
    plannedFinish: "2026-06-30",
    actualStart: "2026-03-02",
    actualFinish: "2026-06-28",
    progressBps: "10000",
    currency: "AUD",
    contractedValueMinor: "255000000",
    budgetCostMinor: "200000000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-metro",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, customerSourceRef: "bos-5-demo-customer-metro", unresolvedAction: true },
  },
  {
    reference: "JOB-USD-TRAVEL",
    name: "NZ inspection travel",
    description: "USD operational cost on USD-currency work.",
    workType: "service_engagement",
    owner: "Travel desk",
    status: "active",
    plannedFinish: "2026-09-30",
    progressBps: "4000",
    currency: "USD",
    budgetCostMinor: "800000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-usd",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, multiCurrency: true },
  },
  {
    reference: "JOB-STALE-01",
    name: "Stale mobilisation review",
    workType: "customer_job",
    owner: "Owner",
    status: "active",
    plannedFinish: "2026-11-30",
    progressBps: "1500",
    currency: "AUD",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-stale",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, customerSourceRef: "bos-5-demo-customer-harbour", stale: true },
  },
  {
    reference: "JOB-COST-ONLY",
    name: "Cost without progress",
    workType: "customer_job",
    owner: "Owner",
    status: "active",
    plannedFinish: "2026-10-15",
    currency: "AUD",
    budgetCostMinor: "5000000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-cost-only",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, customerSourceRef: "bos-5-demo-customer-harbour", noProgress: true },
  },
  {
    reference: "JOB-PROGRESS-ONLY",
    name: "Progress without cost",
    workType: "customer_job",
    owner: "Owner",
    status: "active",
    plannedFinish: "2026-10-15",
    progressBps: "5000",
    currency: "AUD",
    budgetCostMinor: "4000000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-progress-only",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, customerSourceRef: "bos-5-demo-customer-northbound", noCost: true },
  },
  {
    reference: "JOB-ZERO-BUDGET",
    name: "Zero budget initiative",
    workType: "internal_initiative",
    owner: "Owner",
    status: "active",
    plannedFinish: "2026-12-01",
    progressBps: "2500",
    currency: "AUD",
    budgetCostMinor: "0",
    sourceType: "demo",
    sourceRef: "bos-7-demo-work-zero-budget",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, zeroBudget: true },
  },
];

export const OPERATIONS_DEMO_MILESTONES: Array<BusinessWorkMilestoneIngestInput & { workSourceRef: string }> = [
  {
    workSourceRef: "bos-7-demo-work-harbour",
    workId: "lookup",
    name: "Site access approved",
    dueAt: "2026-07-15",
    status: "in_progress",
    weightBps: "4000",
    owner: "Operations lead",
    sourceType: "demo",
    sourceRef: "bos-7-demo-ms-harbour-access",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, overdue: true },
  },
  {
    workSourceRef: "bos-7-demo-work-harbour",
    workId: "lookup",
    name: "Field pack complete",
    dueAt: "2026-08-15",
    status: "not_started",
    weightBps: "6000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-ms-harbour-pack",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
  {
    workSourceRef: "bos-7-demo-work-northbound",
    workId: "lookup",
    name: "Package kickoff",
    dueAt: "2026-07-10",
    completedAt: "2026-07-09",
    status: "completed",
    weightBps: "2000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-ms-northbound-kickoff",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
  {
    workSourceRef: "bos-7-demo-work-northbound",
    workId: "lookup",
    name: "Delivery gate",
    dueAt: "2026-10-15",
    status: "in_progress",
    weightBps: "8000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-ms-northbound-gate",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
  {
    workSourceRef: "bos-7-demo-work-grid",
    workId: "lookup",
    name: "Hold review",
    dueAt: "2026-08-01",
    status: "blocked",
    sourceType: "demo",
    sourceRef: "bos-7-demo-ms-grid-hold",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, blocked: true },
  },
];

export const OPERATIONS_DEMO_COSTS: Array<BusinessWorkCostIngestInput & { workSourceRef: string }> = [
  {
    workSourceRef: "bos-7-demo-work-harbour",
    workId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    costType: "labour",
    amountMinor: "8000000",
    currency: "AUD",
    valueState: "actual",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-harbour-labour-actual",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
  {
    workSourceRef: "bos-7-demo-work-harbour",
    workId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    costType: "subcontractor",
    amountMinor: "2500000",
    currency: "AUD",
    valueState: "actual",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-harbour-sub-actual",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
  {
    workSourceRef: "bos-7-demo-work-harbour",
    workId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    costType: "labour",
    amountMinor: "4000000",
    currency: "AUD",
    valueState: "forecast",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-harbour-labour-forecast",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, notRealized: true },
  },
  {
    workSourceRef: "bos-7-demo-work-harbour",
    workId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    costType: "labour",
    amountMinor: "10000000",
    currency: "AUD",
    valueState: "budget",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-harbour-labour-budget",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, notRealized: true },
  },
  {
    workSourceRef: "bos-7-demo-work-northbound",
    workId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    costType: "material",
    amountMinor: "30000000",
    currency: "AUD",
    valueState: "actual",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-northbound-material",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
  {
    workSourceRef: "bos-7-demo-work-usd",
    workId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    costType: "travel",
    amountMinor: "210000",
    currency: "USD",
    valueState: "actual",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-usd-travel",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
  {
    workSourceRef: "bos-7-demo-work-usd",
    workId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    costType: "travel",
    amountMinor: "90000",
    currency: "AUD",
    valueState: "actual",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-usd-mixed-aud",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, mixedCurrency: true },
  },
  {
    workSourceRef: "bos-7-demo-work-cost-only",
    workId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    costType: "equipment",
    amountMinor: "1200000",
    currency: "AUD",
    valueState: "actual",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-only-equipment",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
  {
    workSourceRef: "bos-7-demo-work-zero-budget",
    workId: "lookup",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    costType: "other_direct",
    amountMinor: "250000",
    currency: "AUD",
    valueState: "actual",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-zero-budget",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
  {
    workSourceRef: "bos-7-demo-work-metro",
    workId: "lookup",
    periodStart: "2026-04-01",
    periodEnd: "2026-06-30",
    costType: "subcontractor",
    amountMinor: "198000000",
    currency: "AUD",
    valueState: "actual",
    sourceType: "demo",
    sourceRef: "bos-7-demo-cost-metro-actual",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
];

export const OPERATIONS_DEMO_CAPACITY: BusinessWorkCapacityIngestInput[] = [
  {
    dimensionType: "team",
    dimensionRef: "delivery-team",
    dimensionName: "Delivery team",
    periodStart: "2026-08-01",
    periodEnd: "2026-08-31",
    availableHoursMinor: "40000",
    committedHoursMinor: "52000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-capacity-overcommit",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, overcommitted: true },
  },
  {
    dimensionType: "period",
    dimensionRef: "2026-08",
    dimensionName: "August 2026",
    periodStart: "2026-08-01",
    periodEnd: "2026-08-31",
    sourceType: "demo",
    sourceRef: "bos-7-demo-capacity-unknown",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE, missingHours: true },
  },
  {
    dimensionType: "work_item",
    dimensionRef: "bos-7-demo-work-northbound",
    dimensionName: "Northbound delivery package",
    periodStart: "2026-08-01",
    periodEnd: "2026-08-31",
    availableHoursMinor: "16000",
    committedHoursMinor: "12000",
    sourceType: "demo",
    sourceRef: "bos-7-demo-capacity-northbound",
    isDemo: true,
    provenance: { fixture: OPERATIONS_DEMO_FIXTURE },
  },
];
