export const PHASE_9G_INSPECTION_OFFLINE_SYNC_GATES = [
  ["A", "Repository and build identity"],
  ["B", "Prior phase regression"],
  ["C", "Project Intelligence v1 tag integrity"],
  ["D", "Engineering Mobile Offline SDK"],
  ["E", "Durable local store and schema migration"],
  ["F", "Encryption and key lifecycle"],
  ["G", "Offline packages"],
  ["H", "Local command queue"],
  ["I", "Evidence upload queue"],
  ["J", "Sync coordinator"],
  ["K", "Connectivity model"],
  ["L", "Deterministic conflict engine"],
  ["M", "Multi-device reconciliation"],
  ["N", "Offline entitlement snapshot"],
  ["O", "Purge and storage management"],
  ["P", "Pack-aware mobile reporting"],
  ["Q", "Sync UI"],
  ["R", "Sync events and audit"],
  ["S", "Service-worker / recovery contracts"],
  ["T", "Offline unit and architecture tests"],
  ["U", "Tenant and workspace isolation"],
  ["V", "Privacy and threat model"],
  ["W", "Browser E2E offline"],
  ["X", "Device evidence documentation"],
  ["Y", "No AI Vision"],
  ["Z", "No Asset Intelligence / Digital Twin ownership"],
  ["AA", "Secret exposure"],
  ["AB", "Artifact identity"],
  ["AC", "Release eligibility and phase9H readiness"],
] as const;

export type Phase9gGateId = (typeof PHASE_9G_INSPECTION_OFFLINE_SYNC_GATES)[number][0];
