export const PHASE_8E_FINDINGS_INTELLIGENCE_GATES = [
  ["A", "Repository and build identity"],
  ["B", "Phase 7B through 8D regression"],
  ["C", "Hosted schema and migration identity"],
  ["D", "Real-JWT RLS"],
  ["E", "Feature registration"],
  ["F", "Shared Engineering Services"],
  ["G", "Document candidate intake"],
  ["H", "Meeting candidate intake"],
  ["I", "Manual candidate intake"],
  ["J", "Lifecycle transitions"],
  ["K", "Evidence and citations"],
  ["L", "Classification and severity"],
  ["M", "Duplicate detection"],
  ["N", "Conflict handling"],
  ["O", "Review queue"],
  ["P", "Human approval"],
  ["Q", "Core conversion"],
  ["R", "Backlinks and audit"],
  ["S", "Pattern Intelligence"],
  ["T", "Reporting handoff"],
  ["U", "Entitlement and isolation"],
  ["V", "HTTP contracts"],
  ["W", "Platform AI governance"],
  ["X", "Browser E2E"],
  ["Y", "Accessibility"],
  ["Z", "Responsive layouts"],
  ["AA", "Performance baseline"],
  ["AB", "Secret exposure"],
  ["AC", "Artifact identity and release eligibility"],
] as const;

export type Phase8eGateId = (typeof PHASE_8E_FINDINGS_INTELLIGENCE_GATES)[number][0];
