import type { EuShearMethodRecord } from "@rtb/types";

export const EU_SHEAR_IMPLEMENTATION_VERSION = "eu-shear-1.0.0" as const;
export const EU_SHEAR_TOOL_REF = "EOS_EU_STEEL_SHEAR" as const;

const MECHANICS_YIELD = "established-mechanics-von-mises-pure-shear-yield-fy-over-sqrt-3-times-governed-shear-area";
const MECHANICS_BUCKLING = "established-mechanics-elastic-plate-shear-buckling-kv-pi2-E-over-12-1-nu2-d-over-t-squared-times-Av";

export const EU_SHEAR_STANDARD_PART_DEPENDENCY_MODEL = {
  memberShearMechanicsPart: "EN_1993_1_1",
  webPlateStabilityFrameworkPart: "EN_1993_1_5",
  assumedAllWebRulesLiveInEn199311: false,
} as const;

export const EU_SHEAR_ELASTIC_MAJOR_MECHANICS_RULE: EuShearMethodRecord = {
  ruleId: "EU-SHEAR-ELASTIC-MAJOR-MECHANICS-V1",
  methodId: "EU_SHEAR_ELASTIC_MAJOR_MECHANICS",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_YIELD,
  calculationPurpose: "von Mises pure-shear yield force for major-axis shear as a mechanics reference, not EN 1993 Vpl,Rd",
  applicability: "steel members with explicit fy and a governed shear area for major-axis shear",
  requiredInputs: ["material.yieldStrength", "section.shearArea"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_SHEAR",
  units: "N",
  implementationVersion: EU_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["EU-SHEAR-BM-YIELD-MAJOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "eu-shear-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "NO_ANNEX_DEPENDENCY",
  ruleRequiresNdp: false,
  axis: "MAJOR_SHEAR",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const EU_SHEAR_ELASTIC_MINOR_MECHANICS_RULE: EuShearMethodRecord = {
  ruleId: "EU-SHEAR-ELASTIC-MINOR-MECHANICS-V1",
  methodId: "EU_SHEAR_ELASTIC_MINOR_MECHANICS",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_YIELD,
  calculationPurpose: "von Mises pure-shear yield force for minor-axis shear as a mechanics reference, not EN 1993 Vpl,Rd",
  applicability: "steel members with explicit fy and a governed shear area for minor-axis shear",
  requiredInputs: ["material.yieldStrength", "section.shearArea"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_SHEAR",
  units: "N",
  implementationVersion: EU_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["EU-SHEAR-BM-YIELD-MINOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "eu-shear-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "NO_ANNEX_DEPENDENCY",
  ruleRequiresNdp: false,
  axis: "MINOR_SHEAR",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const EU_SHEAR_ELASTIC_BUCKLING_MECHANICS_RULE: EuShearMethodRecord = {
  ruleId: "EU-SHEAR-ELASTIC-BUCKLING-MECHANICS-V1",
  methodId: "EU_SHEAR_ELASTIC_BUCKLING_MECHANICS",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_BUCKLING,
  calculationPurpose: "elastic plate shear-buckling force as a mechanics reference; kv is never defaulted",
  applicability: "plates with explicit E, Poisson ratio, web depth, web thickness, governed Av, and supplied kv",
  requiredInputs: ["material.elasticModulus", "material.poissonRatio", "section.webDepth", "section.webThickness", "section.shearArea", "shear.shearBucklingCoefficient"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_SHEAR_BUCKLING",
  units: "N",
  implementationVersion: EU_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["EU-SHEAR-BM-BUCKLING-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "eu-shear-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ENGINEERING_MECHANICS_REFERENCE",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "NO_ANNEX_DEPENDENCY",
  ruleRequiresNdp: false,
  axis: "WEB",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const EU_SECTION_SHEAR_CAPACITY_CODE_PROFILE_RULE: EuShearMethodRecord = {
  ruleId: "EU-SECTION-SHEAR-CAPACITY-CODE-PROFILE-V1",
  methodId: "EU_SECTION_SHEAR_CAPACITY_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-section-shear-resistance-validation-required",
  calculationPurpose: "Eurocode-profile section shear resistance",
  applicability: "not implemented; requires governed shear area rule, partial factor, slenderness dependencies, and confirmed edition",
  requiredInputs: ["material.yieldStrength", "section.shearArea", "ndp.partial-factor"],
  outputType: "EUROCODE_PROFILE_SHEAR_CAPACITY",
  units: "N",
  implementationVersion: EU_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_SHEAR_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: ["partial-factor"],
  annexDependency: "NDP_REQUIRED",
  ruleRequiresNdp: true,
  axis: "SHEAR",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "FRAMEWORK_ONLY",
};

export const EU_WEB_STABILITY_CODE_PROFILE_RULE: EuShearMethodRecord = {
  ruleId: "EU-WEB-STABILITY-CODE-PROFILE-V1",
  methodId: "EU_WEB_STABILITY_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-5-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-web-plate-stability-validation-required",
  calculationPurpose: "Eurocode-profile web/shear-buckling resistance; part dependency is EN 1993-1-5, not assumed to live in EN 1993-1-1",
  applicability: "not implemented; requires governed slenderness, buckling coefficient, reduction, stiffener/panel geometry, partial factor, and confirmed edition",
  requiredInputs: ["section.webDepth", "section.webThickness", "panel geometry", "stiffener context", "ndp.partial-factor", "standardPart"],
  outputType: "EUROCODE_PROFILE_WEB_STABILITY_CAPACITY",
  units: "N",
  implementationVersion: EU_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_WEB_STABILITY_CAPACITY",
  standardPartRef: "EN_1993_1_5",
  ndpDependencies: ["partial-factor"],
  annexDependency: "NDP_REQUIRED",
  ruleRequiresNdp: true,
  axis: "WEB",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "FRAMEWORK_ONLY",
};

export const EU_WEB_SLENDERNESS_CODE_PROFILE_RULE: EuShearMethodRecord = {
  ruleId: "EU-WEB-SLENDERNESS-CODE-PROFILE-V1",
  methodId: "EU_WEB_SLENDERNESS_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-1-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-web-slenderness-limits-validation-required",
  calculationPurpose: "Eurocode-profile web slenderness classification/limits",
  applicability: "not implemented; width/thickness limits are unvalidated",
  requiredInputs: ["section.webDepth", "section.webThickness", "material.yieldStrength", "standardPart", "edition"],
  outputType: "EUROCODE_PROFILE_WEB_SLENDERNESS",
  units: "1",
  implementationVersion: EU_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_WEB_STABILITY_CAPACITY",
  standardPartRef: "EN_1993_1_1",
  ndpDependencies: [],
  annexDependency: "ANNEX_OPTIONAL",
  ruleRequiresNdp: false,
  axis: "WEB",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "VALIDATION_REQUIRED",
};

export const EU_TENSION_FIELD_CODE_PROFILE_RULE: EuShearMethodRecord = {
  ruleId: "EU-TENSION-FIELD-CODE-PROFILE-V1",
  methodId: "EU_TENSION_FIELD_CODE_PROFILE",
  jurisdiction: "eu-eea",
  standardProfileRef: "eu-steel-en1993-1-5-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "en1993-tension-field-post-buckling-validation-required",
  calculationPurpose: "Eurocode-profile tension-field / post-buckling shear resistance",
  applicability: "not implemented; tension-field action is unvalidated and not numerically executed",
  requiredInputs: ["panel geometry", "stiffener context", "standardPart", "edition", "ndp.partial-factor"],
  outputType: "EUROCODE_PROFILE_TENSION_FIELD",
  units: "N",
  implementationVersion: EU_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "eu-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "EN1993",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "EUROCODE_PROFILE_WEB_STABILITY_CAPACITY",
  standardPartRef: "EN_1993_1_5",
  ndpDependencies: ["partial-factor"],
  annexDependency: "NDP_REQUIRED",
  ruleRequiresNdp: true,
  axis: "PANEL",
  compatibleGenerations: ["FIRST_GENERATION", "UNKNOWN_PENDING_CONFIRMATION"],
  scopeState: "NOT_IMPLEMENTED",
};

export const EU_SHEAR_METHOD_REGISTRY: readonly EuShearMethodRecord[] = [
  EU_SHEAR_ELASTIC_MAJOR_MECHANICS_RULE,
  EU_SHEAR_ELASTIC_MINOR_MECHANICS_RULE,
  EU_SHEAR_ELASTIC_BUCKLING_MECHANICS_RULE,
  EU_SECTION_SHEAR_CAPACITY_CODE_PROFILE_RULE,
  EU_WEB_STABILITY_CODE_PROFILE_RULE,
  EU_WEB_SLENDERNESS_CODE_PROFILE_RULE,
  EU_TENSION_FIELD_CODE_PROFILE_RULE,
];

export const IMPLEMENTED_EU_SHEAR_METHODS = [
  EU_SHEAR_ELASTIC_MAJOR_MECHANICS_RULE.methodId,
  EU_SHEAR_ELASTIC_MINOR_MECHANICS_RULE.methodId,
  EU_SHEAR_ELASTIC_BUCKLING_MECHANICS_RULE.methodId,
] as const;

export const FRAMEWORK_ONLY_EU_SHEAR_METHODS = [
  EU_SECTION_SHEAR_CAPACITY_CODE_PROFILE_RULE.methodId,
  EU_WEB_STABILITY_CODE_PROFILE_RULE.methodId,
  EU_WEB_SLENDERNESS_CODE_PROFILE_RULE.methodId,
  EU_TENSION_FIELD_CODE_PROFILE_RULE.methodId,
] as const;
