export const PHASE_8I_PROJECT_INTELLIGENCE_V1_GATES = [
  ["A", "Repository identity"],
  ["B", "Build identity"],
  ["C", "Version identity"],
  ["D", "Migration identity"],
  ["E", "Platform regression"],
  ["F", "Engineering OS regression"],
  ["G", "Module manifest"],
  ["H", "Document Intelligence"],
  ["I", "Meeting Intelligence"],
  ["J", "Findings Intelligence"],
  ["K", "Reporting Intelligence"],
  ["L", "Executive Dashboard"],
  ["M", "Knowledge Intelligence"],
  ["N", "Engineering Reasoning Assistant"],
  ["O", "Cross-feature workflows"],
  ["P", "Data ownership"],
  ["Q", "Entitlement"],
  ["R", "Tenant isolation"],
  ["S", "Workspace isolation"],
  ["T", "AI governance"],
  ["U", "Provider status"],
  ["V", "HTTP and webhook contracts"],
  ["W", "Browser E2E"],
  ["X", "Accessibility"],
  ["Y", "Responsive"],
  ["Z", "Performance"],
  ["AA", "Operations readiness"],
  ["AB", "Secret exposure"],
  ["AC", "Artifact identity"],
  ["AD", "Release eligibility"],
] as const;

export type Phase8iGateId = (typeof PHASE_8I_PROJECT_INTELLIGENCE_V1_GATES)[number][0];
