import type { UsSteelValidationMatrixRow } from "@rtb/types";

export const US_STEEL_VALIDATION_MATRIX: readonly UsSteelValidationMatrixRow[] = [
  { capability: "standard binding", implemented: true, numericallyValidated: false, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "AISC family/edition/amendment architecture; edition UNKNOWN_PENDING_CONFIRMATION" },
  { capability: "building-code adoption", implemented: true, numericallyValidated: false, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "adoption metadata model only; real-world datasets not populated" },
  { capability: "LRFD/ASD governance", implemented: true, numericallyValidated: false, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "explicit method required; no default; mixing fail-closed" },
  { capability: "tension", implemented: true, numericallyValidated: true, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "FyAg/FuAn mechanics; not AISC design strength" },
  { capability: "compression", implemented: true, numericallyValidated: true, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "squash FyA mechanics; not AISC compression strength" },
  { capability: "compression stability", implemented: true, numericallyValidated: true, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "Euler Pcr is not AISC member compression strength" },
  { capability: "major bending", implemented: true, numericallyValidated: true, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "elastic My=FyS; not AISC flexural strength" },
  { capability: "minor bending", implemented: true, numericallyValidated: true, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "elastic My=FyS; not AISC flexural strength" },
  { capability: "LTB", implemented: true, numericallyValidated: true, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "elastic Mcr is not AISC flexural strength" },
  { capability: "major shear", implemented: true, numericallyValidated: true, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "von Mises yield reference; not AISC shear strength" },
  { capability: "minor shear", implemented: true, numericallyValidated: true, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "von Mises yield reference; not AISC shear strength" },
  { capability: "web stability", implemented: true, numericallyValidated: true, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "elastic plate buckling; not AISC web strength" },
  { capability: "combined actions", implemented: false, numericallyValidated: false, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "framework only; IMPLEMENTED_US_INTERACTION_METHODS = NONE" },
  { capability: "serviceability", implemented: true, numericallyValidated: false, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "orchestration of governed criteria; no default L/n" },
  { capability: "member orchestration", implemented: true, numericallyValidated: false, engineerValidated: false, codeProfileImplemented: false, conformanceValidated: false, buildingCodeComplianceValidated: false, certified: false, limitation: "mechanics complete does not equal AISC code-design complete" },
];
