/**
 * Phase 10H certification gates A–BG (Risk / Maintenance / Priority / Decision Context).
 */
export const PHASE_10H_ASSET_INTELLIGENCE_RISK_PRIORITY_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 10A regression"],
  ["C", "Phase 10B regression"],
  ["D", "Phase 10B.1 persistence regression"],
  ["E", "Phase 10C regression"],
  ["F", "Phase 10D regression"],
  ["G", "Phase 10E regression"],
  ["H", "Authoritative Phase 10F regression"],
  ["I", "Phase 10G regression"],
  ["J", "PI v1 integrity"],
  ["K", "II v1 integrity"],
  ["L", "Ownership locks"],
  ["M", "Risk terminology"],
  ["N", "Canonical Risk boundary"],
  ["O", "Maintenance/CMMS boundary"],
  ["P", "Decision Context Engine"],
  ["Q", "Published-slice rule"],
  ["R", "Risk Signal model"],
  ["S", "Risk Signal Engine"],
  ["T", "Risk candidate governance"],
  ["U", "Recommendation taxonomy"],
  ["V", "Maintenance Recommendation Engine"],
  ["W", "Asset Priority Profile"],
  ["X", "Priority Context Engine"],
  ["Y", "Numeric score governance"],
  ["Z", "Semantic dimensional preservation"],
  ["AA", "Evidence Confidence"],
  ["AB", "Trend Confidence"],
  ["AC", "Health composition unchanged"],
  ["AD", "Risk not Health factor"],
  ["AE", "Priority not Health factor"],
  ["AF", "Governed review"],
  ["AG", "Segregation of duties"],
  ["AH", "Hosted migration"],
  ["AI", "Migration lineage"],
  ["AJ", "Hosted persistence"],
  ["AK", "Snapshot"],
  ["AL", "Timeline"],
  ["AM", "Event/outbox integrity"],
  ["AN", "II boundary"],
  ["AO", "PI boundary"],
  ["AP", "Cross-module contract drafts"],
  ["AQ", "AI governance"],
  ["AR", "HTTP contracts"],
  ["AS", "Real JWT role matrix"],
  ["AT", "Tenant isolation"],
  ["AU", "Workspace isolation"],
  ["AV", "IDOR"],
  ["AW", "Idempotency"],
  ["AX", "Concurrency"],
  ["AY", "Health/observability"],
  ["AZ", "Performance"],
  ["BA", "No memory production"],
  ["BB", "No predictive ML"],
  ["BC", "No PoF claim"],
  ["BD", "No RUL claim"],
  ["BE", "Secret exposure"],
  ["BF", "Artifact identity"],
  ["BG", "Phase 10I readiness"],
] as const;

export type Phase10hGateId =
  (typeof PHASE_10H_ASSET_INTELLIGENCE_RISK_PRIORITY_GATES)[number][0];
