import type { EosD0GovernanceRisk } from "@rtb/types";

export const EOS_D0_GOVERNANCE_RISK_REGISTER: readonly EosD0GovernanceRisk[] = [
  {
    id: "D0-R01",
    risk: "Discipline contract too generic for later pack implementation",
    severity: "MEDIUM",
    likelihood: "MEDIUM",
    mitigation: "Keep one shared contract; D1-D8 add pack data only, not new operating systems.",
    owner: "Engineering OS architecture",
    phaseToClose: "D1-D8 pack implementation",
  },
  {
    id: "D0-R02",
    risk: "Future standards engines hard-code one jurisdiction or code family",
    severity: "HIGH",
    likelihood: "MEDIUM",
    mitigation: "Standards remain jurisdiction-selected with edition/amendment/national annex on EosEngineeringStandardRecord.",
    owner: "Discipline pack owners",
    phaseToClose: "D1+ standards engines",
  },
  {
    id: "D0-R03",
    risk: "AI authority ambiguity between suggestion, review, and approval",
    severity: "HIGH",
    likelihood: "MEDIUM",
    mitigation: "Output-class transitions, ReviewRule/ApprovalRule, and AI capability defaults forbid self-approval and LLM governed numerics.",
    owner: "AI governance",
    phaseToClose: "D1 runtime enforcement",
  },
  {
    id: "D0-R04",
    risk: "Cross-discipline circular dependencies",
    severity: "MEDIUM",
    likelihood: "MEDIUM",
    mitigation: "Interfaces are declared metadata; D9 intelligence must detect cycles and keep AI impact advisory.",
    owner: "Cross-discipline intelligence",
    phaseToClose: "D9",
  },
  {
    id: "D0-R05",
    risk: "Jurisdiction profile conflicts on a single workspace",
    severity: "MEDIUM",
    likelihood: "MEDIUM",
    mitigation: "One selected jurisdiction profile per governed output; extendJurisdictionCatalog remains additive.",
    owner: "Global governance",
    phaseToClose: "D1+ project jurisdiction binding",
  },
  {
    id: "D0-R06",
    risk: "Standard edition/amendment/national annex version conflicts",
    severity: "MEDIUM",
    likelihood: "HIGH",
    mitigation: "Calculations must bind standard records, not bare code names; D1 closes unbound structural tool/jurisdiction.",
    owner: "Discipline pack owners",
    phaseToClose: "D1",
  },
  {
    id: "D0-R07",
    risk: "External-tool result mismatch versus internal deterministic results",
    severity: "HIGH",
    likelihood: "HIGH",
    mitigation: "Reuse governed external-tool statuses; uncertified tools fail closed with no silent fallback.",
    owner: "External tool governance",
    phaseToClose: "D1 solver certification",
  },
  {
    id: "D0-R08",
    risk: "Provenance loss on discipline outputs",
    severity: "HIGH",
    likelihood: "MEDIUM",
    mitigation: "All packs inherit eos-eu-0-global-provenance; instance objects must attach the global provenance contract.",
    owner: "Engineering Core / pack owners",
    phaseToClose: "D1 instance objects",
  },
  {
    id: "D0-R09",
    risk: "Discipline object duplication of Engineering Core registers",
    severity: "HIGH",
    likelihood: "LOW",
    mitigation: "CORE_REGISTER_OWNERSHIP_LOCK denies recreation of decision/assumption/action/risk/issue/TQ/lesson.",
    owner: "Engineering Core",
    phaseToClose: "D1 object design review",
  },
  {
    id: "D0-R10",
    risk: "Privacy leakage through discipline metadata",
    severity: "MEDIUM",
    likelihood: "MEDIUM",
    mitigation: "Classifiable data includes personal/AI categories; personal data remains optional and must not be introduced by default.",
    owner: "Privacy / data profile",
    phaseToClose: "D1+ object schemas",
  },
  {
    id: "D0-R11",
    risk: "Tenant leakage via discipline-global mutable state",
    severity: "HIGH",
    likelihood: "LOW",
    mitigation: "Registry is static catalog; instance objects inherit platform tenant/workspace context and security baseline isolation.",
    owner: "Platform security",
    phaseToClose: "D1 instance persistence",
  },
  {
    id: "D0-R12",
    risk: "Overly broad Digital Twin scope including human/person twins",
    severity: "MEDIUM",
    likelihood: "LOW",
    mitigation: "Discipline extensions forbid humanPersonTwinAllowed; measured state remains distinct from inferred, thread, and AI memory.",
    owner: "Digital Twin governance",
    phaseToClose: "separate people-twin governance if ever required",
  },
];
