import type { OwnerCommandRepository } from "../owner-command/repository";
import type { OwnerCommandScope } from "../owner-command/service";
import { asJson, BusinessRiskRepository } from "./repository";

const NOW = "2026-08-19T12:00:00.000Z";
const FIXTURE = "bos-9-business-risk";

function iso(offsetDays: number, time = "T09:00:00.000Z"): string {
  const d = new Date("2026-08-19T00:00:00.000Z");
  d.setUTCDate(d.getUTCDate() + offsetDays);
  return d.toISOString().slice(0, 10) + time;
}

export async function seedBusinessRiskDemo(
  risks: BusinessRiskRepository,
  owner: OwnerCommandRepository,
  scope: OwnerCommandScope,
): Promise<{ created: boolean; isDemo: true }> {
  const createdBy = scope.userId;
  const existing = await risks.getRiskBySource(scope, "demo", "bos-9-demo-cash");
  if (existing) return { created: false, isDemo: true };

  await risks.upsertSettings({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    version: 1,
    effective_at: iso(-30),
    default_max_acceptable_level: "high",
    rules: asJson([
      {
        category: "financial",
        maxAcceptableLevel: "moderate",
        requiresApproval: true,
        escalationThreshold: "high",
      },
    ]),
    provenance: asJson({ fixture: FIXTURE, live: false }),
    created_by: createdBy,
  });

  const decisions = await owner.listDecisions(scope);
  const linkedDecision =
    decisions.find((row) => row.isDemo && row.statement.toLowerCase().includes("cash")) ?? decisions[0] ?? null;

  const cash = await risks.insertRisk({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    reference: "RSK-0001",
    title: "Cash / liquidity concentration",
    description: "Enterprise risk aggregating the existing cash-runway KPI. BOS-9 does not recompute runway.",
    category: "financial",
    domain: "finance",
    nature: "threat",
    owner_label: "Finance lead",
    status: "open",
    source_type: "demo",
    source_ref: "bos-9-demo-cash",
    identified_at: iso(-40),
    review_at: iso(-2),
    linked_decision_id: linkedDecision?.id ?? null,
    provenance: asJson({ fixture: FIXTURE, evidenceReuse: "finance.cash_runway" }),
    is_demo: true,
    created_by: createdBy,
  });

  await risks.insertEvidence({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: cash.id,
    source_type: "kpi",
    source_ref: "bos-1-demo:cash_runway_months",
    snapshot: asJson({ key: "cash_runway_months", value: 4.2, unit: "months", currency: "AUD" }),
    captured_at: iso(-5),
    provenance: asJson({ fixture: FIXTURE, live: false }),
  });

  await risks.insertAssessment({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: cash.id,
    version: 1,
    method: "risk_assessment.v1",
    likelihood: "likely",
    impact: "severe",
    inherent_level: "extreme",
    residual_level: "extreme",
    inherent_score: 20,
    residual_score: 20,
    assessor_label: "Owner",
    rationale: "Likely × severe = 20 (extreme). Qualitative matrix, not a probability.",
    assumptions: asJson(["Cash KPI snapshot is reused, not recomputed"]),
    evidence_refs: asJson([{ sourceType: "kpi", sourceRef: "bos-1-demo:cash_runway_months", title: "Cash runway" }]),
    residual_method: "residual_risk.v1",
    residual_rationale: "No evidenced effective operating control. Residual equals inherent.",
    assessed_at: iso(-5),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });

  const ops = await risks.insertRisk({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    reference: "RSK-0002",
    title: "Delivery / capacity risk",
    description: "Aggregates BOS-7 overdue/blocked work signals as enterprise operational risk.",
    category: "operational",
    domain: "operations",
    nature: "threat",
    owner_label: "Operations lead",
    status: "treating",
    source_type: "demo",
    source_ref: "bos-9-demo-delivery",
    identified_at: iso(-20),
    review_at: iso(14),
    provenance: asJson({ fixture: FIXTURE, evidenceReuse: "operations.overdue_work" }),
    is_demo: true,
    created_by: createdBy,
  });

  await risks.insertEvidence({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: ops.id,
    source_type: "operations",
    source_ref: "bos-7-demo:overdue_work",
    snapshot: asJson({ overdueWork: 3, blockedWork: 1 }),
    captured_at: iso(-1),
    provenance: asJson({ fixture: FIXTURE, live: false }),
  });

  const untested = await risks.insertControl({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    name: "Weekly delivery stand-up",
    description: "Planned detective control. Untested — must not reduce residual.",
    control_type: "detective",
    owner_label: "Operations lead",
    status: "implemented",
    effectiveness: "untested",
    frequency: "weekly",
    evidence_refs: asJson([]),
    tested_at: null,
    review_at: iso(30),
    provenance: asJson({ fixture: FIXTURE, untested: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertControlLink({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: ops.id,
    control_id: untested.id,
    applicable: true,
  });

  await risks.insertAssessment({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: ops.id,
    version: 1,
    method: "risk_assessment.v1",
    likelihood: "likely",
    impact: "major",
    inherent_level: "high",
    residual_level: "high",
    inherent_score: 16,
    residual_score: 16,
    assessor_label: "Operations lead",
    rationale: "Likely × major = 16 (high). Untested control does not reduce residual.",
    assumptions: asJson(["BOS-7 overdue counts reused as evidence refs"]),
    evidence_refs: asJson([{ sourceType: "operations", sourceRef: "bos-7-demo:overdue_work", title: "Overdue work" }]),
    residual_method: "residual_risk.v1",
    residual_rationale: "Control exists but is untested. Residual equals inherent.",
    assessed_at: iso(-1),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });

  const overdueAction = await owner.insertAction(scope, {
    decisionId: linkedDecision?.id ?? null,
    title: "Recover overdue operational work",
    ownerId: scope.userId,
    dueDate: iso(-3).slice(0, 10),
    priority: "high",
    status: "open",
    completionEvidence: {},
    completedAt: null,
    isDemo: true,
    createdBy,
  });
  const treatment = await risks.insertTreatment({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: ops.id,
    strategy: "reduce",
    decision_id: linkedDecision?.id ?? null,
    expected_residual_level: "moderate",
    actual_residual_level: null,
    notes: "Treatment reuses the existing BOS-1 action. No second task table.",
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertActionLink({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: ops.id,
    treatment_id: treatment.id,
    action_id: overdueAction.id,
  });

  const customer = await risks.insertRisk({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    reference: "RSK-0003",
    title: "Customer concentration",
    description: "References BOS-5 concentration evidence. Customer Health is not treated as a risk score.",
    category: "customer",
    domain: "customer",
    nature: "threat",
    owner_label: "Account lead",
    status: "monitoring",
    source_type: "demo",
    source_ref: "bos-9-demo-customer-concentration",
    identified_at: iso(-15),
    review_at: iso(7),
    provenance: asJson({ fixture: FIXTURE, noHealthScoreMapping: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertEvidence({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: customer.id,
    source_type: "customer",
    source_ref: "bos-5-demo:concentration",
    snapshot: asJson({ topCustomerShareBps: 4200, mapping: "explicit_concentration_ref" }),
    captured_at: iso(-2),
    provenance: asJson({ fixture: FIXTURE }),
  });
  const evidencedControl = await risks.insertControl({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    name: "Account diversification review",
    description: "Operating preventive control with test evidence.",
    control_type: "preventive",
    owner_label: "Account lead",
    status: "operating",
    effectiveness: "effective",
    frequency: "quarterly",
    evidence_refs: asJson([{ sourceType: "document", sourceRef: "bos-9-demo:diversification-review", title: "Q2 review" }]),
    tested_at: iso(-10),
    review_at: iso(80),
    provenance: asJson({ fixture: FIXTURE, evidenced: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertControlLink({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: customer.id,
    control_id: evidencedControl.id,
    applicable: true,
  });
  await risks.insertAssessment({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: customer.id,
    version: 1,
    method: "risk_assessment.v1",
    likelihood: "possible",
    impact: "major",
    inherent_level: "high",
    residual_level: "moderate",
    inherent_score: 12,
    residual_score: 5,
    assessor_label: "Account lead",
    rationale: "Possible × major = 12 (high). Evidenced operating control reduces residual by one band.",
    assumptions: asJson(["Concentration share is a reused BOS-5 snapshot"]),
    evidence_refs: asJson([{ sourceType: "customer", sourceRef: "bos-5-demo:concentration", title: "Concentration" }]),
    residual_method: "residual_risk.v1",
    residual_rationale: "Reduced by one band because an applicable control is operating, effective, and evidenced.",
    assessed_at: iso(-2),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });

  const ineffectiveRisk = await risks.insertRisk({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    reference: "RSK-0004",
    title: "Supplier continuity with ineffective control",
    description: "Ineffective control must not reduce residual risk.",
    category: "supplier",
    domain: "operations",
    nature: "threat",
    owner_label: "Procurement",
    status: "open",
    source_type: "demo",
    source_ref: "bos-9-demo-ineffective-control",
    identified_at: iso(-12),
    review_at: iso(5),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });
  const ineffective = await risks.insertControl({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    name: "Single-source dual-run",
    description: "Control tested and found ineffective.",
    control_type: "corrective",
    owner_label: "Procurement",
    status: "ineffective",
    effectiveness: "ineffective",
    frequency: "monthly",
    evidence_refs: asJson([{ sourceType: "document", sourceRef: "bos-9-demo:control-test-fail", title: "Failed test" }]),
    tested_at: iso(-4),
    review_at: iso(10),
    provenance: asJson({ fixture: FIXTURE, ineffective: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertControlLink({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: ineffectiveRisk.id,
    control_id: ineffective.id,
    applicable: true,
  });
  await risks.insertAssessment({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: ineffectiveRisk.id,
    version: 1,
    method: "risk_assessment.v1",
    likelihood: "possible",
    impact: "major",
    inherent_level: "high",
    residual_level: "high",
    inherent_score: 12,
    residual_score: 12,
    assessor_label: "Procurement",
    rationale: "Ineffective control cannot reduce residual.",
    assumptions: asJson([]),
    evidence_refs: asJson([]),
    residual_method: "residual_risk.v1",
    residual_rationale: "Control exists and was tested ineffective. Residual equals inherent.",
    assessed_at: iso(-4),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });

  await risks.insertRisk({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    reference: "RSK-0005",
    title: "Unassessed technology risk",
    description: "No evidence, unknown likelihood and impact, no owner.",
    category: "technology",
    domain: "technology",
    nature: "threat",
    owner_label: null,
    status: "identified",
    source_type: "demo",
    source_ref: "bos-9-demo-unknown",
    identified_at: iso(-1),
    review_at: null,
    provenance: asJson({ fixture: FIXTURE, noEvidence: true }),
    is_demo: true,
    created_by: createdBy,
  });

  const unknownAssessed = await risks.insertRisk({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    reference: "RSK-0006",
    title: "Unknown likelihood / impact",
    description: "Explicit unknown inputs must yield unknown risk level.",
    category: "other",
    domain: "general",
    nature: "threat",
    owner_label: "Owner",
    status: "assessing",
    source_type: "demo",
    source_ref: "bos-9-demo-unknown-matrix",
    identified_at: iso(-6),
    review_at: iso(20),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertAssessment({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: unknownAssessed.id,
    version: 1,
    method: "risk_assessment.v1",
    likelihood: "unknown",
    impact: "unknown",
    inherent_level: "unknown",
    residual_level: "unknown",
    inherent_score: null,
    residual_score: null,
    assessor_label: "Owner",
    rationale: "Unknown × unknown = unknown. Not presented as a probability.",
    assumptions: asJson(["Insufficient evidence"]),
    evidence_refs: asJson([]),
    residual_method: "residual_risk.v1",
    residual_rationale: "Inherent unknown, residual unknown.",
    assessed_at: iso(-6),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });

  const accepted = await risks.insertRisk({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    reference: "RSK-0007",
    title: "Accepted reputation exposure",
    description: "Human-accepted risk whose review date has expired.",
    category: "reputation",
    domain: "general",
    nature: "threat",
    owner_label: "Owner",
    status: "accepted",
    source_type: "demo",
    source_ref: "bos-9-demo-accepted-expired",
    identified_at: iso(-90),
    review_at: iso(-10),
    accepted_at: iso(-60),
    accepted_by: createdBy,
    provenance: asJson({ fixture: FIXTURE, humanAccepted: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertAssessment({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: accepted.id,
    version: 1,
    method: "risk_assessment.v1",
    likelihood: "unlikely",
    impact: "moderate",
    inherent_level: "moderate",
    residual_level: "moderate",
    inherent_score: 6,
    residual_score: 6,
    assessor_label: "Owner",
    rationale: "Human accepted residual moderate.",
    assumptions: asJson([]),
    evidence_refs: asJson([]),
    residual_method: "residual_risk.v1",
    residual_rationale: "No evidenced control. Residual equals inherent.",
    assessed_at: iso(-60),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertTreatment({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: accepted.id,
    strategy: "accept",
    decision_id: null,
    expected_residual_level: "moderate",
    actual_residual_level: "moderate",
    accepted_at: iso(-60),
    accepted_by: createdBy,
    notes: "Accepted by authorized human. AI cannot accept risk.",
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });

  const mixed = await risks.insertRisk({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    reference: "RSK-0008",
    title: "Mixed-currency receivable exposure",
    description: "Exposure cannot be summed across currencies. Amount stays unknown.",
    category: "financial",
    domain: "finance",
    nature: "threat",
    owner_label: "Finance lead",
    status: "open",
    source_type: "demo",
    source_ref: "bos-9-demo-mixed-currency",
    identified_at: iso(-8),
    review_at: iso(3),
    provenance: asJson({ fixture: FIXTURE, mixedCurrency: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertEvidence({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: mixed.id,
    source_type: "finance",
    source_ref: "bos-2-demo:receivable-aud",
    snapshot: asJson({ amountMinor: "2500000", currency: "AUD" }),
    captured_at: iso(-3),
    provenance: asJson({ fixture: FIXTURE }),
  });
  await risks.insertEvidence({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: mixed.id,
    source_type: "finance",
    source_ref: "bos-2-demo:receivable-usd",
    snapshot: asJson({ amountMinor: "1800000", currency: "USD" }),
    captured_at: iso(-3),
    provenance: asJson({ fixture: FIXTURE }),
  });
  await risks.insertAssessment({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: mixed.id,
    version: 1,
    method: "risk_assessment.v1",
    likelihood: "possible",
    impact: "major",
    inherent_level: "high",
    residual_level: "high",
    inherent_score: 12,
    residual_score: 12,
    assessor_label: "Finance lead",
    rationale: "Mixed-currency exposure is unknown, not summed.",
    assumptions: asJson(["Do not invent a single-currency total"]),
    evidence_refs: asJson([]),
    residual_method: "residual_risk.v1",
    residual_rationale: "No evidenced effective control.",
    assessed_at: iso(-3),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });

  await risks.insertObligation({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: cash.id,
    control_id: null,
    action_id: null,
    title: "Treasury review of cash runway",
    source_ref: "internal-policy:treasury-review",
    jurisdiction: "internal",
    owner_label: "Finance lead",
    due_at: iso(-1),
    review_at: iso(-1),
    status: "overdue",
    evidence_refs: asJson([]),
    authorized_confirmation: false,
    provenance: asJson({ fixture: FIXTURE, notStatutory: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertObligation({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: customer.id,
    control_id: evidencedControl.id,
    action_id: null,
    title: "Documented customer concentration review",
    source_ref: "internal-policy:concentration-review",
    jurisdiction: "internal",
    owner_label: "Account lead",
    due_at: iso(20),
    review_at: iso(20),
    status: "compliant",
    evidence_refs: asJson([{ sourceType: "document", sourceRef: "bos-9-demo:diversification-review", title: "Q2 review" }]),
    authorized_confirmation: true,
    confirmation_by: createdBy,
    confirmation_at: iso(-10),
    provenance: asJson({ fixture: FIXTURE, notLegalAdvice: true }),
    is_demo: true,
    created_by: createdBy,
  });
  await risks.insertObligation({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: ops.id,
    title: "Ambiguous delivery obligation",
    source_ref: null,
    jurisdiction: null,
    owner_label: null,
    due_at: null,
    status: "unknown",
    evidence_refs: asJson([]),
    authorized_confirmation: false,
    provenance: asJson({ fixture: FIXTURE, ambiguous: true }),
    is_demo: true,
    created_by: createdBy,
  });

  await risks.insertIncident({
    tenant_id: scope.tenantId,
    workspace_id: scope.workspaceId,
    risk_id: ops.id,
    action_id: overdueAction.id,
    title: "Blocked work cluster",
    description: "Bounded incident link to existing BOS-7 operational issue evidence. Not an IM platform.",
    occurred_at: iso(-4),
    severity: "high",
    source_type: "operations",
    source_ref: "bos-7-demo:blocked-work",
    impact: "Delivery date slipped",
    evidence_refs: asJson([{ sourceType: "signal", sourceRef: "bos-7-demo:blocked-work", title: "Blocked work" }]),
    provenance: asJson({ fixture: FIXTURE }),
    is_demo: true,
    created_by: createdBy,
  });

  return { created: true, isDemo: true };
}
