/** Typed commerce access policy for route and service enforcement. */

export type CommerceCachePolicy = "allow-short-cache" | "fresh";

export interface CommerceAccessPolicy {
  productKey: string;
  applicationKey?: string;
  featureKey?: string;
  action: string;
  seatRequired?: boolean;
  workspaceRequired?: boolean;
  cachePolicy?: CommerceCachePolicy;
  hideResourceExistence?: boolean;
}

export const ENGINEERING_PRODUCT = "engineering-os";
export const BUSINESS_PRODUCT = "business-os";
export const BUSINESS_OS_FEATURE_KEY = "business_os";

/** Business OS API policies (BOS-0 foundation through BOS-7 Work & Operations). Seat not required; catalog remains coming_soon. */
export const BUSINESS_API_POLICIES: Record<string, CommerceAccessPolicy> = {
  "status.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "status.read",
    seatRequired: false,
  },
  "capabilities.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "capabilities.read",
    seatRequired: false,
  },
  "config.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "config.read",
    seatRequired: false,
  },
  "command.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "command.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "health.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "health.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "brief.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "brief.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "kpis.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "kpis.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "kpis.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "kpis.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "signals.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "signals.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "signals.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "signals.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "recommendations.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "recommendations.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "recommendations.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "recommendations.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "decisions.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "decisions.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "decisions.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "decisions.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "actions.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "actions.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "actions.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "actions.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "demo.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "demo.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "finance.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "finance.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "finance.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "finance.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "growth.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "growth.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "growth.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "growth.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "revenue.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "revenue.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "revenue.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "revenue.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "customers.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "customers.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "customers.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "customers.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "profit.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "profit.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "profit.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "profit.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "operations.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "operations.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "operations.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "operations.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "risk.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "risk.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "risk.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "risk.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "context.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "context.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "context.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "context.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "ai-workforce.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "ai-workforce.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "ai-workforce.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "ai-workforce.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "integrations.read": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "integrations.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "integrations.write": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "integrations.write",
    seatRequired: false,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
};

export const BUSINESS_PAGE_POLICIES: Record<string, CommerceAccessPolicy> = {
  "/business": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "access",
    seatRequired: false,
  },
  "/business/finance": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "finance.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/growth": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "growth.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/revenue": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "revenue.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/customers": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "customers.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/profit": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "profit.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/operations": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "operations.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/decisions": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "decisions.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/risk": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "risk.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/context": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "context.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/ai-workforce": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "ai-workforce.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/integrations": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "integrations.read",
    seatRequired: false,
    workspaceRequired: true,
  },
  "/business/settings": {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: "settings.read",
    seatRequired: false,
  },
};

/** Engineering API route key → entitlement policy */
export const ENGINEERING_API_POLICIES: Record<string, CommerceAccessPolicy> = {
  "health.read": { productKey: ENGINEERING_PRODUCT, action: "health.read", seatRequired: false },
  "dashboard.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "dashboard.read", seatRequired: true },
  "projects.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "project.read", seatRequired: true },
  "projects.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "project.create", seatRequired: true, cachePolicy: "fresh" },
  "documents.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "documents", action: "document.read", seatRequired: true },
  "documents.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "documents", action: "document.write", seatRequired: true, cachePolicy: "fresh" },
  "assets.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "asset.read", seatRequired: true },
  "assets.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "companies.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "company.read", seatRequired: true },
  "disciplines.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "discipline.read", seatRequired: true },
  "decisions.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "decision.read", seatRequired: true },
  "decisions.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "decision.write", seatRequired: true, cachePolicy: "fresh" },
  "risks.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "risk.read", seatRequired: true },
  "risks.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "risk.write", seatRequired: true, cachePolicy: "fresh" },
  "issues.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "issue.read", seatRequired: true },
  "issues.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "issue.write", seatRequired: true, cachePolicy: "fresh" },
  "actions.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_controls", action: "action.read", seatRequired: true },
  "actions.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_controls", action: "action.write", seatRequired: true, cachePolicy: "fresh" },
  "lessons.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "knowledge", action: "lesson.read", seatRequired: true },
  "lessons.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "knowledge", action: "lesson.write", seatRequired: true, cachePolicy: "fresh" },
  "technical-queries.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "technical_query.read", seatRequired: true },
  "technical-queries.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "technical_query.write", seatRequired: true, cachePolicy: "fresh" },
  "timeline.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "timeline.read", seatRequired: true },
  "activity.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "activity.read", seatRequired: true },
  "search.read": { productKey: ENGINEERING_PRODUCT, action: "search.read", seatRequired: true },
  "ai.read": { productKey: ENGINEERING_PRODUCT, featureKey: "ai_assistant", action: "ai.execute", seatRequired: true },
  "ai.write": { productKey: ENGINEERING_PRODUCT, featureKey: "ai_assistant", action: "ai.execute", seatRequired: true, cachePolicy: "fresh" },
  "settings.read": { productKey: ENGINEERING_PRODUCT, action: "settings.read", seatRequired: true },
  "settings.write": { productKey: ENGINEERING_PRODUCT, action: "settings.write", seatRequired: true, cachePolicy: "fresh" },
  "applications.read": { productKey: ENGINEERING_PRODUCT, action: "application.list", seatRequired: true },
  "demo.read": { productKey: ENGINEERING_PRODUCT, action: "demo.read", seatRequired: true },
  "demo.write": { productKey: ENGINEERING_PRODUCT, action: "demo.admin", seatRequired: true, cachePolicy: "fresh" },
  "project-intelligence-mappings.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "mapping.read", seatRequired: true, workspaceRequired: true },
  "project-intelligence-mappings.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "mapping.write", seatRequired: true, workspaceRequired: true, cachePolicy: "fresh" },
  "project-intelligence-health.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "health.read", seatRequired: true, workspaceRequired: true },
  "project-intelligence-ai-summary.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", featureKey: "ai_assistant", action: "ai.execute", seatRequired: true, workspaceRequired: true, cachePolicy: "fresh" },
  "project-intelligence-documents.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "document.intelligence.read", seatRequired: true, workspaceRequired: true },
  "project-intelligence-documents.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "document.intelligence.write", seatRequired: true, workspaceRequired: true, cachePolicy: "fresh" },
  "project-intelligence-meetings.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "meeting.intelligence.read", seatRequired: true, workspaceRequired: true },
  "project-intelligence-meetings.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "meeting.intelligence.write", seatRequired: true, workspaceRequired: true, cachePolicy: "fresh" },
  "project-intelligence-findings.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "findings.intelligence.read", seatRequired: true, workspaceRequired: true },
  "inspection-intelligence-slice.read": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "inspection-intelligence-slice.write": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.write",
    seatRequired: true,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "inspection-intelligence-review.read": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.review",
    seatRequired: true,
    workspaceRequired: true,
  },
  "inspection-intelligence-review.write": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.approve",
    seatRequired: true,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "project-intelligence-findings.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "findings.intelligence.write", seatRequired: true, workspaceRequired: true, cachePolicy: "fresh" },
  "project-intelligence-reports.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "reporting.intelligence.read", seatRequired: true, workspaceRequired: true },
  "project-intelligence-reports.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "reporting.intelligence.write", seatRequired: true, workspaceRequired: true, cachePolicy: "fresh" },
  "project-intelligence-knowledge.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "knowledge.intelligence.read", seatRequired: true, workspaceRequired: true },
  "project-intelligence-knowledge.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "knowledge.intelligence.write", seatRequired: true, workspaceRequired: true, cachePolicy: "fresh" },
  "project-intelligence-command-centre.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "project-intelligence-schedule.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "project-intelligence-cost-progress.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "project-intelligence-risk-change.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "project-intelligence-queries-decisions.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "project-intelligence-forecasting.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "project-intelligence-analyst.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "project-intelligence-analyst.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true, cachePolicy: "fresh" },
  "project-intelligence-reasoning.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "reasoning.assistant.read", seatRequired: true, workspaceRequired: true },
  "project-intelligence-reasoning.write": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "reasoning.assistant.execute", seatRequired: true, workspaceRequired: true, featureKey: "ai_assistant", cachePolicy: "fresh" },
  "model-interoperability.read": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "engineering_model_interoperability",
    action: "engineering_model.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "model-interoperability.write": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "engineering_model_interoperability",
    action: "engineering_model.register",
    seatRequired: true,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
  "execution-hosts.read": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "engineering_execution_host",
    action: "execution_host.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "execution-hosts.write": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "engineering_execution_host",
    action: "execution_host.admin",
    seatRequired: true,
    workspaceRequired: true,
    cachePolicy: "fresh",
  },
};

/** Page route application guards */
export const ENGINEERING_PAGE_POLICIES: Record<string, CommerceAccessPolicy> = {
  "/engineering": { productKey: ENGINEERING_PRODUCT, action: "access", seatRequired: true },
  "/engineering/projects": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/documents": { productKey: ENGINEERING_PRODUCT, applicationKey: "documents", action: "access", seatRequired: true },
  "/engineering/inspection": { productKey: ENGINEERING_PRODUCT, applicationKey: "inspection_intelligence", action: "access", seatRequired: true },
  "/engineering/apps/inspection-intelligence": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "access",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/asset-intelligence": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "asset_intelligence",
    action: "access",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/project-controls": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "project_controls",
    action: "access",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/digital-twin": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "digital_twin",
    action: "access",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/model-interoperability": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "engineering_model_interoperability",
    action: "access",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/execution-hosts": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "engineering_execution_host",
    action: "execution_host.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/templates": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/plans": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/sessions": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/review": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.review",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/defects": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/actions": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.write",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/workflows": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/assignments": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.write",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/my-work": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/field": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.write",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/sync": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.read",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/condition": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.write",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/predictive": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.review",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/vision": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.review",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/apps/inspection-intelligence/release": {
    productKey: ENGINEERING_PRODUCT,
    applicationKey: "inspection_intelligence",
    action: "inspection.admin",
    seatRequired: true,
    workspaceRequired: true,
  },
  "/engineering/project-controls": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_controls", action: "access", seatRequired: true },
  "/engineering/meetings": { productKey: ENGINEERING_PRODUCT, applicationKey: "meetings", action: "access", seatRequired: true },
  "/engineering/structural-intelligence": { productKey: ENGINEERING_PRODUCT, applicationKey: "structural_intelligence", action: "access", seatRequired: true },
  "/engineering/knowledge": { productKey: ENGINEERING_PRODUCT, applicationKey: "knowledge", action: "access", seatRequired: true },
  "/engineering/reports": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "report.access", seatRequired: true },
  "/engineering/ai": { productKey: ENGINEERING_PRODUCT, featureKey: "ai_assistant", action: "access", seatRequired: true },
  "/engineering/assets": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/settings": { productKey: ENGINEERING_PRODUCT, action: "access", seatRequired: true },
  "/engineering/actions": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_controls", action: "access", seatRequired: true },
  "/engineering/decisions": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/risks": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/issues": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/lessons": { productKey: ENGINEERING_PRODUCT, applicationKey: "knowledge", action: "access", seatRequired: true },
  "/engineering/technical-queries": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/timeline": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/activity": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/companies": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/disciplines": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true },
  "/engineering/search": { productKey: ENGINEERING_PRODUCT, action: "access", seatRequired: true },
  "/engineering/apps/project-intelligence": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/migration": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "migration.access", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/health": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "health.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/settings": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "settings.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/documents": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "document.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/documents/query": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "document.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/documents/review": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "document.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/documents/health": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "document.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/meetings": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "meeting.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/meetings/new": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "meeting.intelligence.write", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/meetings/health": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "meeting.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/meetings/settings/providers": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "meeting.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/meetings/settings/providers/microsoft-teams": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "meeting.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/meetings/[meetingId]/review": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "meeting.intelligence.write", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/meetings/[meetingId]/minutes": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "meeting.intelligence.write", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/findings": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "findings.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/reports": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "reporting.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/reports/executive": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "reporting.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/knowledge": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "knowledge.intelligence.read", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/schedule": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/cost-progress": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/risk-change": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/queries-decisions": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/forecasting": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/analyst": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "access", seatRequired: true, workspaceRequired: true },
  "/engineering/apps/project-intelligence/reasoning": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "reasoning.assistant.read", seatRequired: true, workspaceRequired: true },
};

export function resolveApiPolicyKey(segment: string, method: string): string {
  const write = method === "POST" || method === "PUT" || method === "PATCH" || method === "DELETE";
  const suffix = write ? "write" : "read";
  return `${segment}.${suffix}`;
}

export function getEngineeringApiPolicy(segment: string, method: string): CommerceAccessPolicy {
  const write = method === "POST" || method === "PUT" || method === "PATCH" || method === "DELETE";
  const key = resolveApiPolicyKey(segment, method);
  const policy = ENGINEERING_API_POLICIES[key];
  if (policy) return policy;
  const fallbackKey = `${segment}.read`;
  if (ENGINEERING_API_POLICIES[fallbackKey]) return ENGINEERING_API_POLICIES[fallbackKey];
  return {
    productKey: ENGINEERING_PRODUCT,
    action: `${segment}.${method.toLowerCase()}`,
    seatRequired: true,
    cachePolicy: write ? "fresh" : "allow-short-cache",
  };
}

export function getBusinessApiPolicy(segment: string, method: string): CommerceAccessPolicy {
  const write = method === "POST" || method === "PUT" || method === "PATCH" || method === "DELETE";
  const key = resolveApiPolicyKey(segment, method);
  const policy = BUSINESS_API_POLICIES[key];
  if (policy) return policy;
  return {
    productKey: BUSINESS_PRODUCT,
    featureKey: BUSINESS_OS_FEATURE_KEY,
    action: `${segment}.${method.toLowerCase()}`,
    seatRequired: false,
    cachePolicy: write ? "fresh" : "allow-short-cache",
  };
}
