import type { CommerceAccessPolicy } from "./commerce-access-policy";
import { ENGINEERING_PRODUCT } from "./commerce-access-policy";

/** Service-layer entitlement matrix for Engineering OS entry points. */
export const ENGINEERING_SERVICE_POLICIES: Record<string, CommerceAccessPolicy> = {
  "project.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "project.read", seatRequired: true },
  "project.get": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "project.read", seatRequired: true },
  "project.create": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "project.create", seatRequired: true, cachePolicy: "fresh" },
  "project.update": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "project.update", seatRequired: true, cachePolicy: "fresh" },
  "project.search": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "project.read", seatRequired: true },
  "asset.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "asset.read", seatRequired: true },
  "asset.get": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "asset.read", seatRequired: true },
  "asset.create": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "asset.update": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "asset.search": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "asset.read", seatRequired: true },
  "document.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "documents", action: "document.read", seatRequired: true },
  "document.get": { productKey: ENGINEERING_PRODUCT, applicationKey: "documents", action: "document.read", seatRequired: true },
  "document.create": { productKey: ENGINEERING_PRODUCT, applicationKey: "documents", action: "document.write", seatRequired: true, cachePolicy: "fresh" },
  "document.update": { productKey: ENGINEERING_PRODUCT, applicationKey: "documents", action: "document.write", seatRequired: true, cachePolicy: "fresh" },
  "document.search": { productKey: ENGINEERING_PRODUCT, applicationKey: "documents", action: "document.read", seatRequired: true },
  "decision.list": { productKey: ENGINEERING_PRODUCT, action: "decision.read", seatRequired: true },
  "decision.get": { productKey: ENGINEERING_PRODUCT, action: "decision.read", seatRequired: true },
  "decision.create": { productKey: ENGINEERING_PRODUCT, action: "decision.write", seatRequired: true, cachePolicy: "fresh" },
  "decision.search": { productKey: ENGINEERING_PRODUCT, action: "decision.read", seatRequired: true },
  "assumption.list": { productKey: ENGINEERING_PRODUCT, action: "decision.read", seatRequired: true },
  "assumption.get": { productKey: ENGINEERING_PRODUCT, action: "decision.read", seatRequired: true },
  "assumption.create": { productKey: ENGINEERING_PRODUCT, action: "decision.write", seatRequired: true, cachePolicy: "fresh" },
  "assumption.update": { productKey: ENGINEERING_PRODUCT, action: "decision.write", seatRequired: true, cachePolicy: "fresh" },
  "system.list": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "system.get": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "system.create": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "system.update": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "interface.list": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "interface.get": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "interface.create": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "interface.update": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "requirement.list": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "requirement.get": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "requirement.create": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "requirement.update": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "change.list": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "change.get": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "change.create": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "change.update": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "impact.list": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "impact.get": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "impact.create": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "impact.update": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "configuration.list": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "configuration.get": { productKey: ENGINEERING_PRODUCT, action: "asset.read", seatRequired: true },
  "configuration.create": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "configuration.update": { productKey: ENGINEERING_PRODUCT, action: "asset.write", seatRequired: true, cachePolicy: "fresh" },
  "optimization.list": { productKey: ENGINEERING_PRODUCT, action: "optimization.read", seatRequired: true },
  "optimization.get": { productKey: ENGINEERING_PRODUCT, action: "optimization.read", seatRequired: true },
  "optimization.create": { productKey: ENGINEERING_PRODUCT, action: "optimization.write", seatRequired: true, cachePolicy: "fresh" },
  "optimization.update": { productKey: ENGINEERING_PRODUCT, action: "optimization.write", seatRequired: true, cachePolicy: "fresh" },
  "analysis.list": { productKey: ENGINEERING_PRODUCT, action: "analysis.read", seatRequired: true },
  "analysis.get": { productKey: ENGINEERING_PRODUCT, action: "analysis.read", seatRequired: true },
  "analysis.create": { productKey: ENGINEERING_PRODUCT, action: "analysis.write", seatRequired: true, cachePolicy: "fresh" },
  "analysis.update": { productKey: ENGINEERING_PRODUCT, action: "analysis.write", seatRequired: true, cachePolicy: "fresh" },
  "risk.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "risk.read", seatRequired: true },
  "risk.get": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "risk.read", seatRequired: true },
  "risk.create": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "risk.write", seatRequired: true, cachePolicy: "fresh" },
  "risk.update": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "risk.write", seatRequired: true, cachePolicy: "fresh" },
  "risk.search": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "risk.read", seatRequired: true },
  "issue.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "issue.read", seatRequired: true },
  "issue.get": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "issue.read", seatRequired: true },
  "issue.create": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "issue.write", seatRequired: true, cachePolicy: "fresh" },
  "issue.search": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "issue.read", seatRequired: true },
  "action.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_controls", action: "action.read", seatRequired: true },
  "action.get": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_controls", action: "action.read", seatRequired: true },
  "action.create": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_controls", action: "action.write", seatRequired: true, cachePolicy: "fresh" },
  "action.update": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_controls", action: "action.write", seatRequired: true, cachePolicy: "fresh" },
  "action.search": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_controls", action: "action.read", seatRequired: true },
  "lesson.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "knowledge", action: "lesson.read", seatRequired: true },
  "lesson.get": { productKey: ENGINEERING_PRODUCT, applicationKey: "knowledge", action: "lesson.read", seatRequired: true },
  "lesson.create": { productKey: ENGINEERING_PRODUCT, applicationKey: "knowledge", action: "lesson.write", seatRequired: true, cachePolicy: "fresh" },
  "lesson.search": { productKey: ENGINEERING_PRODUCT, applicationKey: "knowledge", action: "lesson.read", seatRequired: true },
  "technical_query.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "technical_query.read", seatRequired: true },
  "technical_query.get": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "technical_query.read", seatRequired: true },
  "technical_query.create": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "technical_query.write", seatRequired: true, cachePolicy: "fresh" },
  "technical_query.update": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "technical_query.write", seatRequired: true, cachePolicy: "fresh" },
  "technical_query.search": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "technical_query.read", seatRequired: true },
  "company.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "company.read", seatRequired: true },
  "company.create": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "company.write", seatRequired: true, cachePolicy: "fresh" },
  "discipline.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "discipline.read", seatRequired: true },
  "search.query": { productKey: ENGINEERING_PRODUCT, action: "search.read", seatRequired: true },
  "dashboard.read": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "dashboard.read", seatRequired: true },
  "settings.get": { productKey: ENGINEERING_PRODUCT, action: "settings.read", seatRequired: true },
  "settings.update": { productKey: ENGINEERING_PRODUCT, action: "settings.write", seatRequired: true, cachePolicy: "fresh" },
  "external_tools.list": { productKey: ENGINEERING_PRODUCT, action: "settings.read", seatRequired: true },
  "external_tools.get": { productKey: ENGINEERING_PRODUCT, action: "settings.read", seatRequired: true },
  "external_tools.write": { productKey: ENGINEERING_PRODUCT, action: "settings.write", seatRequired: true, cachePolicy: "fresh" },
  "discipline_intelligence.list": { productKey: ENGINEERING_PRODUCT, action: "settings.read", seatRequired: true },
  "discipline_intelligence.get": { productKey: ENGINEERING_PRODUCT, action: "settings.read", seatRequired: true },
  "discipline_intelligence.write": { productKey: ENGINEERING_PRODUCT, action: "settings.write", seatRequired: true, cachePolicy: "fresh" },
  "application.list": { productKey: ENGINEERING_PRODUCT, action: "application.list", seatRequired: true },
  "demo.status": { productKey: ENGINEERING_PRODUCT, action: "demo.read", seatRequired: true },
  "demo.seed": { productKey: ENGINEERING_PRODUCT, action: "demo.admin", seatRequired: true, cachePolicy: "fresh" },
  "ai.execute": { productKey: ENGINEERING_PRODUCT, featureKey: "ai_assistant", action: "ai.execute", seatRequired: true, cachePolicy: "fresh" },
  "timeline.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "timeline.read", seatRequired: true },
  "activity.list": { productKey: ENGINEERING_PRODUCT, applicationKey: "project_intelligence", action: "activity.read", seatRequired: true },
};
