import type { EngineeringArtifactTemplate } from "./types";

export const BEARING_PRESSURE_FORMULA = "B4/B5";

export const ARTIFACT_TEMPLATES: EngineeringArtifactTemplate[] = [
  {
    id: "eat-calc-example-bearing",
    code: "EAT-CALC-EXAMPLE-BEARING",
    version: "1.0.0",
    name: "Synthetic bearing pressure workbook (example only)",
    artifactType: "CALCULATION_WORKBOOK",
    outputFormat: "XLSX",
    workTypes: ["DESIGN_CALCULATION"],
    lifecycleStages: ["FEED", "DETAILED_DESIGN"],
    expectedOutputType: "CALCULATION_WORKBOOK",
    readinessPolicy: "REQUIRE_READY",
    certification: "EXAMPLE_ONLY",
    sheetsOrSections: ["Cover", "Inputs", "Calculations", "Results", "References", "Assumptions", "EOS Context", "Revision History"],
    formulas: [
      {
        id: "bearing-pressure",
        cell: "B6",
        formula: BEARING_PRESSURE_FORMULA,
        description: "Synthetic bearing pressure = vertical load / plan area",
        unit: "kPa",
      },
    ],
    reviewRequired: true,
    productionEngineeringUse: false,
  },
  {
    id: "eat-report-design",
    code: "EAT-REPORT-DESIGN",
    version: "1.0.0",
    name: "Design report draft",
    artifactType: "DESIGN_REPORT",
    outputFormat: "DOCX",
    workTypes: ["DESIGN_CALCULATION", "DESIGN_REPORT", "ENGINEERING_ANALYSIS"],
    lifecycleStages: ["FEED", "DETAILED_DESIGN"],
    expectedOutputType: "DESIGN_REPORT",
    readinessPolicy: "ALLOW_READY_WITH_CONDITIONS",
    certification: "EXAMPLE_ONLY",
    sheetsOrSections: [
      "Document Control",
      "Purpose / Scope",
      "Project Context",
      "Design Basis",
      "Requirements",
      "Inputs",
      "Assumptions",
      "Interfaces",
      "Analysis",
      "Decisions",
      "Findings placeholders",
      "Limitations",
      "References",
      "Revision History",
    ],
    formulas: [],
    reviewRequired: true,
    productionEngineeringUse: false,
  },
  {
    id: "eat-spec-draft",
    code: "EAT-SPEC-DRAFT",
    version: "1.0.0",
    name: "Specification draft",
    artifactType: "SPECIFICATION",
    outputFormat: "DOCX",
    workTypes: ["SPECIFICATION"],
    lifecycleStages: ["FEED", "DETAILED_DESIGN"],
    expectedOutputType: "SPECIFICATION",
    readinessPolicy: "ALLOW_READY_WITH_CONDITIONS",
    certification: "EXAMPLE_ONLY",
    sheetsOrSections: ["Project Context", "Scope", "Requirements", "Materials placeholders", "Decisions", "Source Register"],
    formulas: [],
    reviewRequired: true,
    productionEngineeringUse: false,
  },
  {
    id: "eat-option-wb",
    code: "EAT-OPTION-WB",
    version: "1.0.0",
    name: "Option study workbook",
    artifactType: "OPTION_STUDY",
    outputFormat: "XLSX",
    workTypes: ["OPTION_STUDY"],
    lifecycleStages: ["CONCEPT", "PREFEASIBILITY", "FEED"],
    expectedOutputType: "OPTION_STUDY",
    readinessPolicy: "ALLOW_INCOMPLETE_DRAFT",
    certification: "EXAMPLE_ONLY",
    sheetsOrSections: ["Context", "Options", "Criteria", "Evidence", "Comparison", "Assumptions", "Risks", "References"],
    formulas: [],
    reviewRequired: true,
    productionEngineeringUse: false,
  },
  {
    id: "eat-option-ppt",
    code: "EAT-OPTION-PPT",
    version: "1.0.0",
    name: "Option study presentation",
    artifactType: "OPTION_STUDY_PRESENTATION",
    outputFormat: "PPTX",
    workTypes: ["OPTION_STUDY"],
    lifecycleStages: ["CONCEPT", "PREFEASIBILITY", "FEED"],
    expectedOutputType: "OPTION_STUDY",
    readinessPolicy: "ALLOW_INCOMPLETE_DRAFT",
    certification: "EXAMPLE_ONLY",
    sheetsOrSections: [
      "Title",
      "Problem / Objective",
      "Project Context",
      "Options",
      "Key Inputs",
      "Comparison",
      "Trade-offs",
      "Risks / Constraints",
      "Information Gaps",
      "Decision Required",
      "References",
    ],
    formulas: [],
    reviewRequired: true,
    productionEngineeringUse: false,
  },
  {
    id: "eat-rfi-draft",
    code: "EAT-RFI-DRAFT",
    version: "1.0.0",
    name: "RFI response draft",
    artifactType: "RFI_RESPONSE",
    outputFormat: "DOCX",
    workTypes: ["RFI_TQ_RESPONSE"],
    lifecycleStages: ["CONSTRUCTION", "COMMISSIONING"],
    expectedOutputType: "RFI_RESPONSE",
    readinessPolicy: "ALLOW_INCOMPLETE_DRAFT",
    certification: "EXAMPLE_ONLY",
    sheetsOrSections: ["Query", "Affected objects", "Sources", "Potential impacts", "Draft response", "Review"],
    formulas: [],
    reviewRequired: true,
    productionEngineeringUse: false,
  },
  {
    id: "eat-tq-draft",
    code: "EAT-TQ-DRAFT",
    version: "1.0.0",
    name: "TQ response draft",
    artifactType: "TQ_RESPONSE",
    outputFormat: "DOCX",
    workTypes: ["RFI_TQ_RESPONSE"],
    lifecycleStages: ["CONSTRUCTION", "COMMISSIONING"],
    expectedOutputType: "TQ_RESPONSE",
    readinessPolicy: "ALLOW_INCOMPLETE_DRAFT",
    certification: "EXAMPLE_ONLY",
    sheetsOrSections: ["Query", "Affected objects", "Sources", "Potential impacts", "Draft response", "Review"],
    formulas: [],
    reviewRequired: true,
    productionEngineeringUse: false,
  },
  {
    id: "eat-concept-memo",
    code: "EAT-CONCEPT-MEMO",
    version: "1.0.0",
    name: "Concept study technical memorandum",
    artifactType: "TECHNICAL_MEMORANDUM",
    outputFormat: "DOCX",
    workTypes: ["CONCEPT_STUDY"],
    lifecycleStages: ["CONCEPT"],
    expectedOutputType: "CONCEPT_STUDY",
    readinessPolicy: "ALLOW_INCOMPLETE_DRAFT",
    certification: "EXAMPLE_ONLY",
    sheetsOrSections: ["Purpose", "Context", "Assumptions", "Missing information", "Limitations"],
    formulas: [],
    reviewRequired: true,
    productionEngineeringUse: false,
  },
];

export function listArtifactTemplates() {
  return ARTIFACT_TEMPLATES;
}

export function findArtifactTemplate(code: string, version?: string) {
  return ARTIFACT_TEMPLATES.find((row) => row.code === code && (!version || row.version === version)) ?? null;
}

export function templatesForExpectedOutput(expectedOutputType: EngineeringArtifactTemplate["expectedOutputType"]) {
  return ARTIFACT_TEMPLATES.filter((row) => row.expectedOutputType === expectedOutputType);
}
