import type { UsShearMethodRecord } from "@rtb/types";
import { AISC_UNKNOWN_EDITION_TOKEN } from "@rtb/types";

export const US_SHEAR_IMPLEMENTATION_VERSION = "us-shear-1.0.0" as const;
export const US_SHEAR_TOOL_REF = "EOS_US_STEEL_SHEAR" as const;

const MECHANICS_YIELD = "established-mechanics-von-mises-pure-shear-yield-fy-over-sqrt-3-times-governed-shear-area";
const MECHANICS_BUCKLING = "established-mechanics-elastic-plate-shear-buckling-kv-pi2-E-over-12-1-nu2-d-over-t-squared-times-Av";
const EDITIONS = [AISC_UNKNOWN_EDITION_TOKEN] as const;

export const US_SHEAR_ELASTIC_MAJOR_MECHANICS_RULE: UsShearMethodRecord = {
  ruleId: "US-SHEAR-ELASTIC-MAJOR-MECHANICS-V1",
  methodId: "US_SHEAR_ELASTIC_MAJOR_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_YIELD,
  calculationPurpose: "von Mises pure-shear yield force for major-axis shear as a mechanics reference, not AISC Vn",
  applicability: "steel members with explicit Fy and a governed shear area for major-axis shear",
  requiredInputs: ["material.yieldStrength", "section.shearArea"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_SHEAR",
  units: "N",
  implementationVersion: US_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-SHEAR-BM-YIELD-MAJOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-shear-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ELASTIC_SHEAR_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "MAJOR_SHEAR",
  factorDependencies: [],
  localAmendmentDependencies: [],
  shearAreaDependency: true,
  webSlendernessDependency: false,
  panelDependency: false,
  stiffenerDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_SHEAR_ELASTIC_MINOR_MECHANICS_RULE: UsShearMethodRecord = {
  ruleId: "US-SHEAR-ELASTIC-MINOR-MECHANICS-V1",
  methodId: "US_SHEAR_ELASTIC_MINOR_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_YIELD,
  calculationPurpose: "von Mises pure-shear yield force for minor-axis shear as a mechanics reference, not AISC Vn",
  applicability: "steel members with explicit Fy and a governed shear area for minor-axis shear",
  requiredInputs: ["material.yieldStrength", "section.shearArea"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_SHEAR",
  units: "N",
  implementationVersion: US_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-SHEAR-BM-YIELD-MINOR-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-shear-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ELASTIC_SHEAR_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "MINOR_SHEAR",
  factorDependencies: [],
  localAmendmentDependencies: [],
  shearAreaDependency: true,
  webSlendernessDependency: false,
  panelDependency: false,
  stiffenerDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_SHEAR_ELASTIC_BUCKLING_MECHANICS_RULE: UsShearMethodRecord = {
  ruleId: "US-SHEAR-ELASTIC-BUCKLING-MECHANICS-V1",
  methodId: "US_SHEAR_ELASTIC_BUCKLING_MECHANICS",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "ESTABLISHED_ENGINEERING_MECHANICS",
  technicalBasisRef: MECHANICS_BUCKLING,
  calculationPurpose: "elastic plate shear-buckling force as a mechanics reference; kv is never defaulted",
  applicability: "plates with explicit E, Poisson ratio, web depth, web thickness, governed Av, and supplied kv",
  requiredInputs: ["material.elasticModulus", "material.poissonRatio", "section.webDepth", "section.webThickness", "section.shearArea", "shear.shearBucklingCoefficient"],
  outputType: "MECHANICS_REFERENCE_ELASTIC_SHEAR_BUCKLING",
  units: "N",
  implementationVersion: US_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "BENCHMARKED",
  benchmarkRefs: ["US-SHEAR-BM-BUCKLING-HAND-1"],
  humanReviewState: "required",
  provenanceRef: "us-shear-mechanics-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "IMPLEMENTED_UNVERIFIED_STANDARD_BINDING",
  methodType: "ELASTIC_SHEAR_BUCKLING_REFERENCE",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "WEB",
  factorDependencies: [],
  localAmendmentDependencies: [],
  shearAreaDependency: true,
  webSlendernessDependency: true,
  panelDependency: true,
  stiffenerDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "MECHANICS_REFERENCE_ONLY",
};

export const US_SECTION_SHEAR_STRENGTH_CODE_PROFILE_RULE: UsShearMethodRecord = {
  ruleId: "US-SECTION-SHEAR-STRENGTH-CODE-PROFILE-V1",
  methodId: "US_SECTION_SHEAR_STRENGTH_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-section-shear-strength-validation-required",
  calculationPurpose: "AISC-profile section shear strength",
  applicability: "not implemented; requires governed shear-area rule, edition, slenderness, and factors",
  requiredInputs: ["material.yieldStrength", "section.shearArea", "classification", "edition"],
  outputType: "AISC_NOMINAL_SHEAR_STRENGTH",
  units: "N",
  implementationVersion: US_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_SHEAR_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "SHEAR",
  factorDependencies: [],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  shearAreaDependency: true,
  webSlendernessDependency: true,
  panelDependency: false,
  stiffenerDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_SHEAR_LRFD_RULE: UsShearMethodRecord = {
  ruleId: "US-SHEAR-LRFD-V1",
  methodId: "US_SHEAR_LRFD",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-lrfd-shear-design-strength-validation-required",
  calculationPurpose: "AISC-profile LRFD shear design strength φvVn",
  applicability: "not implemented; φv unpopulated; edition unknown",
  requiredInputs: ["Vn", "phi_v", "designMethod=LRFD"],
  outputType: "AISC_LRFD_DESIGN_STRENGTH",
  units: "N",
  implementationVersion: US_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_LRFD_DESIGN_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "LRFD",
  axis: "SHEAR",
  factorDependencies: ["phi_v"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  shearAreaDependency: true,
  webSlendernessDependency: true,
  panelDependency: true,
  stiffenerDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_SHEAR_ASD_RULE: UsShearMethodRecord = {
  ruleId: "US-SHEAR-ASD-V1",
  methodId: "US_SHEAR_ASD",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-asd-shear-allowable-strength-validation-required",
  calculationPurpose: "AISC-profile ASD allowable shear strength Vn/Ωv",
  applicability: "not implemented; Ωv unpopulated; edition unknown",
  requiredInputs: ["Vn", "Omega_v", "designMethod=ASD"],
  outputType: "AISC_ASD_ALLOWABLE_STRENGTH",
  units: "N",
  implementationVersion: US_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_ASD_ALLOWABLE_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "ASD",
  axis: "SHEAR",
  factorDependencies: ["Omega_v"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  shearAreaDependency: true,
  webSlendernessDependency: true,
  panelDependency: true,
  stiffenerDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "FRAMEWORK_ONLY",
};

export const US_WEB_SLENDERNESS_CODE_PROFILE_RULE: UsShearMethodRecord = {
  ruleId: "US-WEB-SLENDERNESS-CODE-PROFILE-V1",
  methodId: "US_WEB_SLENDERNESS_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-web-slenderness-limits-validation-required",
  calculationPurpose: "AISC-profile web slenderness limits for shear",
  applicability: "not implemented; h/tw limits unvalidated",
  requiredInputs: ["section.webDepth", "section.webThickness", "material.yieldStrength", "edition"],
  outputType: "AISC_NOMINAL_SHEAR_STRENGTH",
  units: "1",
  implementationVersion: US_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_SHEAR_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "SLENDERNESS",
  factorDependencies: [],
  localAmendmentDependencies: [],
  shearAreaDependency: false,
  webSlendernessDependency: true,
  panelDependency: false,
  stiffenerDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "VALIDATION_REQUIRED",
};

export const US_WEB_STABILITY_CODE_PROFILE_RULE: UsShearMethodRecord = {
  ruleId: "US-WEB-STABILITY-CODE-PROFILE-V1",
  methodId: "US_WEB_STABILITY_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-web-shear-stability-validation-required",
  calculationPurpose: "AISC-profile web buckling/stability for shear",
  applicability: "not implemented; requires kv, slenderness, panel/stiffener, edition, and factors",
  requiredInputs: ["section.webDepth", "section.webThickness", "panel geometry", "stiffener context", "edition"],
  outputType: "AISC_NOMINAL_SHEAR_STRENGTH",
  units: "N",
  implementationVersion: US_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_SHEAR_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "WEB",
  factorDependencies: ["kv"],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  shearAreaDependency: true,
  webSlendernessDependency: true,
  panelDependency: true,
  stiffenerDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "VALIDATION_REQUIRED",
};

export const US_TENSION_FIELD_CODE_PROFILE_RULE: UsShearMethodRecord = {
  ruleId: "US-TENSION-FIELD-CODE-PROFILE-V1",
  methodId: "US_TENSION_FIELD_CODE_PROFILE",
  jurisdiction: "united-states",
  standardProfileRef: "us-steel-aisc360-intended",
  authorityType: "AUTHORITATIVE_STANDARD_DERIVED",
  technicalBasisRef: "aisc-tension-field-post-buckling-validation-required",
  calculationPurpose: "AISC-profile tension-field / post-buckling shear resistance",
  applicability: "not implemented; tension-field action is unvalidated and not numerically executed",
  requiredInputs: ["panel geometry", "stiffener context", "edition", "eligibility"],
  outputType: "AISC_NOMINAL_SHEAR_STRENGTH",
  units: "N",
  implementationVersion: US_SHEAR_IMPLEMENTATION_VERSION,
  validationState: "FRAMEWORK_ONLY",
  benchmarkRefs: [],
  humanReviewState: "required",
  provenanceRef: "us-shear-code-profile-unvalidated-v1",
  clauseRef: null,
  intendedStandardProfile: "AISC360",
  standardConformanceState: "INTENDED_PROFILE",
  bindingState: "FRAMEWORK_ONLY",
  methodType: "AISC_NOMINAL_SHEAR_STRENGTH",
  aiscEditionRequirement: AISC_UNKNOWN_EDITION_TOKEN,
  designMethodApplicability: "BOTH",
  axis: "PANEL",
  factorDependencies: [],
  localAmendmentDependencies: ["localAmendmentSetRef"],
  shearAreaDependency: true,
  webSlendernessDependency: true,
  panelDependency: true,
  stiffenerDependency: true,
  compatibleEditions: EDITIONS,
  scopeState: "NOT_IMPLEMENTED",
};

export const US_SHEAR_METHOD_REGISTRY: readonly UsShearMethodRecord[] = [
  US_SHEAR_ELASTIC_MAJOR_MECHANICS_RULE,
  US_SHEAR_ELASTIC_MINOR_MECHANICS_RULE,
  US_SHEAR_ELASTIC_BUCKLING_MECHANICS_RULE,
  US_SECTION_SHEAR_STRENGTH_CODE_PROFILE_RULE,
  US_SHEAR_LRFD_RULE,
  US_SHEAR_ASD_RULE,
  US_WEB_SLENDERNESS_CODE_PROFILE_RULE,
  US_WEB_STABILITY_CODE_PROFILE_RULE,
  US_TENSION_FIELD_CODE_PROFILE_RULE,
];

export const IMPLEMENTED_US_SHEAR_METHODS = [
  US_SHEAR_ELASTIC_MAJOR_MECHANICS_RULE.methodId,
  US_SHEAR_ELASTIC_MINOR_MECHANICS_RULE.methodId,
  US_SHEAR_ELASTIC_BUCKLING_MECHANICS_RULE.methodId,
] as const;

export const FRAMEWORK_ONLY_US_SHEAR_METHODS = [
  US_SECTION_SHEAR_STRENGTH_CODE_PROFILE_RULE.methodId,
  US_SHEAR_LRFD_RULE.methodId,
  US_SHEAR_ASD_RULE.methodId,
  US_WEB_SLENDERNESS_CODE_PROFILE_RULE.methodId,
  US_WEB_STABILITY_CODE_PROFILE_RULE.methodId,
  US_TENSION_FIELD_CODE_PROFILE_RULE.methodId,
] as const;
