/**
 * Phase 10E certification gates A–AW.
 */
export const PHASE_10E_ASSET_INTELLIGENCE_FAILURE_GATES = [
  ["A", "Repository/build identity"],
  ["B", "Phase 10A regression"],
  ["C", "Phase 10B regression"],
  ["D", "Phase 10B.1 persistence regression"],
  ["E", "Phase 10C regression"],
  ["F", "Phase 10D regression"],
  ["G", "PI v1 integrity"],
  ["H", "II v1 integrity"],
  ["I", "Ownership lock"],
  ["J", "Failure terminology"],
  ["K", "Failure Taxonomy Registry"],
  ["L", "Pack taxonomy compatibility"],
  ["M", "Failure Mode state"],
  ["N", "Failure Mechanism state"],
  ["O", "Cause governance"],
  ["P", "Effect model"],
  ["Q", "Consequence model"],
  ["R", "Detection provenance"],
  ["S", "Evidence Confidence integration"],
  ["T", "Evidence sufficiency"],
  ["U", "Failure Intelligence Engine"],
  ["V", "Governed review"],
  ["W", "Root Cause governance"],
  ["X", "Hosted migration"],
  ["Y", "Hosted failure persistence"],
  ["Z", "Taxonomy versioning"],
  ["AA", "State versioning"],
  ["AB", "Snapshot integration"],
  ["AC", "Timeline"],
  ["AD", "Health composition boundary"],
  ["AE", "Failure/degradation boundary"],
  ["AF", "Failure/reliability boundary"],
  ["AG", "II public-contract boundary"],
  ["AH", "AI governance"],
  ["AI", "Real JWT role matrix"],
  ["AJ", "Tenant isolation"],
  ["AK", "Workspace isolation"],
  ["AL", "IDOR"],
  ["AM", "Idempotency"],
  ["AN", "Concurrency"],
  ["AO", "Event/outbox integrity"],
  ["AP", "HTTP contracts"],
  ["AQ", "Health/observability"],
  ["AR", "Performance"],
  ["AS", "No memory production"],
  ["AT", "No predictive/PoF/RUL claims"],
  ["AU", "Secret exposure"],
  ["AV", "Artifact identity"],
  ["AW", "Phase 10F readiness"],
] as const;

export type Phase10eGateId = (typeof PHASE_10E_ASSET_INTELLIGENCE_FAILURE_GATES)[number][0];
