/**
 * Approved claim library + disclosure policy seeds for Customer Assurance.
 * Truthful enterprise wording only — no certification claims.
 */

import type {
  AssuranceClaimReference,
  AssuranceDisclosurePolicy,
  AssuranceDocumentReference,
  CustomerAssuranceProfile,
  CustomerSecurityQuestionnaireResponseReference,
  SubprocessorAssuranceReference,
} from "../../customer-assurance-contracts";

export const SEED_DISCLOSURE_POLICIES: AssuranceDisclosurePolicy[] = [
  {
    policyId: "pol-ca-customer-safe",
    version: "1.0.0",
    audience: "authenticated_customer",
    allowedLevels: ["public", "customer_safe"],
    usesPlatformPolicyEngine: true,
    failClosedOnUnknownClassification: true,
    automaticExternalDisclosureEnabled: false,
  },
  {
    policyId: "pol-ca-reviewer",
    version: "1.0.0",
    audience: "auditor_reviewer",
    allowedLevels: ["public", "customer_safe", "approved_reviewer"],
    usesPlatformPolicyEngine: true,
    failClosedOnUnknownClassification: true,
    automaticExternalDisclosureEnabled: false,
  },
  {
    policyId: "pol-ca-internal",
    version: "1.0.0",
    audience: "internal_only",
    allowedLevels: [
      "public",
      "customer_safe",
      "approved_reviewer",
      "restricted_internal",
    ],
    usesPlatformPolicyEngine: true,
    failClosedOnUnknownClassification: true,
    automaticExternalDisclosureEnabled: false,
  },
];

const now = "2026-08-09T00:00:00.000Z";

export const SEED_APPROVED_CLAIMS: AssuranceClaimReference[] = [
  {
    claimId: "claim-mfa-privileged",
    version: "1.0.0",
    claimType: "identity_access",
    statementKey: "mfa_privileged_access",
    statement:
      "Multi-factor authentication for privileged access is supported within current certified platform scope.",
    scope: "platform",
    controlRefs: ["RTB-SEC-S01"],
    assessmentRefs: [],
    evidenceRefs: ["ev-ca-mfa"],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "supported",
    limitations: ["Scope-limited to current Security & Assurance certified controls"],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-tenant-isolation",
    version: "1.0.0",
    claimType: "isolation",
    statementKey: "tenant_isolation",
    statement:
      "Tenant isolation is supported within the current certified Isolation Assurance scope.",
    scope: "platform",
    controlRefs: ["RTB-SEC-ISO-BASE"],
    assessmentRefs: [],
    evidenceRefs: ["ev-ca-isolation"],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "supported",
    limitations: [
      "Does not expose probe methodology or other-tenant identities",
      "Verification within certified scope only",
    ],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-eos-security-ga",
    version: "1.0.0",
    claimType: "secure_sdlc",
    statementKey: "engineering_os_security_ga_gate",
    statement:
      "Engineering OS security GA gate is supported via frozen V1 integrity and Security & Assurance certification lineage.",
    scope: "platform",
    controlRefs: ["RTB-SEC-S07"],
    assessmentRefs: [],
    evidenceRefs: ["ev-ca-eos"],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "supported",
    limitations: [],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-external-pentest",
    version: "1.0.0",
    claimType: "external_assurance",
    statementKey: "external_penetration_test",
    statement:
      "External penetration testing is required before Tier-1 production (S07) and is not completed.",
    scope: "platform",
    controlRefs: ["RTB-SEC-S07"],
    assessmentRefs: [],
    evidenceRefs: [],
    externalAssuranceRefs: ["ext-pen-s07"],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "requires_external_assurance",
    limitations: ["penetration test planned ≠ penetration test completed"],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-customer-sso",
    version: "1.0.0",
    claimType: "identity_access",
    statementKey: "customer_sso",
    statement:
      "Customer SSO is architecturally supported via Platform Identity but is not production-ready (S08).",
    scope: "platform",
    controlRefs: ["RTB-SEC-S08"],
    assessmentRefs: [],
    evidenceRefs: [],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "partially_supported",
    limitations: ["SSO supported architecturally ≠ customer SSO production-ready"],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-iso27001",
    version: "1.0.0",
    claimType: "framework",
    statementKey: "iso27001_status",
    statement: "ISO/IEC 27001 control mapping is available. RTB is not ISO 27001 certified.",
    scope: "platform",
    controlRefs: ["RTB-SEC-S01"],
    assessmentRefs: [],
    evidenceRefs: [],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "not_disclosed",
    limitations: ["framework mapping ≠ compliance claim", "not certified"],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-soc2",
    version: "1.0.0",
    claimType: "framework",
    statementKey: "soc2_status",
    statement: "SOC 2 Trust Services Criteria mapping scaffold only. RTB is not SOC 2 attested.",
    scope: "platform",
    controlRefs: ["RTB-SEC-S01"],
    assessmentRefs: [],
    evidenceRefs: [],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "not_disclosed",
    limitations: ["mapping scaffold only — not an attestation"],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-essential-eight",
    version: "1.0.0",
    claimType: "framework",
    statementKey: "essential_eight_status",
    statement:
      "Australian Essential Eight applicability/mapping is assessed. Maturity is not claimed.",
    scope: "platform",
    controlRefs: ["RTB-SEC-S01"],
    assessmentRefs: [],
    evidenceRefs: [],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "partially_supported",
    limitations: ["applicability assessed; maturity not claimed"],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-ai-training",
    version: "1.0.0",
    claimType: "ai_security",
    statementKey: "ai_training_use",
    statement:
      "AI training-use posture derives only from approved provider and data-governance policy references.",
    scope: "platform",
    controlRefs: ["RTB-SEC-S05"],
    assessmentRefs: [],
    evidenceRefs: ["ev-ca-ai"],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "supported",
    limitations: ["Does not disclose system prompts or guardrail internals"],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-backup-restore",
    version: "1.0.0",
    claimType: "backup_recovery",
    statementKey: "backup_restore",
    statement:
      "Backup restore is tested within documented scope. RPO=DEFINED_NOT_TESTED; RTO=MEASURED (not SLA).",
    scope: "platform",
    controlRefs: ["RTB-SEC-S07"],
    assessmentRefs: [],
    evidenceRefs: ["ev-ca-backup"],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "supported",
    limitations: ["backup tested ≠ contractual SLA", "RPO/RTO are not marketed as SLA"],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-secure-compute",
    version: "1.0.0",
    claimType: "secure_compute",
    statementKey: "secure_compute_assurance",
    statement:
      "Secure compute assurance covers execution isolation, provider qualification, no silent solver fallback, and workspace isolation within certified scope.",
    scope: "platform",
    controlRefs: ["RTB-SEC-SC-BASE"],
    assessmentRefs: [],
    evidenceRefs: ["ev-ca-secure-compute"],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "supported",
    limitations: [
      "Does not reveal host secrets, network topology attack detail, or licence credentials",
    ],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-secure-sdlc",
    version: "1.0.0",
    claimType: "secure_sdlc",
    statementKey: "secure_sdlc_assurance",
    statement:
      "Secure SDLC assurance covers dependency SCA, secret scanning, build identity, and security certification gates within approved evidence scope.",
    scope: "platform",
    controlRefs: ["RTB-SEC-S06"],
    assessmentRefs: [],
    evidenceRefs: ["ev-ca-sdlc"],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "supported",
    limitations: ["Does not expose raw vulnerability inventory publicly"],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-incident-readiness",
    version: "1.0.0",
    claimType: "incident_readiness",
    statementKey: "incident_response_process",
    statement:
      "An incident-response process exists with approved process summary and contact pathway.",
    scope: "platform",
    controlRefs: ["RTB-SEC-S04"],
    assessmentRefs: [],
    evidenceRefs: ["ev-ca-incident"],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "supported",
    limitations: [
      "Does not expose internal incidents, active findings, forensics, or customer-impact details by default",
    ],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
  {
    claimId: "claim-data-residency",
    version: "1.0.0",
    claimType: "data_governance",
    statementKey: "data_residency",
    statement:
      "Data residency state is not_verified pending authoritative Platform Governance metadata confirmation.",
    scope: "platform",
    controlRefs: [],
    assessmentRefs: [],
    evidenceRefs: [],
    externalAssuranceRefs: [],
    effectiveAt: now,
    reviewStatus: "approved",
    disclosureLevel: "customer_safe",
    status: "unknown",
    limitations: [
      "Do not infer residency from tenant identity",
      "Do not invent legal sovereignty guarantees",
    ],
    requiresAuthoritativeSupport: true,
    certificationWordingForbidden: true,
  },
];

export const SEED_ASSURANCE_DOCUMENTS: AssuranceDocumentReference[] = [
  {
    documentId: "doc-security-overview",
    title: "Platform Security Overview",
    version: "1.0.0",
    platformFileRef: "files:security-overview-v1",
    classification: "INTERNAL",
    disclosureLevel: "customer_safe",
    effectiveAt: now,
    owner: "Security & Assurance",
    approvalStatus: "approved",
    usesPlatformFiles: true,
  },
  {
    documentId: "doc-incident-response",
    title: "Incident Response Process Summary",
    version: "1.0.0",
    platformFileRef: "files:incident-response-summary-v1",
    classification: "INTERNAL",
    disclosureLevel: "customer_safe",
    effectiveAt: now,
    owner: "Security & Assurance",
    approvalStatus: "approved",
    usesPlatformFiles: true,
  },
];

export const SEED_CUSTOMER_PROFILE: CustomerAssuranceProfile = {
  profileId: "profile-platform-default",
  version: "1.0.0",
  scope: "platform",
  categories: [
    "security_governance",
    "identity_access",
    "tenant_isolation",
    "data_protection",
    "ai_security",
    "secure_compute",
    "secure_sdlc",
    "incident_readiness",
    "backup_recovery",
    "external_assurance",
    "framework_coverage",
    "data_residency",
    "subprocessors",
    "customer_data_use_policy",
    "enterprise_identity_capability",
  ],
  approvedClaimIds: SEED_APPROVED_CLAIMS.map((c) => c.claimId),
  approvedDocumentIds: SEED_ASSURANCE_DOCUMENTS.map((d) => d.documentId),
  disclosureLevel: "customer_safe",
  reviewStatus: "approved",
  effectiveAt: now,
  limitations: [
    "customer assurance ≠ certification",
    "security posture ≠ guarantee of security",
  ],
  certificationClaimed: false,
};

export const SEED_QUESTIONNAIRE_RESPONSES: CustomerSecurityQuestionnaireResponseReference[] =
  [
    {
      responseId: "qresp-mfa",
      questionId: "q-mfa",
      canonicalTopic: "mfa",
      approvedClaimRefs: ["claim-mfa-privileged"],
      approvedDocumentRefs: ["doc-security-overview"],
      responseStatus: "supported",
      lastReviewed: now,
      reviewer: "security_assurance_admin",
      limitations: [],
      inventedResponseForbidden: true,
    },
    {
      responseId: "qresp-iso",
      questionId: "q-iso27001",
      canonicalTopic: "iso27001",
      approvedClaimRefs: ["claim-iso27001"],
      approvedDocumentRefs: [],
      responseStatus: "not_disclosed",
      lastReviewed: now,
      reviewer: "security_assurance_admin",
      limitations: ["Do not claim ISO certification"],
      inventedResponseForbidden: true,
    },
  ];

export const SEED_SUBPROCESSORS: SubprocessorAssuranceReference[] = [
  {
    subprocessorId: "sub-supabase",
    provider: "Supabase",
    purpose: "identity_and_data_platform",
    dataCategories: ["identity", "application_data"],
    regionVerified: "not_verified",
    contractPolicyRef: "policy:subprocessor-supabase",
    aiProviderFlag: false,
    status: "active",
    reviewedAt: now,
  },
];
